- etc/brick-types.api.md
- packages/brick-types/src/manifest.ts
> fix(): 增加AuthInfo接口字段 refs USER-4

- packages/brick-kit/src/core/LocationContext.ts
> fix(): 修复formRender中properties的表达式无法解析

- packages/custom-antd-styles/src/table.less
ref: MONITOR-4549
请勾选以下两组选项其中之一：
或者：
>
>
> fix(table-less): 复原filter图标位置样式

- packages/brick-kit/src/BrickAsComponent.spec.tsx
- packages/brick-kit/src/BrickAsComponent.tsx
- packages/brick-kit/src/core/CustomForms/ExpandCustomForm.ts
- packages/brick-kit/src/core/Kernel.ts
- packages/brick-kit/src/core/LocationContext.ts
- packages/brick-kit/src/core/Runtime.ts
which allows usage of useBrick with tpl resolve state
Closes NEXT_BUILDER-2466
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support useBrick with tpl resolve state 

- packages/brick-kit/src/internal/menu.spec.ts
- packages/brick-kit/src/internal/menu.ts
Closes NEXT_BUILDER-2472
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix menu with PERMISSIONS.check

- packages/brick-kit/src/core/Kernel.ts
- packages/brick-kit/src/core/Router.ts
- packages/brick-kit/src/core/Runtime.ts
> fix(): favicon repeat render

- packages/brick-container/src/styles/theme/dark.css
- packages/brick-container/src/styles/theme/default.css
- packages/custom-antd-styles/src/button.less
close BRICK_STORE-3204
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 更改button样式 更改info和danger的颜色 size为sm的尺寸

- packages/brick-kit/src/auth.ts
> fix(): 增加userShowValue字段 refs USER-4

- packages/brick-container/src/styles/theme/default.css
- packages/brick-container/src/styles/variables.css
- packages/custom-antd-styles/src/button.less
- packages/custom-antd-styles/src/card.less
- packages/custom-antd-styles/src/date-picker.less
- packages/custom-antd-styles/src/input.less
> fix(): 更改构件圆角

- packages/brick-kit/src/core/Kernel.spec.ts
- packages/brick-kit/src/core/Kernel.ts
- packages/brick-kit/src/core/LocationContext.spec.ts
- packages/brick-kit/src/core/LocationContext.ts
- packages/brick-kit/src/core/Router.spec.ts
- packages/brick-kit/src/core/Router.ts
Closes NEXT_BUILDER-2476
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): concurrently load bricks and business apis

- packages/brick-kit/src/core/Kernel.spec.ts
- packages/brick-kit/src/core/Kernel.ts
- packages/brick-utils/src/getDllAndDepsOfStoryboard.spec.ts
- packages/brick-utils/src/getDllAndDepsOfStoryboard.ts
Custom processors needs to be blocked
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix concurrently load bricks and business apis

- etc/brick-kit.api.md
- packages/brick-kit/src/BrickAsComponent.spec.tsx
- packages/brick-kit/src/BrickAsComponent.tsx
- packages/brick-kit/src/core/CustomForms/constants.ts
- packages/brick-kit/src/transformProperties.ts
> feat(): brickAsComponent支持form_state表达式解析，refs: ITSERVICE_NEXT-5450

- packages/dev-dependencies/patch.js
> feat(): enable --runInBand for test:ci

- packages/brick-kit/src/core/Runtime.ts
> fix(): fix brick preview with provider

- .size-limit.js
- etc/brick-kit.api.md
- packages/brick-container/src/preview.ejs
- packages/brick-container/src/preview.ts
- packages/brick-container/src/styles/preview.css
- packages/brick-container/webpack/common.js
- packages/brick-kit/src/core/Router.ts
- packages/brick-kit/src/core/Runtime.ts
- packages/brick-kit/src/developHelper.ts
Refs NEXT_BUILDER-2455
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support brick preview in iframe

- packages/brick-kit/src/core/CustomForms/ExpandCustomForm.ts
> feat(): 支持formschema渲染不携带根容器，refs: ITSERVICE_NEXT-5472

- packages/brick-container/src/styles/variables.css
- packages/custom-antd-styles/src/button.less
- packages/custom-antd-styles/src/card.less
- packages/custom-antd-styles/src/input.less
> fix(): 改变组件间距以及input和button的圆角

- packages/brick-kit/src/core/Kernel.spec.ts
- packages/brick-kit/src/core/Kernel.ts
- packages/brick-utils/src/getDllAndDepsOfStoryboard.spec.ts
- packages/brick-utils/src/getDllAndDepsOfStoryboard.ts
> fix(): fix loading widgets

- packages/brick-kit/src/core/CustomForms/ExpandCustomForm.ts
> feat(FORMBUILDER): 新增params内置formstate，废弃condition功能

- packages/brick-kit/src/internal/menu.spec.ts
- packages/brick-kit/src/internal/menu.ts
fixes CD-3478
请勾选以下两组选项其中之一：
- [*] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。
或者：
>
>
> fix(): 修复overrideApp没有合并defaultConfig和userConfig的问题

- packages/custom-antd-styles/src/input.less
- packages/custom-antd-styles/src/radio.less
- packages/custom-antd-styles/src/select.less
- packages/custom-antd-styles/src/upload.less
close BRICK_STORE-3221
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修改select及upload等组件的radius

- packages/brick-container/src/styles/variables.css
- packages/custom-antd-styles/src/card.less
close BRICK_STORE-3202
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修改卡片间距

- packages/brick-container/src/styles/variables.css
- packages/custom-antd-styles/src/input.less
close BRICK_STORE-3221
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修改构件圆角样式

- packages/custom-antd-styles/src/input.less
> fix(): changeBorderRadiusOfInputGroup

- packages/custom-antd-styles/src/input.less
> fix(): fixBorderRadiusOfInputGroupfist-child

- declarations/global.d.ts
- packages/brick-kit/package.json
- packages/brick-kit/src/core/standaloneBootstrap.spec.ts
- packages/brick-kit/src/core/standaloneBootstrap.ts
- yarn.lock
Refs NEXT_BUILDER-2514
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support devloper brick preview

- packages/custom-antd-styles/src/pagination.less
- packages/custom-antd-styles/src/select.less
close BRICK_STORE-3229
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修改select-dropdown和pagination的border-radius

- bricks/basic/package.json
- bricks/basic/src/bootstrap.ts
- bricks/basic/src/button/button.shadow.css
- bricks/basic/src/button/example.html
- bricks/basic/src/button/index.tsx
- bricks/basic/src/interface.ts
- bricks/basic/src/style/dark.css
- bricks/basic/src/style/default.css
- bricks/basic/src/style/generated.css
- bricks/basic/src/style/index.css
- bricks/basic/src/style/index.tsx
- bricks/basic/src/style/variables.css
- yarn.lock
> feat(): support button component

- packages/brick-kit/src/BrickAsComponent.spec.tsx
- packages/brick-kit/src/BrickAsComponent.tsx
> fix(useBrick): wait for brick being loaded before rendering

- bricks/basic/src/bootstrap.ts
- bricks/basic/src/button/button.shadow.css
- bricks/basic/src/interface.ts
- bricks/basic/src/link/example.html
- bricks/basic/src/link/index.tsx
- bricks/basic/src/link/link.shadow.css
> feat(): support link component

- bricks/basic/src/bootstrap.ts
- bricks/basic/src/flex-layout/example.html
- bricks/basic/src/flex-layout/flex-layout.shadow.css
- bricks/basic/src/flex-layout/index.spec.tsx
- bricks/basic/src/flex-layout/index.tsx
Refs BRICK_STORE-3234
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): flex-layout brick

- packages/sdk-scripts/src/loaders/loadService.ts
> fix(loadService): ignore non-yaml files

- bricks/basic/src/bootstrap.ts
- bricks/basic/src/button/button.shadow.css
- bricks/basic/src/button/index.tsx
- bricks/basic/src/link/index.tsx
- bricks/basic/src/modal/example.html
- bricks/basic/src/modal/index.tsx
- bricks/basic/src/modal/modal.shadow.css
> feat(): support Modal component

- packages/brick-container/tools/report_installed_brick_next_package.py
> fix(report_nb): nb上报脚本修改\n Ref: NEXT_BUILDER-2621

- bricks/basic/src/bootstrap.ts
- bricks/basic/src/input/example.html
- bricks/basic/src/input/index.tsx
- bricks/basic/src/input/input.shadow.css
- bricks/basic/src/interface.ts
> feat(): support Input component

- bricks/basic/src/bootstrap.ts
- bricks/basic/src/textarea/calculateAutoSizeStyle.ts
- bricks/basic/src/textarea/example.html
- bricks/basic/src/textarea/index.tsx
- bricks/basic/src/textarea/textarea.shadow.css
> feat(): support Textarea component

- bricks/basic/src/bootstrap.ts
- bricks/demo-basic/package.json
- bricks/demo-form/package.json
- bricks/icons/build.config.js
- bricks/icons/package.json
- bricks/icons/scripts/pre-build.js
- bricks/icons/src/bootstrap.ts
- bricks/icons/src/easyops-icon/.gitignore
- bricks/icons/src/easyops-icon/index.tsx
- bricks/icons/src/fa-icon/.gitignore
- bricks/icons/src/fa-icon/index.tsx
- bricks/icons/src/index.ts
- bricks/icons/tsconfig.json
- declarations/global.d.ts
- mock-micro-apps/test/storyboard.yaml
- packages/build-next-bricks/package.json
- packages/build-next-bricks/src/build.js
- yarn.lock
> feat(): new bricks: icons.easyops-icon and icons.fa-icon

- CONTRIBUTING-V3.md
- packages/brick-playground/build.config.js
- packages/brick-playground/package.json
- packages/brick-playground/src/index.css
- packages/brick-playground/src/index.ejs
- packages/brick-playground/src/index.ts
- packages/brick-playground/src/preview-bootstrap.ts
- packages/brick-playground/src/preview.css
- packages/brick-playground/src/preview.ejs
- packages/runtime/src/internal/Renderer.ts
- packages/runtime/src/internal/Runtime.ts
- packages/runtime/src/internal/secretInternals.ts
> feat(): support play bricks with yaml

- bricks/demo-widgets/build.config.js
- bricks/demo-widgets/package.json
- bricks/demo-widgets/src/bootstrap.ts
- bricks/demo-widgets/src/index.ts
- bricks/demo-widgets/src/tpl-first-template.ts
- bricks/demo-widgets/src/tpl-second-template.ts
- bricks/demo-widgets/tsconfig.json
- mock-micro-apps/test/storyboard.yaml
- packages/build-next-bricks/src/scanBricks.js
- packages/runtime/src/internal/Renderer.ts
> feat(): support widget packages

- CONTRIBUTING-V3.md
- mock-micro-apps/test/storyboard.yaml
- packages/brick-types/src/manifest.ts
- packages/runtime/src/internal/CustomTemplates/constants.ts
- packages/runtime/src/internal/CustomTemplates/expandCustomTemplate.ts
- packages/runtime/src/internal/CustomTemplates/setupTemplateProxy.ts
- packages/runtime/src/internal/Renderer.ts
- packages/runtime/src/internal/compute/evaluate.ts
- packages/runtime/src/internal/interfaces.ts
- yarn.lock
> feat(): support control nodes: forEach/if/switch

- etc/brick-types.api.md
- packages/brick-kit/src/core/Router.ts
- packages/brick-types/src/manifest.ts
> fix(): fix setting favicon not render

- packages/brick-icons/src/icons/condition-config-fill.svg
- packages/custom-antd-styles/src/table.less
refs BRICK_STORE-3251
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): BRICK_STORE-3251 【表格组件】表头筛选图标颜色需替换为 #8c8c8c ，位置应紧跟表头文字，间隔是8px

- packages/custom-antd-styles/src/table.less
refs BRICK_STORE-3251
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): BRICK_STORE-3251 【表格组件】表头筛选图标颜色hover是不需要蓝色

- .github/workflows/ci.yml
- bricks/basic/src/flex-layout/index.spec.ts
- bricks/basic/src/flex-layout/index.tsx
- bricks/demo-basic/package.json
- bricks/demo-basic/src/x-button/index.spec.tsx
- bricks/demo-basic/src/x-button/index.tsx
- bricks/demo-basic/src/y-button/index.spec.ts
- bricks/demo-basic/src/y-button/index.tsx
- bricks/demo-form/package.json
- bricks/demo-widgets/package.json
- bricks/icons/src/general-icon/index.spec.ts
- package.json
- packages/brick-container/jest.config.js
- packages/brick-container/package.json
- packages/brick-http/src/__snapshots__/http.spec.ts.snap
- packages/inject/src/__snapshots__/syntax.spec.ts.snap
- packages/inject/src/compile.spec.ts
- packages/inject/src/lexical.spec.ts
- packages/react-runtime/package.json
- packages/runtime/package.json
- packages/supply/package.json
- packages/test-next/jsconfig.json
- packages/test-next/src/createJestConfig.js
- packages/test-next/src/transforms/file.js
> chore(): refine tests

- bricks/basic/src/bootstrap.ts
- bricks/basic/src/form-item/FormItem.shadow.css
- bricks/basic/src/form-item/FormItemElement.tsx
- bricks/basic/src/form-item/index.tsx
- bricks/basic/src/form/example.html
- bricks/basic/src/form/formStore.ts
- bricks/basic/src/form/index.tsx
- bricks/basic/src/input/index.tsx
- bricks/basic/src/input/input.shadow.css
- bricks/basic/src/interface.ts
- bricks/basic/src/utils/Event.ts
- bricks/basic/src/utils/PubSub.ts
> feat(): support Form Component

- dll/editor-bricks-helper/manifest.snapshot.json
- packages/brick-dll/manifest.snapshot.json
- packages/brick-kit/src/core/StoryboardContext.ts
- packages/brick-utils/src/track.ts
> fix(): 修复formstate中conf设置track:true无法生效,refs:FORM_BUILDER-217

- bricks/basic/package.json
- bricks/basic/src/bootstrap.ts
- bricks/basic/src/drawer/drawer.shadow.css
- bricks/basic/src/drawer/example.html
- bricks/basic/src/drawer/index.tsx
- bricks/basic/src/interface.ts
- bricks/basic/src/modal/index.tsx
> feat(): support Drawer Component

- bricks/demo-basic/src/button-group/index.tsx
- packages/element/src/NextElement.ts
- packages/element/src/createDecorators.ts
- packages/react-element/src/ReactNextElement.spec.tsx
- packages/react-element/src/ReactNextElement.tsx
> feat(): allow non-shadowDOM bricks

- packages/custom-antd-styles/src/button.less
> fix(button): fix hover, focus, and active style of text type

- CONTRIBUTING-V3.md
- bricks/demo-basic/build.config.js
- bricks/demo-basic/src/bootstrap.ts
- bricks/demo-basic/src/native-button/i18n.ts
- bricks/demo-basic/src/native-button/index.ts
- bricks/demo-basic/src/say-hello/i18n.ts
- bricks/demo-basic/src/say-hello/index.tsx
- bricks/demo-basic/src/x-button/index.tsx
- bricks/demo-basic/src/y-button/index.spec.ts
- mock-micro-apps/test/storyboard.yaml
- packages/build-next-bricks/bin/build-next-bricks.js
- packages/i18n/src/init.ts
- packages/i18n/src/react.ts
- packages/runtime/src/internal/compute/getGeneralGlobals.ts
- packages/runtime/src/internal/registerAppI18n.ts
> fix(): refine i18n usage in bricks

- CONTRIBUTING-V3.md
- mock-micro-apps/test/storyboard.yaml
- packages/runtime/src/internal/CustomTemplates/expandCustomTemplate.ts
- packages/runtime/src/internal/Router.ts
- packages/runtime/src/internal/bindListeners.ts
- packages/runtime/src/internal/data/CollectContracts.spec.ts
- packages/runtime/src/internal/data/CollectContracts.ts
- packages/runtime/src/internal/data/FlowApi.spec.ts
- packages/runtime/src/internal/data/FlowApi.ts
- packages/runtime/src/internal/data/FlowApiProvider.ts
- packages/runtime/src/internal/data/getProviderBrick.ts
- packages/runtime/src/internal/data/resolveData.ts
- packages/types/package.json
> feat(): support flow api provider

- bricks/basic/src/bootstrap.ts
- bricks/basic/src/text/example.html
- bricks/basic/src/text/index.tsx
refs BRICK_STORE-3293
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support Text component

- bricks/basic/src/bootstrap.ts
- bricks/basic/src/grid-layout/example.html
- bricks/basic/src/grid-layout/grid-layout.shadow.css
- bricks/basic/src/grid-layout/index.tsx
ref:BRICK_STORE-3287
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support grid-layout component

- bricks/basic/src/grid-layout/grid-layout.shadow.css
- bricks/basic/src/grid-layout/index.tsx
Refs: BRICK_STORE-3287
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): border not effect

- bricks/basic/src/grid-layout/grid-layout.shadow.css
- bricks/basic/src/grid-layout/index.tsx
ref:BRICK_STORE-3287
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): adjust grid-layout style

- packages/build-config-factory/src/generateBrickDocs.js
refs NEXT_BUILDER-2697
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): add editor & editorProps to generated doc

- packages/jest-config-factory/src/next-jest.js
ref: https://github.com/facebook/jest/pull/13395
请勾选以下两组选项其中之一：
或者：
>
>
> fix(next-jest): adaptation for folder restructuring of jest-cli

- bricks/basic/src/bootstrap.ts
- bricks/basic/src/select/example.html
- bricks/basic/src/select/index.shadow.css
- bricks/basic/src/select/index.tsx
> feat(): wipGeneralSelect构件

- v3/styles-v3/package.json
- v3/styles-v3/src/index.less
which overrides default global style
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): ignore antd global.less

- packages/brick-container/deploy/update_postscript.sh
- packages/brick-container/tools/report_installed_brick_next_package.py
brick_next升级脚本修改， 增加反写brick_next到制品仓库的逻辑
Ref NEXT_BUILDER-2741
请勾选以下两组选项其中之一：
或者：
>
>
> feat(report_brick_next): report_brick_next

- bricks/basic/src/bootstrap.ts
- bricks/basic/src/submit-buttons/example.html
- bricks/basic/src/submit-buttons/index.shadow.css
- bricks/basic/src/submit-buttons/index.spec.tsx
- bricks/basic/src/submit-buttons/index.tsx
refs BRICK_STORE-3313
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): BRICK_STORE-3313 【next v3】表单-提交按钮构件

- v3/styles-v3/src/global.less
- v3/styles-v3/webpack.config.js
> feat(): expose v2 global css

- v3/styles-v3/src/global.less
> fix(): fix missing variable in global.css

- packages/brick-container/deploy/package.conf.yaml
更新依赖的micro_app_service版本
请勾选以下两组选项其中之一：
或者：
>
>
> chore(report_brick_next): report_brick_next

- bricks/v2-adapter/build.config.js
- bricks/v2-adapter/package.json
- packages/react-runtime/src/index.ts
- packages/react-runtime/src/useCurrentTheme.ts
- packages/runtime/src/handleHttpError.ts
- packages/runtime/src/themeAndMode.ts
- yarn.lock
> fix(): fix illustrations

- bricks/basic/src/bootstrap.ts
- bricks/basic/src/image/ImageComponent.spec.tsx
- bricks/basic/src/image/ImageComponent.tsx
- bricks/basic/src/image/ImageList.spec.tsx
- bricks/basic/src/image/ImageList.tsx
- bricks/basic/src/image/ImageListContext.ts
- bricks/basic/src/image/Preview.spec.tsx
- bricks/basic/src/image/Preview.tsx
- bricks/basic/src/image/example.html
- bricks/basic/src/image/hooks/useImage.spec.ts
- bricks/basic/src/image/hooks/useImage.ts
- bricks/basic/src/image/hooks/useTransform.spec.ts
- bricks/basic/src/image/hooks/useTransform.ts
- bricks/basic/src/image/imageComponent.shadow.css
- bricks/basic/src/image/index.spec.ts
- bricks/basic/src/image/index.spec.tsx
- bricks/basic/src/image/index.tsx
- bricks/basic/src/image/preview.shadow.css
- bricks/basic/src/image/previewConfig.ts
Closes BRICK_STORE-3294
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support basic.general-image

- bricks/basic/src/image/hooks/useImage.spec.ts
- bricks/basic/src/image/hooks/useTransform.spec.ts
> chore(): import renderHook from '@testing-library/react'

- bricks/basic/src/bootstrap.ts
- bricks/basic/src/button/button.shadow.css
- bricks/basic/src/button/index.spec.ts
- bricks/basic/src/button/index.tsx
- bricks/basic/src/dropdown-button/dropdown-buttons.shadow.css
- bricks/basic/src/dropdown-button/index.spec.ts
- bricks/basic/src/dropdown-button/index.tsx
- bricks/basic/src/interface.ts
> feat(): support dropdown buttons component

- bricks/basic/src/bootstrap.ts
- bricks/basic/src/tag-list/index.spec.ts
- bricks/basic/src/tag-list/index.tsx
- bricks/basic/src/tag/example.html
- bricks/basic/src/tag/index.spec.ts
- bricks/basic/src/tag/index.tsx
- bricks/basic/src/tag/tag.shadow.css
> feat(): support Tag Component

- packages/brick-container/src/styles/variables.css
- packages/brick-kit/src/core/Router.spec.ts
- packages/brick-kit/src/core/Router.ts
close CD-4033
请勾选以下两组选项其中之一：
或者：
>
>
> feat(router): support-ui-8.2-compact-layout background

- packages/brick-container/src/styles/theme/dark.css
- packages/brick-container/src/styles/theme/default.css
- packages/custom-antd-styles/src/input.less
> fix(): 增加新颜色变量及修改input.less

- packages/brick-kit/src/internal/menu.spec.ts
- packages/brick-kit/src/internal/menu.ts
Refs: DESKTOP-305
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix menu update when  dynamic arg

- CONTRIBUTING-V3.md
- bricks/v2-adapter/src/data-providers/legacy-brick-kit/getLegacyUseBrick.ts
- packages/react-runtime/src/ReactUseBrick.tsx
- packages/runtime/src/internal/secretInternals.ts
> fix(): refine useBrick

- cypress/e2e/control-nodes.spec.js
- cypress/e2e/use-brick.spec.js
- package.json
- packages/brick-container/scripts/env.js
- packages/brick-container/scripts/getProxy.js
- packages/brick-container/scripts/middlewares/serveBricksWithVersions.js
- packages/brick-container/scripts/serve.js
- packages/brick-container/scripts/start.js
- packages/runtime/src/internal/menu/fetchMenuById.ts
- packages/serve-helpers/src/tryFiles.js
> fix(): support serving with remote standalone apps

- packages/runtime/src/internal/loadBootstrapData.ts
- packages/runtime/src/internal/menu/computeMenuData.ts
- packages/runtime/src/internal/menu/interfaces.ts
- packages/runtime/src/internal/menu/loadDynamicMenuItems.ts
- packages/runtime/src/internal/menu/mergeMenu.ts
> fix(): fix menu overrideApp

- CONTRIBUTING-V3.md
- bricks/v2-adapter/package.json
- bricks/v2-adapter/src/data-providers/legacy-brick-kit/getLegacyRuntime.ts
- packages/runtime/src/internal/Renderer.ts
- packages/runtime/src/internal/Router.ts
- packages/runtime/src/internal/Runtime.ts
- packages/runtime/src/internal/secretInternals.ts
- yarn.lock
> fix(): support breadcrumb

- CONTRIBUTING-V3.md
- bricks/v2-adapter/src/data-providers/legacy-brick-kit/getLegacyRuntime.ts
- packages/runtime/src/StoryboardFunctionRegistry.ts
- packages/runtime/src/index.ts
- packages/runtime/src/internal/Router.ts
- packages/runtime/src/internal/compute/WidgetI18n.ts
- packages/runtime/src/internal/compute/evaluate.ts
- packages/runtime/src/internal/compute/getGeneralGlobals.ts
- packages/runtime/src/internal/compute/images.spec.ts
- packages/runtime/src/internal/compute/images.ts
> feat(): support widget i18n and images

- bricks/icons/package.json
- bricks/icons/scripts/pre-build.js
- bricks/v2-adapter/package.json
- bricks/v2-adapter/src/data-providers/load-bricks.ts
- packages/loader/src/stableLoadBricks.ts
- yarn.lock
> fix(): using v3 icons for v2 bricks

- bricks/basic/src/text/index.spec.ts
- bricks/basic/src/text/index.tsx
> chore(): add Text jest

- CONTRIBUTING-V3.md
- bricks/icons/package.json
- bricks/icons/scripts/pre-build.js
> fix(): generate all icons by default

- packages/custom-antd-styles/src/alert.less
- packages/custom-antd-styles/src/checkbox/mixin.less
- packages/custom-antd-styles/src/modal.less
- packages/custom-antd-styles/src/notification.less
- packages/custom-antd-styles/src/popover.less
- packages/custom-antd-styles/src/select.less
- packages/custom-antd-styles/src/tooltip.less
> fix(): BRICK_STORE-3314 【8.2升级】部分遗漏组件的圆角调整

- packages/brick-container/src/styles/antd.less
- v3/styles-v3/src/index.less
> fix(): notification圆角调整

- packages/runtime/src/internal/bindListeners.spec.ts
- packages/runtime/src/internal/data/resolveDataStore.spec.ts
> test(): add tests

- bricks/basic/src/grid-layout/index.spec.ts
> test(): grid-layout add test case

- bricks/data-view/src/bootstrap.ts
- bricks/data-view/src/data-view-variables.shadow.css
- bricks/data-view/src/modern-style-component-title/example.html
- bricks/data-view/src/modern-style-component-title/index.spec.ts
- bricks/data-view/src/modern-style-component-title/index.tsx
- bricks/data-view/src/modern-style-component-title/modern-style-component-title.shadow.css
Refs DASHBOARD-231
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support modern-style-component-title

- bricks/basic/src/interface.ts
- bricks/basic/src/select/example.html
- bricks/basic/src/select/index.shadow.css
- bricks/basic/src/select/index.tsx
- bricks/basic/src/tag/index.tsx
- bricks/basic/src/tag/tag.shadow.css
> feat(): select support multiple mode

- packages/runtime/src/internal/Renderer.spec.ts
> test(): add tests for tpl

- cypress/e2e/use-brick.spec.js
- cypress/support/commands.js
> test(): ignore portal orders for useBrick

- bricks/data-view/src/data-view-variables.shadow.css
- bricks/data-view/src/gauge-chart/gauge-chart.shadow.css
- bricks/data-view/src/gauge-chart/index.spec.ts
- bricks/data-view/src/gauge-chart/index.tsx
- bricks/data-view/src/modern-style-component-title/index.tsx
- bricks/data-view/src/modern-style-component-title/modern-style-component-title.shadow.css
refs DASHBOARD-236
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): gauge-chart add other properties

- bricks/data-view/src/bootstrap.ts
- bricks/data-view/src/data-view-variables.shadow.css
- bricks/data-view/src/gauge-chart/index.tsx
- bricks/data-view/src/modern-style-component-title/index.tsx
- bricks/data-view/src/modern-style-component-title/modern-style-component-title.shadow.css
- bricks/data-view/src/modern-style-page-title/example.html
- bricks/data-view/src/modern-style-page-title/index.spec.ts
- bricks/data-view/src/modern-style-page-title/index.tsx
- bricks/data-view/src/modern-style-page-title/modern-style-page-title.shadow.css
Refs DASHBOARD-230
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support modern-style-page-title

- packages/runtime/src/internal/Renderer.spec.ts
- packages/runtime/src/internal/Runtime.spec.ts
- packages/runtime/src/internal/Runtime.ts
- packages/runtime/src/internal/menu/fetchMenuById.spec.ts
- packages/runtime/src/internal/menu/mergeMenu.ts
- packages/runtime/src/internal/secret_internals.spec.ts
> chore(): add tests

- .github/workflows/release-after-merged.yml
> chore(ci): fix release-after-merged

- package.json
- packages/brick-container/serve/env.js
> fix(): specify local micro-apps

- packages/brick-container/serve/getProxy.js
- packages/brick-container/serve/utils/concatBrickPackages.js
> fix(): fix merge local bricks with remote

- packages/easyops-illustrations/package.json
> fix(): include images in npm package

- packages/brick-playground/scripts/start.js
- packages/brick-playground/serve/index.js
- packages/serve-helpers/src/getBrickPackages.js
> fix(): support bricks from local npm

- packages/build-next-bricks/index.d.ts
- packages/build-next-bricks/src/build.js
> feat(): new config options: svgAsAsset, imageAssetFilename

- v3/brick-dll-v3/package.json
- v3/brick-dll-v3/webpack.dll.js
> chore(): do not copy illustrations any more

- packages/loader/src/stableLoadBricks.spec.ts
- packages/loader/src/stableLoadBricks.ts
- packages/runtime/src/internal/data/getProviderBrick.ts
> feat(): load v2-adapter and its dependencies

- packages/brick-container/tools/report_installed_brick_next_package.py
refs NEXT_BUILDER-2890
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): should also report nt packges

- packages/build-next-bricks/index.d.ts
- packages/build-next-bricks/src/build.js
- packages/build-next-bricks/src/getSvgrLoaders.js
- packages/build-next-bricks/src/index.js
> feat(): expose svg rules

- packages/brick-playground/package.json
- packages/brick-playground/src/preview/preview.ts
> fix(): add missing dist-preview

- packages/brick-icons/src/icons/colored-big-screen/app.svg
- packages/brick-icons/src/icons/colored-big-screen/host.svg
- packages/brick-icons/src/icons/colored-big-screen/pod.svg
> chore(): add icons

- packages/custom-antd-styles/src/table.less
> fix(): close MONITOR-5331 refs MONITOR-5331

- packages/react-runtime/src/ReactUseBrick.tsx
- packages/runtime/src/internal/compute/computeRealValue.ts
- packages/runtime/src/internal/secret_internals.spec.ts
- packages/runtime/src/internal/secret_internals.ts
> fix(): expose legacy doTransform

- packages/brick-playground/src/preview/bootstrap.ts
- packages/runtime/src/CustomTemplates.spec.ts
- packages/runtime/src/CustomTemplates.ts
- packages/runtime/src/internal/Renderer.spec.ts
- packages/runtime/src/internal/Renderer.ts
- packages/runtime/src/internal/RendererContext.ts
- packages/runtime/src/internal/compute/evaluate.spec.ts
- packages/runtime/src/internal/compute/evaluate.ts
- packages/runtime/src/internal/data/FlowApi.spec.ts
- packages/runtime/src/internal/data/FlowApi.ts
- packages/runtime/src/internal/data/resolveData.spec.ts
- packages/runtime/src/internal/data/resolveData.ts
- packages/runtime/src/internal/secret_internals.spec.ts
- packages/runtime/src/internal/secret_internals.ts
- packages/runtime/src/isStrictMode.spec.ts
- packages/runtime/src/isStrictMode.ts
- packages/utils/src/storyboard/expressions/collectMemberUsage.ts
- packages/utils/src/storyboard/functions/collectMemberUsageInFunction.spec.ts
- packages/utils/src/storyboard/functions/collectMemberUsageInFunction.ts
> feat(): v3 strict mode

- packages/brick-container/scripts/start.js
- packages/brick-container/src/bootstrap.ts
- packages/runtime/src/index.ts
- packages/runtime/src/internal/Router.ts
- packages/runtime/src/internal/insertPreviewRoutes.spec.ts
- packages/runtime/src/internal/insertPreviewRoutes.ts
- packages/runtime/src/internal/secret_internals.spec.ts
- packages/runtime/src/internal/secret_internals.ts
> feat(): support preview in visual builder

- packages/runtime/src/CustomTemplates.spec.ts
- packages/runtime/src/CustomTemplates.ts
> fix(): only warn about using native props as tpl props in non-strict mode

- packages/runtime/src/internal/Runtime.spec.ts
- packages/runtime/src/internal/Runtime.ts
> fix(): fix feature flags in playground

- packages/brick-container/src/styles/variables.css
> Williamcai/update UI 8.2 compact layout content style

- packages/brick-kit/src/core/Kernel.ts
- packages/brick-kit/src/core/LocationContext.spec.ts
- packages/brick-kit/src/core/LocationContext.ts
Ref BRICK_STORE-3357
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix loading processors in widgets

- packages/test-next/src/createJestConfig.js
> fix(): treat css imports other than css modules as text file

- packages/brick-container/src/styles/theme/dark.css
- packages/brick-container/src/styles/theme/default.css
> fix(): NEXT_BUILDER-2934 二级菜单分类颜色需替换

- etc/runtime.api.md
- packages/runtime/src/Dialog.spec.ts
- packages/runtime/src/Dialog.ts
- packages/runtime/src/handleHttpError.spec.ts
- packages/runtime/src/handleHttpError.ts
- packages/runtime/src/internal/i18n.ts
> fix(): refine dialog service

- packages/runtime/src/internal/Runtime.ts
- packages/runtime/src/internal/matchStoryboard.ts
> fix(): fix isOutsideApp

- packages/react-element/src/wrapBrick.spec.tsx
- packages/react-element/src/wrapBrick.tsx
> feat(wrapLocalBrick): allow pass brick name

- packages/brick-container/build.config.js
- packages/brick-playground/build.config.js
> fix(): make cache groups compatible in EasyOps CI

- packages/brick-playground/src/preview/bootstrap.ts
- packages/brick-playground/src/preview/preview.css
- packages/brick-playground/src/preview/preview.ejs
> fix(): reset preview body height to initial

- packages/brick-kit/src/core/CustomTemplates/__snapshots__/expandCustomTemplate.spec.ts.snap
- packages/brick-kit/src/core/CustomTemplates/expandCustomTemplate.ts
- packages/brick-kit/src/core/CustomTemplates/setupUseBrickInTemplate.spec.ts
- packages/brick-kit/src/core/CustomTemplates/setupUseBrickInTemplate.ts
- packages/brick-kit/src/internal/setProperties.spec.ts
- packages/brick-kit/src/internal/setProperties.ts
> fix(): fix multi-instance of useBrick state conflict

- packages/brick-playground/src/declarations.d.ts
- packages/brick-playground/src/preview/bootstrap.ts
> feat(preview): allow adding style

- CONTRIBUTING-V3.md
- etc/runtime.api.md
- packages/brick-container/package.json
- packages/brick-container/src/bootstrap.ts
- packages/brick-container/src/loadBootstrapData.spec.ts
- packages/brick-container/src/loadBootstrapData.ts
- packages/brick-container/src/loadCheckLogin.ts
- packages/brick-playground/src/preview/bootstrap.ts
- packages/runtime/src/Dialog.spec.ts
- packages/runtime/src/Dialog.ts
- packages/runtime/src/Notification.spec.ts
- packages/runtime/src/Notification.ts
- packages/runtime/src/index.ts
- packages/runtime/src/internal/Router.ts
- packages/runtime/src/internal/Runtime.spec.ts
- packages/runtime/src/internal/Runtime.ts
- packages/runtime/src/internal/bootstrapData.ts
- packages/runtime/src/internal/fulfilStoryboard.ts
- packages/runtime/src/internal/menu/fetchMenuById.spec.ts
- packages/runtime/src/internal/secret_internals.spec.ts
- packages/runtime/src/internal/secret_internals.ts
- packages/types/src/manifest.ts
> refactor(): move bootstrap fetching outside of runtime

- packages/brick-container/src/bootstrap.ts
- packages/runtime/src/internal/Runtime.spec.ts
- packages/runtime/src/internal/Runtime.ts
> fix(): allow bootstrap with initializing data

- packages/brick-kit/src/internal/setProperties.spec.ts
- packages/brick-kit/src/internal/setProperties.ts
> fix(): fix set props of useBrick

- .size-limit.js
- packages/brick-dll/webpack.dll.js
- packages/brick-kit/package.json
- packages/brick-kit/src/core/Kernel.spec.ts
- packages/brick-kit/src/core/Kernel.ts
- packages/brick-utils/src/getDllAndDepsOfStoryboard.spec.ts
- packages/brick-utils/src/getDllAndDepsOfStoryboard.ts
- yarn.lock
> feat(): support using v3 bricks in v2 container

- packages/runtime/src/internal/compute/computeRealProperties.ts
Ref NEXT_BUILDER-3169
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): allow undefined prop value

- packages/brick-scripts/template/bricks-pkg/deploy-default/package.conf.yaml
- packages/build-config-factory/src/generateDeps.js
- packages/build-config-factory/src/post-build.js
> fix(): allow v2 bricks to be used in v3 container

- packages/dev-dependencies/extract.js
> fix(): fix extract when renovate is enabled in root

- packages/brick-kit/src/core/CustomTemplates/setupUseBrickInTemplate.ts
- packages/brick-kit/src/internal/setProperties.spec.ts
> fix(): ignore non-plain object in props when setup useBrick

- packages/cook/src/preevaluate.spec.ts
- packages/cook/src/preevaluate.ts
- packages/runtime/src/internal/compute/getTracks.spec.ts
- packages/runtime/src/internal/compute/getTracks.ts
- packages/utils/src/storyboard/expressions/beforeVisitGlobalMember.ts
- packages/utils/src/storyboard/expressions/track.spec.ts
- packages/utils/src/storyboard/expressions/track.ts
> feat(): support track evalute syntax sugar

- packages/runtime/src/createRoot.ts
> fix(createRoot): add missing form state store

- packages/runtime/src/internal/bindListeners.spec.ts
- packages/runtime/src/internal/bindListeners.ts
- packages/types/src/manifest.ts
> feat(): support if/esle syntax

- packages/brick-dll/manifest.snapshot.json
- v3/brick-dll-v3/manifest.snapshot.json
- yarn.lock
> fix(): update rc-util

- etc/brick-kit.api.md
- etc/brick-types.api.md
- packages/brick-kit/src/checkIf.ts
- packages/brick-kit/src/internal/bindListeners.spec.ts
- packages/brick-kit/src/internal/bindListeners.ts
- packages/brick-types/src/manifest.ts
> feat(): support if/esle syntax in v2

- etc/brick-kit.api.md
- packages/brick-kit/src/core/BrickNode.spec.ts
- packages/brick-kit/src/core/BrickNode.ts
- packages/brick-kit/src/core/Runtime.ts
- packages/brick-kit/src/developHelper.ts
Refs NEXT_BUILDER-3160
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support preview context/state value

- etc/brick-kit.api.md
- packages/brick-kit/src/core/Runtime.ts
- packages/brick-kit/src/core/interfaces.ts
- packages/brick-kit/src/developHelper.ts
Refs NEXT_BUILDER-3189
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): refactor preview value

- packages/brick-container/serve/utils/sizeCheck.js
> fix(): refine size-check

- etc/runtime.api.md
- packages/runtime/src/internal/bindListeners.spec.ts
- packages/runtime/src/internal/bindListeners.ts
- packages/runtime/src/internal/data/DataStore.spec.ts
- packages/runtime/src/internal/data/DataStore.ts
- packages/types/src/manifest.ts
> feat(): support context batchUpdate

- packages/cook/src/cook.spec.ts
- packages/cook/src/sanitize.ts
- packages/supply/src/index.ts
> feat(): function support RegExp

- packages/cook/src/cook.spec.ts
- packages/cook/src/sanitize.ts
- packages/supply/src/index.ts
> feat(): function support RegExp in v3

- packages/cook/src/preevaluate.spec.ts
- packages/cook/src/preevaluate.ts
> fix(): fix trackAll Reg

- packages/cook/src/preevaluate.spec.ts
- packages/cook/src/preevaluate.ts
> fix(): fix track all reg

- packages/build-next-bricks/src/build.js
- packages/easyops-runtime/src/auth.spec.ts
- packages/easyops-runtime/src/auth.ts
- packages/easyops-runtime/src/index.ts
> feat(): support auth methods

- packages/preview/src/bootstrap.ts
> fix(): in html mode, scan all descendant bricks

- packages/brick-container/scripts/start.js
- packages/brick-container/serve/env.js
- packages/brick-container/serve/getProxy.js
- packages/brick-container/serve/index.js
- packages/brick-container/serve/middlewares/bootstrapJson.js
- packages/brick-container/serve/middlewares/standaloneBootstrapJson.js
- packages/serve-helpers/index.d.ts
- packages/serve-helpers/src/getBrickPackages.js
> fix(serve): support --local-bricks

- packages/monaco-contributions/package.json
- yarn.lock
> fix(): fix monaco version not matching

- etc/brick-types.api.md
- packages/brick-kit/package.json
- packages/brick-kit/src/internal/menu.spec.ts
- packages/brick-kit/src/internal/menu.ts
- packages/brick-types/src/menu.ts
- yarn.lock
Refs DESIGNER_ROUTINE-651
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): menu支持大于两层

- packages/runtime/src/internal/Router.ts
- packages/runtime/src/internal/Runtime.ts
- packages/runtime/src/internal/compute/evaluate.spec.ts
> feat(): sys add settings field&export brand, misc

- etc/brick-types.api.md
- packages/brick-kit/package.json
- packages/brick-kit/src/core/Kernel.spec.ts
- packages/brick-kit/src/core/Kernel.ts
- packages/brick-kit/src/internal/menu.spec.ts
- packages/brick-kit/src/internal/menu.ts
- packages/brick-types/src/menu.ts
- packages/brick-utils/src/builder/normalizeMenu.ts
- yarn.lock
Refs DESIGNER_ROUTINE-651
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): menu支持大于两层(standalone)

- packages/brick-playground/build.config.js
- packages/brick-playground/src/index.ts
- packages/monaco-contributions/html.d.ts
- packages/monaco-contributions/html.js
- packages/monaco-contributions/package.json
> feat(): support extended html syntax: allow dots in tag name

- packages/brick-kit/src/internal/menu.spec.ts
- packages/brick-kit/src/internal/menu.ts
Refs DESIGNER_ROUTINE-648
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): menu新接口结构体字段会默认填充所有结构体ID导致空判断出错

- .size-limit.js
- packages/brick-utils/src/builder/normalizeMenu.spec.ts
- packages/brick-utils/src/builder/normalizeMenu.ts
Refs DESIGNER_ROUTINE-648
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): normalizeMenu兼容新接口

- packages/brick-icons/src/icons/second-menu/cmdb-data-operations.svg
> fix(): add icon Closes INSTANCE-4965

- packages/brick-playground/serve/getExamples.js
> fix(): extract examples from docs in markdown

- packages/custom-antd-styles/src/table.less
- packages/custom-antd-styles/src/timeline.less
> fix(): 修改table及timeline样式

- packages/build-next-bricks/bin/build-next-bricks.js
> feat(): support build manifest only

- packages/brick-icons/src/icons/third-menu/product-objective-third-menu.svg
- packages/custom-antd-styles/src/table.less
> fix(table): 修改table间距

- packages/build-next-bricks/src/scanBricks.js
> fix(): ignore missing imports

- packages/build-next-bricks/index.d.ts
- packages/build-next-bricks/src/build.js
> fix(): fix svg rules

- packages/brick-container/src/styles/theme/dark.css
- packages/brick-container/src/styles/theme/default.css
- packages/custom-antd-styles/src/pagination.less
> chore(): BRICK_STORE-3383 ref BRICK_STORE-3383

- etc/brick-types.api.md
- packages/brick-kit/src/core/Kernel.spec.ts
- packages/brick-kit/src/core/Kernel.ts
- packages/brick-types/src/manifest.ts
Closes NEXT_BUILDER-3297
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): standalone模式下小产品图标url错误

- etc/brick-kit.api.md
- etc/brick-types.api.md
- packages/brick-kit/src/core/Kernel.spec.ts
- packages/brick-kit/src/core/Kernel.ts
- packages/brick-kit/src/core/Runtime.ts
- packages/brick-types/src/builder.ts
- packages/brick-utils/src/snippetEvaluate.ts
Refs NEXT_BUILDER-3360
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support dynamic snippet preview

- packages/brick-kit/src/core/Runtime.ts
Refs NEXT_BUILDER-3360
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): settings as optionals

- packages/brick-kit/src/core/Runtime.ts
Refs NEXT_BUILDER-3360
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): settings as optional params

- .size-limit.js
- etc/brick-types.api.md
- packages/brick-types/src/manifest.ts
> fix(): fix types that causing schema json too large

- .eslintrc
- packages/yo/bin/yo.js
- packages/yo/jsconfig.json
- packages/yo/package.json
- packages/yo/src/index.js
- packages/yo/src/plopfile.js
- packages/yo/src/templates/brick.md.hbs
- packages/yo/src/templates/brick/i18n.ts
- packages/yo/src/templates/brick/index.spec.tsx.hbs
- packages/yo/src/templates/brick/index.tsx.hbs
- packages/yo/src/templates/brick/styles.shadow.css
- packages/yo/src/templates/bricks/build.config.js
- packages/yo/src/templates/bricks/package.json.hbs
- packages/yo/src/templates/bricks/src/index.ts
- packages/yo/src/templates/bricks/tsconfig.json
- packages/yo/src/templates/provider/provider.spec.ts.hbs
- packages/yo/src/templates/provider/provider.ts.hbs
- yarn.lock
> feat(): yo: help to create bricks

- packages/brick-container/src/bootstrap.ts
- packages/brick-container/src/utils.spec.ts
- packages/brick-container/src/utils.ts
Ref: BRICK_STORE-3391
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): brick_next在发起http请求给后端的时候，自动按策略生成trace_id

- packages/yo/package.json
- packages/yo/src/plopfile.js
- packages/yo/src/templates/shared/package.json.hbs
- packages/yo/src/templates/shared/tsconfig.build.json
- packages/yo/src/templates/shared/tsconfig.json
> feat(): create new shared libraries

- packages/brick-kit/src/core/Kernel.spec.ts
- packages/brick-kit/src/core/Kernel.ts
> fix(): unset  `FLAGS["migrate-to-brick-next-v3"]`

- packages/doc-helpers/src/yamlToHtml.js
> fix(): fix transformation of slots to children

- etc/brick-kit.api.md
- etc/brick-types.api.md
- packages/brick-kit/src/core/CustomTemplates/CustomTemplateContext.ts
- packages/brick-kit/src/core/LocationContext.ts
- packages/brick-kit/src/core/StoryboardContext.spec.ts
- packages/brick-kit/src/core/StoryboardContext.ts
- packages/brick-types/src/manifest.ts
> context支持Trigger挂载生命周期自动触发 

- packages/brick-utils/src/snippetEvaluate.spec.ts
- packages/brick-utils/src/snippetEvaluate.ts
- packages/cook/src/preevaluate.ts
Refs NEXT_BUILDER-3307
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): support more variable

- etc/runtime.api.md
- packages/brick-container/serve/getProxy.js
- packages/brick-container/src/bootstrap.ts
- packages/easyops-runtime/package.json
- packages/easyops-runtime/src/index.ts
- packages/easyops-runtime/src/websocket/MessageDispatcher.spec.ts
- packages/easyops-runtime/src/websocket/MessageDispatcher.ts
- packages/easyops-runtime/src/websocket/MessageService.spec.ts
- packages/easyops-runtime/src/websocket/MessageService.ts
- packages/runtime/src/createRoot.ts
- packages/runtime/src/internal/Renderer.spec.ts
- packages/runtime/src/internal/RendererContext.ts
- packages/runtime/src/internal/Router.ts
- packages/runtime/src/internal/Runtime.ts
- packages/runtime/src/internal/bindListeners.spec.ts
- packages/runtime/src/internal/bindListeners.ts
- packages/runtime/src/internal/data/DataStore.ts
- packages/runtime/src/internal/secret_internals.ts
> feat(): websocket message dispatcher

- CONTRIBUTING-V3.md
- packages/doc-helpers/src/yamlToHtml.js
> fix(yaml-to-html): transform useProvider

- etc/runtime.api.md
- packages/runtime/src/createRoot.ts
- packages/runtime/src/internal/Router.ts
- packages/runtime/src/internal/bindListeners.spec.ts
- packages/runtime/src/internal/data/DataStore.spec.ts
- packages/runtime/src/internal/data/DataStore.ts
- packages/runtime/src/internal/secret_internals.ts
- packages/types/src/manifest.ts
> feat(): support context.resolve.async

- packages/brick-kit/src/internal/menu.spec.ts
- packages/brick-kit/src/internal/menu.ts
Closes NEXT_BUILDER-3364
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): menu to 支持解析 YAML 格式的字符串

- packages/build-next-bricks/bin/build-next-bricks.js
- packages/build-next-bricks/src/EmitBricksJsonPlugin.js
- packages/build-next-bricks/src/build.js
- packages/build-next-bricks/src/makeBrickManifest.js
- packages/build-next-bricks/src/scanBricks.js
- packages/build-next-bricks/src/utils.js
> feat(): build brick supports analysis typescript

- packages/runtime/src/CustomTemplates.spec.ts
- packages/runtime/src/internal/CustomTemplates/constants.ts
- packages/runtime/src/internal/CustomTemplates/setupTemplateProxy.ts
- packages/runtime/src/internal/Renderer.spec.ts
- packages/runtime/src/internal/Renderer.ts
- packages/runtime/src/internal/compute/computeRealProperties.spec.ts
- packages/runtime/src/internal/compute/computeRealProperties.ts
- packages/runtime/src/internal/data/DataStore.spec.ts
- packages/runtime/src/internal/data/DataStore.ts
- packages/runtime/src/internal/interfaces.ts
> fix(): states will wait for specific host props only

- packages/brick-kit/src/internal/menu.spec.ts
- packages/brick-kit/src/internal/menu.ts
Closes NEXT_BUILDER-3445
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): menu to 解析时兼容表达式

- etc/runtime.api.md
- packages/brick-manifest/index.d.ts
- packages/build-next-bricks/src/build.js
- packages/build-next-bricks/src/makeBrickManifest.js
- packages/build-next-bricks/src/scanBricks.js
- packages/doc-helpers/src/getExamples.js
- packages/runtime/src/internal/Runtime.ts
> feat(): provider manifest

- packages/brick-manifest/index.d.ts
- packages/build-next-bricks/src/makeBrickManifest.js
- packages/build-next-bricks/src/scanBricks.js
> feat(): support brick manifest fields create type

- dll/editor-bricks-helper/manifest.snapshot.json
- packages/editor-bricks-helper/src/index.ts
> feat(): export getUniqueNodeId

- CONTRIBUTING-V3.md
- packages/brick-container/build.config.js
- packages/brick-container/src/index.ts
- packages/runtime/src/internal/Runtime.ts
- packages/runtime/src/internal/compute/evaluate.ts
- packages/runtime/src/internal/devtools.spec.ts
- packages/runtime/src/internal/devtools.ts
> fix(): compatible with devtools

- packages/brick-manifest/annotation.d.ts
- packages/build-next-bricks/src/getTypeDeclaration.js
- packages/build-next-bricks/src/makeBrickManifest.js
> fix(): infer type annotation from the default value

- packages/preview/src/bootstrap.ts
> fix(): styles are in head instead of body

- packages/runtime/src/createRoot.ts
- packages/runtime/src/internal/Router.ts
> fix(): set theme before rendering

- bricks/e2e/src/list-by-use-brick/index.tsx
- mock-micro-apps/e2e/storyboard.yaml
- packages/brick-manifest/index.d.ts
- packages/build-next-bricks/src/makeBrickManifest.js
- packages/build-next-bricks/src/scanBricks.js
- packages/element/src/NextElement.spec.ts
- packages/element/src/createDecorators.ts
- packages/yo/src/plopfile.js
- packages/yo/src/templates/brick.md.hbs
- packages/yo/src/templates/brick/i18n.ts
- packages/yo/src/templates/brick/index.spec.tsx.hbs
- packages/yo/src/templates/brick/index.tsx.hbs
> feat(): support brick alias

- bricks/e2e/package.json
- packages/build-next-bricks/src/build.js
- packages/yo/src/plopfile.js
- shared/common-bricks/common-bricks.json
> feat(): check common bricks

- packages/custom-antd-styles/src/table.less
Closes DESIGNER_ROUTINE-667
请勾选以下两组选项其中之一：
或者：
>
>
> fix(custom-antd-styles): antd表格没数据时不能hover

- packages/brick-kit/src/internal/menu.spec.ts
- packages/brick-kit/src/internal/menu.ts
Closes BRICK-26
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 多层菜单排序失效

- packages/runtime/src/history.spec.ts
- packages/runtime/src/history.ts
> fix(): history fallback to from v2 runtime

- declarations/global.d.ts
- packages/build-next-bricks/index.d.ts
- packages/build-next-bricks/src/build.js
- packages/build-next-bricks/src/getSvgrLoaders.js
- packages/test-next/src/createJestConfig.js
> fix(): refine svgr options for icon font

- packages/brick-container/src/styles/antd.less
- packages/custom-antd-styles/src/card.less
- packages/custom-antd-styles/src/drawer.less
- v3/styles-v3/src/index.less
Refs DESIGNER_ROUTINE-669
请勾选以下两组选项其中之一：
或者：
>
>
> feat(custom-antd-styles): 卡片、抽屉左右内间距调整

- packages/brick-container/src/styles/theme/default.css
Refs DESIGNER_ROUTINE-672
请勾选以下两组选项其中之一：
或者：
>
>
> fix(bricks-container): v8-top-menu-item-hover调整

- packages/brick-container/src/polyfill.ts
- packages/brick-container/src/replaceChildren.spec.ts
- packages/brick-container/src/replaceChildren.ts
> fix(): polyfill for Element::replaceChildren

- packages/build-next-bricks/src/isDeprecatedV2Packages.js
- packages/build-next-bricks/src/scanBricks.js
> fix(): throw error if find importing deprecated v2 packages

- packages/runtime/src/internal/bindListeners.ts
> fix(): batch update error in template

- packages/brick-container/build.config.js
- packages/brick-container/package.json
- packages/brick-container/src/bootstrap.ts
- packages/brick-container/src/preview/capture.ts
- packages/brick-container/src/preview/connect.spec.ts
- packages/brick-container/src/preview/connect.ts
- packages/brick-container/src/preview/initialize.spec.ts
- packages/brick-container/src/preview/initialize.ts
- packages/brick-container/src/preview/inspector.ts
- packages/brick-container/src/preview/interfaces.ts
- packages/brick-container/src/preview/resizeScreenshot.spec.ts
- packages/brick-container/src/preview/resizeScreenshot.ts
- yarn.lock
> fix(): put preview helpers in brick-container

- packages/brick-kit/src/internal/menu.spec.ts
- packages/brick-kit/src/internal/menu.ts
> fix(): load processors before compute menu data

- packages/react-runtime/src/ReactUseBrick.tsx
- packages/react-runtime/tsconfig.json
> fix(): make v3 bricks compatible with Brick Next v2

- packages/react-runtime/src/ReactUseBrick.tsx
> fix(): check useBrick factories existence

- packages/custom-antd-styles/src/table.less
> fix(): 表格样式错误 ref CD-5314

- packages/runtime/src/internal/Renderer.ts
- packages/runtime/src/internal/data/resolveData.spec.ts
- packages/runtime/src/internal/data/resolveData.ts
> fix(): compatible with resolve.field

- packages/runtime/src/internal/Runtime.spec.ts
- packages/runtime/src/internal/Runtime.ts
Closes NEXT_BUILDER-3688
请勾选以下两组选项其中之一：
或者：
>
>
> feat():  runtime export hasInstalledApp

- packages/brick-kit/src/core/Router.spec.ts
- packages/brick-kit/src/core/Router.ts
- packages/brick-kit/src/core/standaloneBootstrap.ts
> fix(): 添加nologin模式下需要跳转到指定登陆页逻辑 refs EASYCORE-1463

- etc/runtime.api.md
- packages/brick-container/src/preview/connect.spec.ts
- packages/brick-container/src/preview/connect.ts
- packages/brick-container/src/preview/interfaces.ts
- packages/runtime/src/createRoot.spec.ts
- packages/runtime/src/internal/Renderer.spec.ts
- packages/runtime/src/internal/Runtime.spec.ts
- packages/runtime/src/internal/data/DataStore.spec.ts
- packages/runtime/src/internal/data/DataStore.ts
- packages/runtime/src/internal/interfaces.ts
- packages/runtime/src/internal/mount.ts
- packages/runtime/src/internal/secret_internals.spec.ts
- packages/runtime/src/internal/secret_internals.ts
> feat(): support inspect-data-value in v3

- packages/loader/src/loadScript.spec.ts
- packages/loader/src/loadScript.ts
> fix(): fix load script with full URL

- packages/brick-container/src/preview/listen.spec.ts
- packages/brick-container/src/preview/listen.ts
> fix(): add flags to enable preview agent

- packages/brick-container/serve/getProxy.js
- packages/brick-container/serve/utils/getStoryboards.js
> fix(): support serve with v2 server

- packages/brick-utils/src/builder/normalizeBuilderNode.spec.ts
- packages/brick-utils/src/builder/normalizeBuilderNode.ts
- packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
- packages/editor-bricks-helper/src/internal/getBuilderNode.spec.ts
> fix(): keep brick alias

- packages/brick-container/src/polyfill.ts
- packages/brick-container/src/replaceChildren.spec.ts
- packages/brick-container/src/replaceChildren.ts
> fix(): polyfill for replaceChildren

- packages/runtime/src/internal/compute/evaluate.spec.ts
- packages/runtime/src/internal/compute/evaluate.ts
> fix(): fix processors with devtools

- .gitignore
- CONTRIBUTING.md
- packages/brick-container/package.json
- packages/brick-container/serve/env.js
- packages/brick-container/serve/getProxy.js
- packages/brick-container/serve/middlewares/bootstrapJson.js
- packages/brick-container/serve/middlewares/getMiddlewares.js
- packages/brick-container/serve/middlewares/serveBricksWithVersions.js
- packages/brick-container/serve/middlewares/standaloneBootstrapJson.js
- packages/brick-container/serve/utils/getLocalBrickFolders.js
- packages/serve-helpers/index.d.ts
- packages/serve-helpers/src/getBrickPackages.js
- yarn.lock
> fix(): allow serve with local brick folders

- packages/brick-container/package.json
- packages/brick-container/serve/env.js
- yarn.lock
> fix(): use a previous version of glob to avoid issues of yarn with package name alias

- etc/runtime.api.md
- packages/react-runtime/src/ReactUseBrick.spec.tsx
- packages/react-runtime/src/ReactUseBrick.tsx
- packages/runtime/src/internal/secret_internals.spec.ts
- packages/runtime/src/internal/secret_internals.ts
> fix(): ignore fails of useBrick rendering when render id changed

- packages/brick-container/serve/env.js
- packages/brick-container/serve/getProxy.js
- packages/runtime/src/CustomTemplates.spec.ts
- packages/runtime/src/internal/CustomTemplates/constants.ts
- packages/runtime/src/internal/CustomTemplates/expandCustomTemplate.ts
- packages/runtime/src/internal/CustomTemplates/setupTemplateProxy.ts
- packages/runtime/src/internal/FormRenderer/expandFormRenderer.ts
- packages/runtime/src/internal/Renderer.ts
- packages/runtime/src/internal/compute/computeRealProperties.spec.ts
- packages/runtime/src/internal/compute/computeRealProperties.ts
- packages/runtime/src/internal/data/DataStore.spec.ts
- packages/runtime/src/internal/data/DataStore.ts
- packages/runtime/src/internal/interfaces.ts
> fix(): fix nested templates with proxy props

- etc/runtime.api.md
- packages/runtime/src/internal/interfaces.ts
- packages/runtime/src/internal/secret_internals.spec.ts
- packages/runtime/src/internal/secret_internals.ts
- packages/types/src/manifest.ts
Refs NEXT_BUILDER-3752
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): v3 support auto build & push in preivew

- packages/runtime/src/internal/CustomTemplates/setupUseBrickInTemplate.spec.ts
- packages/runtime/src/internal/CustomTemplates/setupUseBrickInTemplate.ts
- packages/runtime/src/internal/compute/computeRealValue.spec.ts
- packages/runtime/src/internal/compute/computeRealValue.ts
> fix(): bypass functions when compute expressions

- packages/brick-playground/serve/bootstrapJson.js
> fix(): yarn serve:playground run failed

- packages/brick-container/package.json
- packages/brick-container/serve/env.js
- packages/brick-container/serve/index.js
- packages/brick-container/serve/utils/getStoryboards.js
- packages/brick-container/serve/utils/injectIndexHtml.js
> fix(): support live reload (currently only for local micro-apps)

- packages/brick-container/scripts/start.js
- packages/brick-container/serve/env.js
- packages/brick-container/serve/index.js
- packages/brick-container/serve/middlewares/getMiddlewares.js
- packages/serve-helpers/src/getBrickPackages.js
> fix(): allow set local mocks

- packages/serve-helpers/src/getBrickPackages.js
> fix(): compatible with no filePath in bricks.json

- packages/runtime/src/internal/Renderer.spec.ts
- packages/runtime/src/internal/Renderer.ts
- packages/runtime/src/internal/Router.ts
> fix(): load processors before mount

- etc/brick-types.api.md
- packages/brick-kit/src/core/Kernel.spec.ts
- packages/brick-kit/src/core/Kernel.ts
- packages/brick-types/src/builder.ts
Closes NEXT_BUILDER-3782
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): theme-template snippet use context instead of data 

- etc/runtime.api.md
- packages/runtime/src/internal/secret_internals.spec.ts
- packages/runtime/src/internal/secret_internals.ts
Closes NEXT_BUILDER-3782
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): v3 - theme-template snippet use context instead of data

- packages/react-runtime/src/index.ts
- packages/react-runtime/src/useRouteRender.spec.ts
- packages/react-runtime/src/useRouteRender.ts
- packages/runtime/src/internal/Router.ts
Closes NEXT_BUILDER-3908
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support app bar tips in v3

- packages/brick-kit/src/internal/bindListeners.ts
> fix(): do not mutate event args

- .github/workflows/ci.yml
- packages/yo/src/templates/shared/package.json.hbs
> fix(): fix exports for shared libs

- packages/brick-container/tools/report_installed_brick_next_package.py
refs NEXT_BUILDER-3724
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 上报脚本支持v3构件

- packages/build-next-bricks/src/build.js
> fix(): enable css nesting rules

- .github/workflows/ci.yml
- packages/build-next-bricks/src/build.js
> fix(module-federation): mark @babel/parser as shared

- packages/brick-container/tools/report_installed_brick_next_package.py
fixes NEXT_BUILDER-3724
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 未上报slots

- cypress/e2e/control-nodes.spec.js
- mock-micro-apps/e2e/storyboard.yaml
- packages/runtime/src/internal/Renderer.spec.ts
- packages/runtime/src/internal/Renderer.ts
> feat(): support lifeCycle.onMount/onUnmount for control nodes

- packages/runtime/src/internal/Renderer.spec.ts
- packages/runtime/src/internal/Renderer.ts
> fix(): dispatch onUnmount for control nodes when root unmount

- packages/runtime/src/internal/Router.ts
- packages/runtime/src/internal/Runtime.spec.ts
> fix(): 增加自定义登陆页跳转逻辑 refs EASYCORE-1757

- packages/build-next-bricks/bin/build-next-bricks.js
- packages/build-next-bricks/src/EmitBricksJsonPlugin.js
- packages/build-next-bricks/src/build.js
- packages/build-next-bricks/src/getDocs.js
- packages/build-next-bricks/src/scanBricks.js
Closes NEXT_BUILDER-3977
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): build brick generate examples.json

- declarations/global.d.ts
- packages/brick-container/build.config.js
- packages/brick-container/package.json
- packages/preview/src/bootstrap.ts
- packages/preview/src/index.ts
Closes NEXT_BUILDER-4006
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support preview in brick-container

- packages/brick-utils/src/removeDeadConditions.spec.ts
- packages/brick-utils/src/removeDeadConditions.ts
> fix(): handle dead conditions with then/else

- packages/brick-container/tools/report_installed_brick_next_package.py
Closes NEXT_BUILDER-3964
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): bricks上报脚本调整, 增加v3构件的示例conf和接口interface

- etc/brick-types.api.md
- packages/brick-types/src/story.ts
> chore(): update story interface

- etc/runtime.api.md
- packages/easyops-runtime/src/menu/fetchMenuById.ts
- packages/runtime/src/internal/CustomTemplates/constants.ts
- packages/runtime/src/internal/CustomTemplates/expandCustomTemplate.ts
- packages/runtime/src/internal/CustomTemplates/setupTemplateProxy.ts
- packages/runtime/src/internal/FormRenderer/expandFormRenderer.ts
- packages/runtime/src/internal/Renderer.spec.ts
- packages/runtime/src/internal/Renderer.ts
- packages/runtime/src/internal/compute/evaluate.spec.ts
- packages/runtime/src/internal/compute/evaluate.ts
- packages/runtime/src/internal/interfaces.ts
> feat(): support INDEX in :forEach

- packages/brick-container/build.config.js
- packages/brick-container/src/index.ts
> fix(): support mock date in v3

- packages/brick-container/build.config.js
> fix(): refine preview bootstrap url

- cypress/e2e/control-nodes.spec.js
- mock-micro-apps/e2e/storyboard.yaml
- packages/runtime/src/internal/Renderer.spec.ts
- packages/runtime/src/internal/Renderer.ts
- packages/runtime/src/internal/RendererContext.ts
- packages/runtime/src/internal/enums.ts
- packages/runtime/src/internal/interfaces.ts
- packages/runtime/src/internal/mount.ts
- packages/runtime/src/internal/secret_internals.spec.ts
- packages/runtime/src/internal/secret_internals.ts
> fix(): fix rerender of control nodes with empty initial

- etc/runtime.api.md
- packages/brick-container/serve/getProxy.js
- packages/brick-container/src/bootstrap.ts
- packages/easyops-runtime/package.json
- packages/easyops-runtime/src/analytics/analytics.spec.ts
- packages/easyops-runtime/src/analytics/analytics.ts
- packages/easyops-runtime/src/analytics/http.spec.ts
- packages/easyops-runtime/src/analytics/http.ts
- packages/easyops-runtime/src/analytics/index.ts
- packages/easyops-runtime/src/analytics/interfaces.ts
- packages/easyops-runtime/src/analytics/pageView.spec.ts
- packages/easyops-runtime/src/analytics/pageView.ts
- packages/easyops-runtime/src/index.ts
- packages/easyops-runtime/src/menu/fetchMenuById.spec.ts
- packages/http/jest.config.js
- packages/http/src/http.ts
- packages/runtime/src/index.ts
- packages/runtime/src/internal/Renderer.spec.ts
- packages/runtime/src/internal/Renderer.ts
- packages/runtime/src/internal/Router.ts
- packages/runtime/src/internal/Runtime.spec.ts
- packages/runtime/src/internal/Runtime.ts
> fix(): support api and page-view analytics

- etc/runtime.api.md
- packages/runtime/src/internal/interfaces.ts
- packages/runtime/src/internal/secret_internals.spec.ts
- packages/runtime/src/internal/secret_internals.ts
> fix(): receive collectUsedContracts as a function

- etc/brick-types.api.md
- packages/brick-kit/src/internal/menu.ts
- packages/brick-types/src/menu.ts
> fix(): support menu field

- packages/build-next-bricks/src/makeBrickManifest.js
> fix(): allow mark internal props

- CONTRIBUTING.md
- packages/brick-container/index.d.ts
- packages/brick-container/package.json
- packages/brick-container/serve/env.js
- packages/brick-container/serve/getProxy.js
- packages/brick-container/serve/middlewares/getMiddlewares.js
> fix(): support override user config by apps

- packages/brick-container/src/bootstrap.ts
- packages/brick-container/src/loadBootstrapData.spec.ts
- packages/brick-container/src/loadBootstrapData.ts
- packages/brick-container/src/mocks.spec.ts
- packages/brick-container/src/mocks.ts
> fix(): support API mocks

- packages/brick-kit/src/internal/menu.ts
> fix(): make menu compatible with `items/children` and `text/title`

- cypress/e2e/size-check.spec.js
- mock-micro-apps/e2e/storyboard.yaml
> chore(ci): check size in e2e test

- packages/http/src/exports.ts
- packages/http/src/http.ts
- packages/http/src/index.ts
- packages/http/tsconfig.json
> fix(): use v2 http module for v3 bricks in v2 container

- packages/loader/src/stableLoadBricks.spec.ts
- packages/loader/src/stableLoadBricks.ts
> fix(): handle error when loading brick with no namespace

- packages/yo/src/templates/brick/i18n.ts
> fix(): refine i18n locale types

- packages/brick-container/serve/getProxies.js
which put its bootstrap.json in `/next/:appId/-/bootstrap.*.json`
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): compatible with legacy standalone app

- etc/runtime.api.md
- packages/easyops-runtime/src/auth-v2.ts
- packages/easyops-runtime/src/index.ts
- packages/react-runtime/src/ReactUseBrick.spec.tsx
- packages/react-runtime/src/ReactUseBrick.tsx
- packages/runtime/src/CustomProcessors.ts
- packages/runtime/src/CustomTemplates.ts
- packages/runtime/src/getV2RuntimeFromDll.ts
- packages/runtime/src/history.spec.ts
- packages/runtime/src/history.ts
- packages/runtime/src/index.ts
- packages/runtime/src/internal/Runtime.ts
- packages/runtime/src/internal/compute/WidgetFunctions.ts
- packages/runtime/src/internal/compute/WidgetI18n.ts
- packages/runtime/src/internal/compute/checkIf.ts
> fix(): fallback runtime to v2 for v3 bricks in v2 container

- etc/runtime.api.md
- packages/runtime/src/getV2RuntimeFromDll.ts
- packages/runtime/src/internal/compute/WidgetFunctions.ts
- packages/runtime/src/internal/compute/WidgetI18n.ts
> fix(): v3 widget not work well in v2Kit

- packages/runtime/src/internal/Runtime.ts
> fix(): missing getRecentApps in fallback runtime

- packages/brick-kit/src/internal/menu.spec.ts
- packages/brick-kit/src/internal/menu.ts
> fix(): fix permissions check within dynamic menu

- declarations/global.d.ts
- packages/brick-container/src/bootstrap.ts
- packages/runtime/src/internal/Router.ts
> fix(): emit router events for devtools

- packages/element/src/NextElement.spec.ts
- packages/element/src/NextElement.ts
- packages/element/src/createDecorators.ts
- packages/element/src/internal/symbols.ts
> fix(): fix boolean property defaults to true

- packages/brick-container/serve/middlewares/standaloneBootstrapJson.js
- packages/runtime/src/UIPatch.spec.ts
- packages/runtime/src/UIPatch.ts
- packages/runtime/src/internal/Router.ts
- packages/runtime/src/internal/Runtime.spec.ts
- packages/runtime/src/internal/Runtime.ts
- packages/types/src/manifest.ts
> feat(): support load ui-patch from v3 bricks

- packages/brick-utils/src/removeDeadConditions.spec.ts
- packages/brick-utils/src/removeDeadConditions.ts
> fix(): covert useBrick if it is an array of size 1

- packages/brick-playground/serve/bootstrapJson.js
> fix(): add weather api key for playground

- v3/styles-v3/src/antd-compatible.less
- v3/styles-v3/src/index.js
- v3/styles-v3/src/index.less
- v3/styles-v3/webpack.config.js
AGILE-1386
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): separate `ant-compatible.less` otherwise it will override `@mention-prefix-cls`

- packages/runtime/src/handleHttpError.ts
> fix(): set word-break for handleHttpError

- etc/brick-types.api.md
- packages/brick-container/src/index.tsx
- packages/brick-container/src/styles/variables.css
- packages/brick-container/src/styles/version/index.css
- packages/brick-container/src/styles/version/ui-v8-2.css
- packages/brick-kit/src/core/Router.ts
- packages/brick-kit/src/core/setUIClassName.spec.ts
- packages/brick-kit/src/core/setUIClassName.ts
- packages/brick-types/src/manifest.ts
> chore(): update style

- packages/runtime/src/internal/Router.ts
> fix(): move setUIClassName before mountTree

- packages/easyops-runtime/src/flowApi/FlowApi.ts
- packages/runtime/src/createRoot.spec.ts
- packages/runtime/src/createRoot.ts
- packages/runtime/src/internal/RendererContext.ts
- packages/runtime/src/internal/Router.ts
- packages/runtime/src/internal/Runtime.ts
- packages/runtime/src/internal/data/DataStore.spec.ts
- packages/runtime/src/internal/data/DataStore.ts
- packages/runtime/src/internal/data/resolveData.spec.ts
- packages/runtime/src/internal/data/resolveData.ts
> fix(): fix cache strategy for multi-rendering

- packages/brick-container/serve/serveLocal.js
> fix(): fix a problem when serve with local templates

- packages/brick-kit/src/core/CustomForms/CustomFormContext.ts
- packages/brick-kit/src/core/CustomForms/ExpandCustomForm.ts
- packages/brick-kit/src/core/CustomTemplates/CustomTemplateContext.ts
- packages/brick-kit/src/core/CustomTemplates/expandCustomTemplate.ts
- packages/brick-kit/src/core/FlowApi.ts
- packages/brick-kit/src/core/LocationContext.ts
- packages/brick-kit/src/core/Router.ts
- packages/brick-kit/src/core/StoryboardContext.ts
> fix(): fix error handling for multi-rendering

- packages/brick-kit/src/core/LocationContext.ts
> fix(): mount menu after pre-fetch

- packages/easyops-runtime/src/flowApi/FlowApi.ts
- packages/runtime/src/internal/data/DataStore.spec.ts
- packages/runtime/src/internal/data/DataStore.ts
for compatibility
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): make new error class instead of use `cause`

- packages/brick-container/src/styles/variables.css
- packages/brick-container/src/styles/version/ui-v8-2.css
> chore(): add css variables

- packages/theme/src/variables.css
- packages/theme/src/version/ui-v8-2.css
> chore(): add css variable

- packages/theme/src/default.css
- packages/theme/src/version/ui-v8-2.css
> fix(css): update --slide-up-shadow

- packages/brick-container/serve/getProxy.js
> fix(): handle local settings for non-standalone apps

- packages/theme/src/variables.css
- packages/theme/src/version/ui-v8-2.css
> fix(): add new css variables for tabs

- packages/theme/src/variables.css
> fix(): fix --tabs-outlined-content-padding

- packages/brick-container/src/styles/variables.css
- packages/brick-container/src/styles/version/ui-v8-2.css
> fix(): add new css variables: --grid-card-gap

- packages/theme/src/variables.css
- packages/theme/src/version/ui-v8-2.css
> chore(): add css variables for category-container

- packages/build-next-bricks/package.json
- packages/build-next-bricks/src/build.js
- yarn.lock
> chore(): add less loader

- packages/runtime/src/internal/secret_internals.ts
> fix(): allow to set slots/children for template preview

- packages/brick-kit/src/core/Kernel.ts
> fix(): allow to set slots for template preview

- packages/build-next-bricks/src/scanBricks.js
> fix(): fix scan bricks on unexpected files

- packages/runtime/package.json
- packages/runtime/src/internal/Runtime.ts
- packages/runtime/src/internal/customizeColorTheme.spec.ts
- packages/runtime/src/internal/customizeColorTheme.ts
- yarn.lock
> feat(): support customizing color theme

- packages/brick-container/src/replaceChildren.spec.ts
- packages/brick-container/src/replaceChildren.ts
> fix(): polyfill DocumentFragment:replaceChildren

- etc/runtime.api.md
- packages/brick-playground/src/index.ejs
- packages/brick-playground/src/index.ts
- packages/preview/src/bootstrap.ts
- packages/preview/types.d.ts
- packages/runtime/src/createRoot.ts
- packages/runtime/src/index.ts
> fix(): set ui version in docs and playground

- .github/workflows/ci.yml
> chore(ci): update npm mirror syncing url

- packages/theme/.npmignore
- packages/theme/package.json
- renovate.json
- yarn.lock
> fix(): do not ignore generated.css in npm

- packages/brick-kit/src/core/Kernel.spec.ts
- packages/brick-kit/src/core/Kernel.ts
> fix(): keep runtime injected menus when update

- nx.json
- packages/react-runtime/src/ReactUseBrick.spec.tsx
- packages/react-runtime/src/ReactUseBrick.tsx
> fix(): ignore stale useBrick render

- packages/theme/scripts/build.js
- packages/theme/src/dark.css
- packages/theme/src/default.css
> feat(theme): update color

- packages/theme/src/dark.css
- packages/theme/src/default.css
> fix(): fix sidebar css variables

- packages/brick-container/package.json
- yarn.lock
> chore(): update @next-core/theme

- packages/brick-manifest/index.d.ts
- packages/build-next-bricks/src/makeBrickManifest.js
> feat(): support build bricks with category

- packages/build-next-bricks/bin/build-next-bricks.js
> fix(): fix import path in Windows

- packages/pipes/package.json
- yarn.lock
> fix(): update pipes which target to es5

- packages/runtime/src/internal/data/resolveData.ts
- packages/utils/package.json
- packages/utils/src/general/createProviderClass.spec.ts
- packages/utils/src/general/createProviderClass.ts
- yarn.lock
Refs MONITOR-7391
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): support saveAs method

- packages/theme/src/dark.css
- packages/theme/src/default.css
- packages/theme/src/version/ui-v8-2.css
> chore(): update css variables

- packages/brick-kit/src/core/Router.ts
> fix(): dispatch route.render in v2 as well

- mock-micro-apps/e2e/storyboard.yaml
- packages/runtime/src/internal/Renderer.ts
- packages/runtime/src/internal/Runtime.spec.ts
- packages/types/src/manifest.ts
> fix(): use prop instead of flags to enable incremental sub-routes

- .github/workflows/ci.yml
- etc/runtime.api.md
- packages/runtime/src/internal/CustomTemplates/expandCustomTemplate.ts
- packages/runtime/src/internal/FormRenderer/expandFormRenderer.ts
- packages/runtime/src/internal/data/DataStore.spec.ts
- packages/runtime/src/internal/data/DataStore.ts
- packages/runtime/src/internal/data/realTimeDataInspect.spec.ts
- packages/runtime/src/internal/data/realTimeDataInspect.ts
- packages/runtime/src/internal/secret_internals.ts
> feat(): support real time data inspect

- packages/brick-manifest/index.d.ts
- packages/build-next-bricks/src/makeBrickManifest.js
> feat(): build bricks with insider tag

- packages/build-next-bricks/src/EmitBricksJsonPlugin.js
- packages/build-next-bricks/src/build.js
- packages/loader/src/stableLoadBricks.spec.ts
- packages/loader/src/stableLoadBricks.ts
- packages/loader/src/standalone.ts
Refs NEXT_BUILDER-4478
请勾选以下两组选项其中之一：
或者：
>
>
1. 新增 deprecated-bricks.json 用来标记构件是否废弃
2. 标记废弃的构件，所使用的名称可以被其他构件包使用，可以做到方便的迁移和替换
3. 有标记废弃的构件包会在 brick.json 中生成 deprecatedElements 字段，用来标识哪些构件是废弃的
4. 加载构件包的时候根据该字段去做相应处理，做到平滑没有破坏性的变更
> feat(): support load deprecated brick

- packages/brick-container/package.json
- yarn.lock
> chore(): update next-core/theme

- packages/build-next-bricks/bin/build-next-bricks.js
- packages/build-next-bricks/src/buildStories.js
> feat(): support build brick with stories

- packages/runtime/src/internal/Renderer.ts
> fix(): use substitution strings for console.*

- packages/easyops-runtime/src/menu/fetchMenuById.spec.ts
- packages/easyops-runtime/src/menu/loadDynamicMenuItems.ts
> fix(): fix permission check in dynamic menu items

- packages/brick-container/serve/getIndexHtml.js
- packages/brick-container/serve/getProxies.js
- packages/brick-container/serve/serveLocal.js
Refs NEXT_BUILDER-4492
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): debugger with public dependencies mode

- packages/public-scoped-sdk/index.js
> chore(): add sys-setting-sdk

- packages/public-scoped-sdk/index.js
> chore(): add sys-setting

- packages/public-scoped-sdk/index.js
> chore(): sdk update

- etc/brick-kit.api.md
- packages/brick-kit/src/getRealValue.spec.ts
- packages/brick-kit/src/getRealValue.ts
- packages/brick-kit/src/internal/evaluate.spec.ts
- packages/brick-kit/src/internal/evaluate.ts
> feat(): support real time query

- packages/brick-kit/src/core/FlowApi.ts
> fix(): Provider::saveAs requires the first argument to be the filename

- packages/brick-kit/src/getRealValue.spec.ts
- packages/brick-kit/src/getRealValue.ts
- packages/brick-kit/src/internal/evaluate.spec.ts
- packages/brick-kit/src/internal/evaluate.ts
> fix(): optional use real time query in placeholders

- packages/brick-container/tools/report_installed_brick_next_package.py
> feat(): update reportInstalledBrickNextPackage.py

- packages/brick-container/tools/report_installed_brick_next_package.py
> feat(): update report_install_brick_next_package

- packages/runtime/src/internal/data/DataStore.spec.ts
- packages/runtime/src/internal/data/DataStore.ts
> feat(): track conditional resolve

- declarations/global.d.ts
- packages/brick-container/serve/getProxy.js
- packages/brick-container/serve/utils/injectIndexHtml.js
- packages/brick-container/src/loadBootstrapData.spec.ts
- packages/brick-container/src/loadBootstrapData.ts
- packages/runtime/src/internal/Router.ts
- packages/runtime/src/internal/Runtime.spec.ts
- packages/runtime/src/setAppVariable.spec.ts
- packages/runtime/src/setAppVariable.ts
Refs NEXT_BUILDER-4499
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support union app mode

- packages/brick-container/src/loadBootstrapData.spec.ts
- packages/brick-container/src/loadBootstrapData.ts
- packages/types/src/manifest.ts
> fix(): add bootstrapFile path prefix

- packages/i18n/package.json
- packages/i18n/src/index.ts
- yarn.lock
> fix(): fallback i18next to v22, which supports old browsers (es5)

- packages/brick-container/tools/link_static_file.py
- packages/brick-container/tools/report_installed_micro_app_sa.py
> chore(): 脚本迁移

- packages/brick-container/tools/report_installed_brick_next_package.py
> fix(): fix v3 widget upload error

- packages/theme/src/default.css
- packages/theme/src/variables.css
请勾选以下两组选项其中之一：
- [下] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。
或者：
>
>
> chore(): update tag css variable

- packages/brick-container/tools/report_installed_brick_next_package.py
> chore(): report ingore package without stories.json

- etc/runtime.api.md
- packages/element/src/NextElement.spec.ts
- packages/element/src/createDecorators.ts
- packages/element/src/interfaces.ts
- packages/react-runtime/src/ReactUseBrick.spec.tsx
- packages/react-runtime/src/ReactUseBrick.tsx
- packages/runtime/src/createRoot.ts
- packages/runtime/src/internal/Runtime.ts
- packages/runtime/src/internal/secret_internals.spec.ts
- packages/runtime/src/internal/secret_internals.ts
- packages/runtime/src/internal/setupRootRuntimeContext.spec.ts
- packages/runtime/src/internal/setupRootRuntimeContext.ts
> fix(): use correct runtime context for useBrick within createRoot

- packages/brick-container/deploy/update_postscript.sh
- packages/brick-container/tools/report_installed_brick_next_package.py
脚本读取brick_next_v3目录， 非brick_next目录，
解决brick_next_v3先于brick_next升级时找不到brick_next目录的bug
Ref: NEXT_BUILDER-4517
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): brick_next_v3相关脚本修改，

- packages/build-next-bricks/bin/post-build-next-bricks.js
- packages/build-next-bricks/bin/pre-build-next-bricks.js
> feat(): before build bricks, remove their peerDependencies

- packages/brick-container/tools/report_installed_brick_next_package.py
- packages/brick-container/tools/report_installed_micro_app_sa.py
上报脚本调用本机的micro_app_service/micro_app_sa_service服务
Ref: NEXT_BUILDER-4517
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): brick_next脚本修改，

- packages/brick-container/tools/report_installed_brick_next_package.py
- packages/brick-container/tools/report_installed_micro_app_sa.py
Ref: NEXT_BUILDER-4517
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): python脚本多删除了class

- packages/babel-preset-next/index.js
- packages/babel-preset-next/package.json
> fix(): add missing dep `@babel/runtime`

- packages/build-next-bricks/src/generatePkgBuild.js
> fix(): fix async copyFile

- packages/brick-container/serve/getProxy.js
> fix(): fix bootstrap.json match RegExp

- packages/brick-container/serve/getProxies.js
> fix(): bootstrap match RegExp

- packages/theme/src/dark.css
- packages/theme/src/default.css
> chore(): update nav css variables

- etc/brick-kit.api.md
- packages/brick-kit/src/BrickAsComponent.tsx
> fix(): fix useBrick with v3 bricks in v2 container

- packages/babel-preset-prismjs/index.js
> feat():code-bricks.code-display支持perl语言 ref CD-6900

- packages/brick-container/tools/report_installed_micro_app_sa.py
> chore(): standalone-na 上报脚本修改， 增加字段usePublicDependencies/unionTags

- packages/brick-container/deploy/package.conf.yaml
- packages/brick-container/deploy/update_postscript.sh
ref: NEXT_BUILDER-4548
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): brick_next依赖micro_app_standalone_service

- packages/brick-container/tools/link_static_file.py
ref: UC-668
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): sa-na上报python脚本调整， 如果standalone-na目录下bricks/core目录为空, 说明需要体积精简

- packages/brick-container/tools/link_static_file.py
> feat(): brick_next中sa-na脚本修改， 支持sa-na体积精简 Ref: UC-668

- .size-limit.js
- packages/brick-dll/manifest.snapshot.json
- packages/easyops-analytics/package.json
- packages/easyops-analytics/src/ApiAnalysis.spec.ts
- packages/easyops-analytics/src/ApiAnalysis.ts
- v3/brick-dll-v3/manifest.snapshot.json
- v3/brick-dll-v3/package.json
- yarn.lock
Closes CMDB_CONSUME-233
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): 优化框架性能数据发送时机, 不要最后一起发送

- packages/brick-container/tools/report_installed_micro_app_sa.py
refs APP_STORE-34
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): report增加author/description字段

- packages/brick-container/tools/link_static_file.py
> chore(): 判断是否体积精简的条件修改

- .size-limit.js
- packages/brick-kit/src/core/Router.ts
- packages/brick-kit/src/i18n/constants.ts
- packages/brick-kit/src/i18n/locales/en.ts
- packages/brick-kit/src/i18n/locales/zh.ts
close INFRA-2422
请勾选以下两组选项其中之一：
或者：
>
>
> feat(router): brickPageNotFound support go back to homepage

- package.json
- packages/dev-dependencies/package.json
- yarn.lock
> fix(): lock lint-staged to ~13.0.4, since newer versions require Node 16+

- __jest__/setup.ts
- packages/easyops-runtime/package.json
- packages/easyops-runtime/src/analytics/analytics.spec.ts
- packages/easyops-runtime/src/analytics/analytics.ts
- packages/easyops-runtime/src/analytics/transport.ts
- yarn.lock
Closes CMDB_CONSUME-246
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): next-v3框架前端指标发送优化

- packages/brick-container/src/i18n/constants.ts
- packages/brick-container/src/i18n/locales/en.ts
- packages/brick-container/src/i18n/locales/zh.ts
- packages/brick-container/src/index.tsx
- packages/brick-kit/src/core/Router.ts
- packages/brick-kit/src/handleHttpError.spec.tsx
- packages/brick-kit/src/handleHttpError.tsx
> fix(): handle special error

- packages/brick-dll/manifest.snapshot.json
- packages/easyops-analytics/package.json
- packages/easyops-analytics/src/ApiAnalysis.spec.ts
- packages/easyops-analytics/src/ApiAnalysis.ts
- v3/brick-dll-v3/manifest.snapshot.json
- v3/brick-dll-v3/package.json
- yarn.lock
> fix(): revert yarn.lock and refine analysis tests

- packages/build-next-bricks/src/getTypeDeclaration.js
> fix(): record references when using extends

- packages/runtime/src/internal/Router.ts
- packages/runtime/src/internal/mount.ts
> fix(): always sync render when mount

- cypress/e2e/size-check.spec.js
- packages/runtime/src/internal/data/DataStore.ts
- packages/runtime/src/internal/data/resolveDataStore.spec.ts
- packages/runtime/src/internal/data/resolveDataStore.ts
> fix(): handle circular STATE with TPL

- packages/brick-playground/src/index.css
> fix(): refine playground style in small screen

- packages/runtime/src/internal/Renderer.spec.ts
- packages/runtime/src/internal/RendererContext.ts
> fix(): fix useBrick with portal dynamic nodes rerender

- packages/create-next-repo/src/patches/patchInternalRenovate.spec.ts
- packages/create-next-repo/src/patches/patchInternalRenovate.ts
- packages/dev-dependencies/patch.js
- packages/dev-dependencies/patches/index.js
- packages/dev-dependencies/patches/updateRenovateForV2.js
- packages/dev-dependencies/patches/updateRenovateForV2.spec.js
- packages/dev-dependencies/patches/updateRenovatePostExecutionMode.js
- packages/dev-dependencies/patches/updateRenovatePostExecutionMode.spec.js
> feat(): patch renovate post execution mode

- cypress/e2e/sub-routes.spec.js
- mock-micro-apps/e2e/storyboard.yaml
- packages/runtime/src/internal/Renderer.ts
- packages/runtime/src/internal/RendererContext.ts
- packages/runtime/src/internal/Router.ts
- packages/runtime/src/internal/Runtime.spec.ts
> feat(): support nesting incremental sub-routes

- packages/runtime/src/internal/Renderer.ts
- packages/runtime/src/internal/Runtime.spec.ts
> fix(): fix memoized route slot

- packages/brick-utils/src/removeDeadConditions.spec.ts
- packages/brick-utils/src/removeDeadConditions.ts
- packages/storyboard/src/interfaces.ts
- packages/storyboard/src/parseStoryboard.ts
- packages/storyboard/src/traverseStoryboard.ts
Closes NEXT_BUILDER-4596
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): handle dead conditions with menu

- packages/build-next-bricks/src/getTypeDeclaration.js
so it can be displayed as table in docs
请勾选以下两组选项其中之一：
或者：
>
>
> fxi(): treat type literal alias as interface

- packages/brick-container/serve/utils/sizeCheck.js
> fix(): fix size check: ignore alias of deprecated bricks

- .github/workflows/cleanup-caches.yml
> chore(): fix cleanup caches

- packages/brick-container/src/loadBootstrapData.spec.ts
- packages/brick-container/src/loadBootstrapData.ts
> feat(): getRuntimeMicroAppStandalone with version

- packages/react-runtime/package.json
- packages/react-runtime/src/index.ts
- packages/react-runtime/src/useProvider/fetch.spec.ts
- packages/react-runtime/src/useProvider/fetch.ts
- packages/react-runtime/src/useProvider/useProvider.spec.tsx
- packages/react-runtime/src/useProvider/useProvider.ts
- packages/react-runtime/src/useProvider/useProviderArgs.spec.ts
- packages/react-runtime/src/useProvider/useProviderArgs.ts
- packages/react-runtime/src/useProvider/useProviderArgsDefaults.ts
- packages/react-runtime/src/useProvider/useProviderTypes.ts
- yarn.lock
Closes MONITOR-7866
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): next-v3支持react hook调用provider

- packages/runtime/src/internal/Router.ts
- packages/runtime/src/setWatermark.spec.ts
- packages/runtime/src/setWatermark.ts
> feat(): support set watermark

- packages/runtime/src/getRealValue.spec.ts
- packages/runtime/src/getRealValue.ts
> feat(): support getRealValue

- packages/brick-container/serve/getProxies.js
Refs NEXT_BUILDER-4746
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复在开发者中心构件调试页本地调试失效问题

- packages/runtime/src/internal/Router.ts
> fix(): set watermark later

- packages/easyops-runtime/src/websocket/MessageDispatcher.spec.ts
- packages/easyops-runtime/src/websocket/MessageDispatcher.ts
> fix(): fix when message subscribe after onMessage

- packages/eslint-config-next/index.js
- packages/runtime/src/internal/CustomTemplates/constants.ts
- packages/runtime/src/internal/CustomTemplates/expandCustomTemplate.ts
- packages/runtime/src/internal/CustomTemplates/setupTemplateProxy.ts
- packages/runtime/src/internal/Renderer.spec.ts
- packages/runtime/src/internal/Renderer.ts
- packages/runtime/src/internal/interfaces.ts
> fix(): isolate forEach access between inside and outside of template

- declarations/global.d.ts
- packages/brick-container/serve/getProxy.js
- packages/brick-container/serve/utils/injectIndexHtml.js
- packages/brick-container/src/images.spec.ts
- packages/brick-container/src/images.ts
- packages/brick-container/src/loadBootstrapData.spec.ts
- packages/brick-container/src/loadBootstrapData.ts
- packages/runtime/src/internal/Runtime.ts
- packages/runtime/src/setWatermark.spec.ts
- packages/runtime/src/setWatermark.ts
Refs NEXT_BUILDER-4768
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support new union app mode

- packages/brick-kit/src/core/Kernel.spec.ts
- packages/brick-kit/src/core/Kernel.ts
Refs NEXT_BUILDER-4501
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): fix mini-bootstrap load

- packages/brick-container/serve/getIndexHtml.js
- packages/brick-container/serve/getProxies.js
- packages/brick-kit/src/core/Kernel.ts
- packages/brick-kit/src/internal/images.spec.ts
- packages/brick-kit/src/internal/images.ts
> fix(): brick local debug

- packages/brick-kit/src/internal/images.ts
> fix(): fix image preview

- etc/runtime.api.md
- packages/runtime/src/index.ts
> chore(): export getRealValue

- packages/brick-container/serve/getIndexHtml.js
- packages/brick-container/serve/getProxies.js
> fix(): 支持 union app root 的变量

- packages/brick-container/serve/getProxy.js
- packages/brick-container/serve/utils/injectIndexHtml.js
> fix(): 支持 union app root 变量

- packages/brick-container/serve/getIndexHtml.js
- packages/brick-container/serve/getProxies.js
> fix(): refine union app root

- packages/brick-container/tools/package-union/report_union_micro_app.py
- packages/brick-container/tools/report_installed_brick_next_package.py
- packages/brick-container/tools/report_installed_micro_app_sa.py
1. report接口增加isFromUnionApp字段
2. 名字服务调用修改： 127.0.0.1-〉ip
ref: NEXT_BUILDER-4801
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 联合na上报脚本更新

- .github/workflows/update-docs-etc.yml
- bricks/e2e/src/async-dep/index.tsx
- bricks/e2e/src/async-wrap/index.tsx
- bricks/e2e/src/bootstrap.ts
- etc/runtime.api.md
- packages/react-runtime/package.json
- packages/react-runtime/src/asyncWrapBrick.spec.tsx
- packages/react-runtime/src/asyncWrapBrick.ts
- packages/react-runtime/src/index.ts
- packages/runtime/src/internal/secret_internals.ts
> feat(): support asyncWrapBrick

- packages/brick-container/package.json
- packages/brick-container/src/AuthenticationChange.spec.ts
- packages/brick-container/src/AuthenticationChange.ts
- packages/brick-container/src/bootstrap.ts
- packages/brick-container/src/i18n.ts
- packages/brick-container/src/loadCheckLogin.ts
- packages/runtime/src/Dialog.ts
- yarn.lock
> feat(): refresh page if auth changed

- cypress/e2e/sub-routes.spec.js
- mock-micro-apps/e2e/storyboard.yaml
- packages/runtime/src/createRoot.ts
- packages/runtime/src/internal/Renderer.spec.ts
- packages/runtime/src/internal/Renderer.ts
- packages/runtime/src/internal/Runtime.spec.ts
- packages/runtime/src/internal/setupRootRuntimeContext.ts
> fix(): setup runtime context for useBrick

- packages/build-next-bricks/src/getTypeDeclaration.js
> fix(): ignore computed property signature for types

- packages/theme/scripts/build.js
Closes INFRA-2721
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): update green color

- cypress/e2e/sub-routes.spec.js
- etc/runtime.api.md
- mock-micro-apps/e2e/storyboard.yaml
- packages/runtime/src/createRoot.ts
- packages/runtime/src/internal/Renderer.spec.ts
- packages/runtime/src/internal/Renderer.ts
- packages/runtime/src/internal/RendererContext.ts
- packages/runtime/src/internal/Router.ts
- packages/runtime/src/internal/Runtime.spec.ts
- packages/runtime/src/internal/interfaces.ts
- packages/runtime/src/internal/secret_internals.ts
> fix(): fix nesting incremental sub-routes

- packages/runtime/src/internal/RendererContext.ts
> fix(): override stale incremental render callback

- packages/brick-container/serve/env.js
- packages/brick-container/serve/getProxy.js
> fix(): handle proxy origin

- cypress.config.ts
- cypress/e2e/sub-routes.spec.js
- packages/runtime/src/internal/Renderer.spec.ts
- packages/runtime/src/internal/Renderer.ts
- packages/runtime/src/internal/Runtime.spec.ts
> fix(): fix handling menu requests

- packages/brick-container/tools/package-union/report_union_micro_app.py
- packages/brick-container/tools/report_installed_micro_app_sa.py
1. union_na并行升级
2. 删除unionTags字段->废弃
3. unionApp的report接口加上unionAppInfo信息
Closes NEXT_BUILDER-4835
Closes NEXT_BUILDER-4837
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): union-na中的多个standalone-na要并行升级

- packages/brick-container/serve/getProxies.js
- packages/brick-container/serve/utils.js
> fix(): 修复在构件仓库中调试本地构件时 container 为 remote 模式时报错问题

- packages/brick-container/deploy/package.conf.yaml
> chore(): 下线组件,无需再依赖

- packages/brick-container/deploy/package.conf.yaml
> chore(): 下线组件，无需再依赖

- packages/brick-container/src/loadBootstrapData.spec.ts
- packages/brick-container/src/loadBootstrapData.ts
- packages/runtime/src/internal/Runtime.spec.ts
- packages/runtime/src/internal/Runtime.ts
Closes MONITOR-8335
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support userConfig.settings.locales

- packages/brick-kit/src/core/Kernel.spec.ts
- packages/brick-kit/src/core/Router.ts
- packages/brick-kit/src/core/processors.spec.ts
- packages/brick-kit/src/core/processors.ts
- packages/brick-kit/src/core/setAppLocales.spec.ts
- packages/brick-kit/src/core/setAppLocales.ts
Closes MONITOR-8335
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support settings.locales

- packages/preview/package.json
- packages/preview/src/bootstrap.ts
- packages/preview/src/replaceUseChildren.ts
> feat(preview): replace useChildren with useBrick

- packages/brick-container/src/preview.ts
- packages/brick-container/src/replaceUseChildren.spec.ts
- packages/brick-container/src/replaceUseChildren.ts
> feat(): support useChildren in preview

- packages/preview/src/replaceUseChildren.ts
> fix(): delete original slots for useChildren

- .github/workflows/ci.yml
- packages/brick-container/src/preview.ts
> fix(): add missing globals for preview page

- etc/runtime.api.md
- packages/brick-playground/src/index.ts
- packages/preview/src/bootstrap.ts
- packages/preview/types.d.ts
- packages/runtime/src/createRoot.spec.ts
- packages/runtime/src/createRoot.ts
- packages/runtime/src/internal/compute/evaluate.spec.ts
- packages/runtime/src/internal/compute/evaluate.ts
> feat(): support setting url and app for preview rendering

- packages/brick-container/serve/index.js
> fix(): bypass SSE requests

- packages/preview/package.json
- packages/preview/src/bootstrap.ts
- packages/preview/src/index.ts
- packages/preview/src/replaceUseChildren.spec.ts
- packages/preview/src/replaceUseChildren.ts
> fix(): replace useChildren in children

- packages/brick-utils/src/removeDeadConditions.spec.ts
- packages/brick-utils/src/removeDeadConditions.ts
> fix(): keep conditional handlers if has `else`

- packages/test-next/index.d.ts
- packages/test-next/src/createJestConfig.js
> feat(): allow adding coveragePathIgnorePatterns

- packages/element/src/createDecorators.ts
- packages/element/src/internal/symbols.ts
Retrieve the same symbols for mixed versions of @next-core/react-element and @next-core/element
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): use `Symbol.for` instead of `Symbol`

- packages/brick-container/serve/getProxy.js
> fix(): 修复构件仓库调试报错问题

- packages/easyops-runtime/package.json
- packages/easyops-runtime/src/auth.ts
- yarn.lock
Refs NEXT_BUILDER-4894
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support accessToken

- packages/brick-playground/src/index.ts
- packages/preview/package.json
- packages/preview/src/bootstrap.ts
- packages/preview/types.d.ts
> feat(preview): support _preview_only_inject

- etc/runtime.api.md
- packages/easyops-runtime/src/flowApi/CollectContracts.spec.ts
- packages/easyops-runtime/src/flowApi/CollectContracts.ts
- packages/easyops-runtime/src/flowApi/index.ts
- packages/runtime/src/internal/interfaces.ts
- packages/runtime/src/internal/secret_internals.spec.ts
- packages/runtime/src/internal/secret_internals.ts
Refs NEXT_BUILDER-4911
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): support debug data value

- etc/runtime.api.md
- packages/runtime/src/internal/secret_internals.spec.ts
- packages/runtime/src/internal/secret_internals.ts
Refs NEXT_BUILDER-4911
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): debug data value in template

- packages/brick-playground/src/index.ejs
- packages/brick-playground/src/index.ts
> fix(): default to yaml in playground

- packages/build-next-bricks/src/build.js
> fix(): Use react required version for react-dom if it is not specified

- packages/build-next-bricks/index.d.ts
- packages/build-next-bricks/src/build.js
> feat(): support resolve options

- dll/editor-bricks-helper/manifest.snapshot.json
- etc/brick-kit.api.md
- packages/brick-dll/manifest.snapshot.json
- packages/brick-kit/src/core/CollectContracts.spec.ts
- packages/brick-kit/src/core/CollectContracts.ts
- packages/brick-kit/src/core/Runtime.ts
- packages/brick-kit/src/index.ts
> fix(): 搜集调试契约兼容 v2 框架

- packages/runtime/src/internal/secret_internals.ts
> fix(): refine debug

- packages/preview/src/bootstrap.ts
- packages/preview/types.d.ts
> feat(): support noResolve for preview inject

- packages/brick-utils/src/builder/normalizeMenu.spec.ts
- packages/brick-utils/src/builder/normalizeMenu.ts
> feat(normalizeMenu): add uuid

- etc/runtime.api.md
- packages/brick-container/scripts/start.js
- packages/brick-container/serve/index.js
- packages/react-runtime/src/ReactUseBrick.spec.tsx
- packages/react-runtime/src/ReactUseBrick.tsx
- packages/runtime/src/internal/Renderer.spec.ts
- packages/runtime/src/internal/Renderer.ts
- packages/runtime/src/internal/Router.ts
- packages/runtime/src/internal/secret_internals.ts
- packages/types/src/manifest.ts
> feat(): render error boundary

- packages/utils/src/general/createSSEStream.spec.ts
- packages/utils/src/general/createSSEStream.ts
> fix(): handle sse error event

- packages/browserslist-config-next/production.js
> feat(): update browser requirements to chrome 84+ / firefox 72+ / safari 14.1+

- packages/theme/src/default.css
> fix(): menu css variable

- packages/runtime/src/internal/Runtime.ts
> fix(): not necessary to process brick packages multiple times

- etc/runtime.api.md
- packages/build-next-bricks/src/EmitBricksJsonPlugin.js
- packages/build-next-bricks/src/build.js
- packages/build-next-bricks/src/scanBricks.js
- packages/loader/src/stableLoadBricks.spec.ts
- packages/loader/src/stableLoadBricks.ts
- packages/runtime/src/CustomEditors.spec.ts
- packages/runtime/src/CustomEditors.ts
- packages/runtime/src/index.ts
> feat(): add CustomEditorRegisty

- packages/brick-container/src/browse-happy.ejs
Refs NWYD-2063
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): browse-happy.ejs文件增加对已升级浏览器访问该url时重定向到首页

- etc/runtime.api.md
- packages/runtime/src/internal/secret_internals.ts
> feat(): runtime exprot loadEditors

- dll/editor-bricks-helper/manifest.snapshot.json
- etc/brick-kit.api.md
- packages/brick-dll/manifest.snapshot.json
- packages/brick-kit/src/core/Kernel.spec.ts
- packages/brick-kit/src/core/processors.spec.ts
- packages/brick-kit/src/core/processors.ts
- packages/brick-kit/src/index.ts
> fix(): Launchpad 搜索报错

- packages/cook/src/ExecutionContext.ts
- packages/cook/src/__fixtures__/function-names.ts
- packages/cook/src/__fixtures__/index.ts
- packages/cook/src/__fixtures__/try-statements.ts
- packages/cook/src/context-free.ts
- packages/cook/src/cook.spec.ts
- packages/cook/src/cook.ts
- packages/cook/src/interfaces.ts
- packages/runtime/src/StoryboardFunctionRegistry.ts
- packages/supply/src/index.ts
> feat(): support single-step debugging for functions

- etc/brick-kit.api.md
- packages/brick-kit/src/core/Runtime.ts
- packages/brick-kit/src/core/interfaces.ts
- packages/brick-kit/src/developHelper.ts
> feat(): 获取当前微应用上下文变量信息

- etc/runtime.api.md
- packages/runtime/src/internal/Renderer.ts
- packages/runtime/src/internal/Router.ts
- packages/runtime/src/internal/interfaces.ts
- packages/runtime/src/internal/routeMatchedMap.spec.ts
- packages/runtime/src/internal/routeMatchedMap.ts
- packages/runtime/src/internal/secret_internals.spec.ts
- packages/runtime/src/internal/secret_internals.ts
请勾选以下两组选项其中之一：
或者：
>
>
在 VB 编排时 展示当前应用下相关的运行变量
> feat(): 获取微应用上下文相关变量并展示

- packages/custom-antd-styles/src/notification.less
Closes INFRA-2954
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): 公告提醒样式调整

- packages/custom-antd-styles/src/notification.less
Closes INFRA-2954
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 公告提醒样式调整

- .github/workflows/update-docs-etc.yml
- packages/cook/src/cook.ts
> fix(): refine debugger breakpoints

- etc/runtime.api.md
- packages/cook/src/cook.ts
- packages/cook/src/precook.ts
- packages/runtime/src/StoryboardFunctionRegistry.ts
> fix(): fix debugging nested FN calls

- packages/brick-kit/src/core/CustomEditors.spec.ts
- packages/brick-kit/src/core/CustomEditors.ts
- packages/brick-kit/src/core/Runtime.ts
- packages/brick-kit/src/core/exports.ts
- packages/build-config-factory/src/post-build.js
- packages/webpack-config-factory/src/bricks/ScanPropertyEditorBricksPlugin.js
- packages/webpack-config-factory/src/bricks/index.js
- packages/webpack-config-factory/src/bricks/webpack.base.factory.js
> feat(): support CustomEditors

- packages/easyops-runtime/src/checkPermissions.spec.ts
- packages/easyops-runtime/src/checkPermissions.ts
Closes CMDB_CONSUME-362
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): permission.check在路由变化时失败

- packages/easyops-runtime/src/flowApi/FlowApi.ts
> fix(): compatible with sub services of api gateway

- packages/build-next-bricks/src/scanBricks.js
> fix(): editor export name

- packages/brick-playground/serve/bootstrapJson.js
> fix(): inject local editors in misc

- packages/runtime/src/StoryboardFunctionRegistry.spec.ts
- packages/runtime/src/StoryboardFunctionRegistry.ts
> fix(): enable function debug mode only when necessary

- packages/cook/src/cook.spec.ts
- packages/cook/src/cook.ts
> fix(): call hooks.beforeEvaluate in NamedEvaluation

- packages/brick-playground/src/index.ts
> fix(): respect gap settings of examples in playground

- packages/loader/src/stableLoadBricks.ts
> feat(): update load editor name

- packages/runtime/src/CustomEditors.spec.ts
- packages/runtime/src/CustomEditors.ts
> fix(): customEditor not throw error

- packages/loader/src/stableLoadBricks.ts
> fix(): v2 editor load fail

- packages/cook/src/__fixtures__/functions.ts
- packages/cook/src/cook.ts
> fix(): lodash requires function length

- etc/runtime.api.md
- packages/easyops-runtime/src/menu/fetchMenuById.ts
- packages/runtime/src/internal/CustomTemplates/constants.ts
- packages/runtime/src/internal/CustomTemplates/expandCustomTemplate.ts
- packages/runtime/src/internal/CustomTemplates/setupTemplateProxy.ts
- packages/runtime/src/internal/FormRenderer/expandFormRenderer.ts
- packages/runtime/src/internal/Renderer.spec.ts
- packages/runtime/src/internal/Renderer.ts
- packages/runtime/src/internal/compute/evaluate.spec.ts
- packages/runtime/src/internal/compute/evaluate.ts
- packages/runtime/src/internal/interfaces.ts
> feat(): support SIZE of :forEach in expressions

- packages/brick-playground/src/index.css
- packages/brick-playground/src/index.ejs
- packages/brick-playground/src/index.ts
> fix(): allow toggling source code

- package.json
- packages/dev-dependencies/patch.js
- yarn.lock
> chore(): update ua-parser-js

- packages/runtime/src/internal/Renderer.ts
> fix(): computed formData

- packages/runtime/src/internal/CustomTemplates/constants.ts
- packages/runtime/src/internal/CustomTemplates/expandCustomTemplate.ts
- packages/runtime/src/internal/CustomTemplates/setupTemplateProxy.ts
- packages/runtime/src/internal/Renderer.spec.ts
- packages/runtime/src/internal/Renderer.ts
- packages/runtime/src/internal/interfaces.ts
> fix(): allow accessing forEach variables of template internal from external

- packages/brick-container/src/loadBootstrapData.spec.ts
- packages/brick-container/src/loadBootstrapData.ts
- packages/runtime/src/internal/Runtime.spec.ts
- packages/runtime/src/internal/Runtime.ts
- packages/types/src/manifest.ts
> feat(): 平台title支持自定义配置

- packages/runtime/src/internal/FormRenderer/expandFormRenderer.ts
- packages/runtime/src/internal/FormRenderer/registerFormRenderer.spec.ts
- packages/runtime/src/internal/FormRenderer/registerFormRenderer.ts
- packages/runtime/src/internal/Renderer.ts
Refs FLOW_BUILDER-1203
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): proxy form method

- packages/runtime/src/internal/Runtime.spec.ts
- packages/runtime/src/internal/Runtime.ts
> fix(): 如果小产品自定义了title无论什么情况都显示自定义title

- dll/editor-bricks-helper/manifest.snapshot.json
- packages/brick-dll/manifest.snapshot.json
- packages/brick-kit/src/core/Router.ts
- packages/brick-kit/src/core/StoryboardFunctionRegistryFactory.ts
- packages/brick-kit/src/internal/evaluate.ts
- packages/brick-kit/src/internal/menu.ts
- packages/brick-utils/src/removeDeadConditions.ts
- packages/brick-utils/src/track.ts
- packages/brick-utils/src/visitStoryboard.ts
- packages/cook/src/cook.ts
- packages/cook/src/interfaces.ts
- packages/cook/src/precookFunction.spec.ts
- packages/cook/src/precookFunction.ts
- packages/cook/src/preevaluate.spec.ts
- packages/cook/src/preevaluate.ts
- v3/brick-dll-v3/manifest.snapshot.json
> fix(): cache function and expression AST

- etc/brick-types.api.md
- packages/brick-kit/src/core/LocationContext.ts
- packages/brick-types/src/runtime.ts
> fix(): append all auth info into SYS

- packages/runtime/src/internal/FormRenderer/registerFormRenderer.spec.ts
- packages/runtime/src/internal/FormRenderer/registerFormRenderer.ts
> fix(): Fixed an issue when rendering the root scene

- packages/loader/src/stableLoadBricks.spec.ts
- packages/loader/src/stableLoadBricks.ts
> fix(): refine error reporting of loading bricks

- packages/brick-kit/src/core/Runtime.ts
> fix(): return correct current app when rendering storyboard

- packages/brick-container/tools/package-union/report_union_micro_app.py
> fix(): 更新union_na脚本

- packages/build-next-bricks/src/scanBricks.js
> feat(): support widget custom editor

- packages/yo/src/plopfile.js
- packages/yo/src/templates/brick/index.tsx.hbs
> fix(): refine brick template

- .npmrc
- cypress/e2e/sub-routes.spec.js
- mock-micro-apps/e2e/storyboard.yaml
- packages/runtime/src/internal/Router.ts
- packages/runtime/src/internal/Runtime.spec.ts
> fix(): handle multi navigations to a page with incrementalSubRoutes

- packages/runtime/src/internal/secret_internals.spec.ts
- packages/runtime/src/internal/secret_internals.ts
> fix(): fix updating route in bricks

- packages/runtime/src/setWatermark.spec.ts
- packages/runtime/src/setWatermark.ts
> fix(): do not call showWatermark if there is no content

- package.json
- packages/brick-container/serve/index.js
- packages/brick-container/serve/utils/shouldServeAsIndexHtml.js
> fix(): fix serve home

- packages/editor-bricks-helper/src/internal/BuilderDataManager.ts
> fix(): trigger data change after updateNode

- packages/brick-utils/src/removeDeadConditions.spec.ts
- packages/brick-utils/src/removeDeadConditions.ts
> fix(): fix dead removal for context onChange

- packages/brick-container/serve/getProxy.js
> fix(): http-proxy-middleware does not support zstd encoding

- packages/brick-container/serve/getProxy.js
- packages/brick-container/serve/index.js
> fix(): fix serve as https

- packages/runtime/src/StoryboardFunctionRegistry.spec.ts
- packages/runtime/src/StoryboardFunctionRegistry.ts
- packages/types/src/manifest.ts
> fix(): use compiled deps and perm from functions

- packages/brick-dll/package.json
> fix(): update peer deps version for @next-core/easyops-analytics

- packages/easyops-runtime/src/flowApi/FlowApi.ts
- packages/easyops-runtime/src/flowApi/FlowApiProvider.spec.ts
- packages/easyops-runtime/src/flowApi/FlowApiProvider.ts
> fix(): only need necessary fields for contracts

- packages/brick-utils/src/builder/normalizeBuilderNode.spec.ts
- packages/brick-utils/src/builder/normalizeBuilderNode.ts
> fix(normalizeBuilderNode): disposable urlQueryParams, and handle empty string for json fields

- packages/runtime/src/internal/Renderer.ts
> fix(): Enable leading invocation for debounced re-render, to keep tracking orders

- packages/brick-kit/src/core/Kernel.ts
- packages/brick-kit/src/core/processors.spec.ts
- packages/brick-kit/src/core/processors.ts
> feat(): support setting merge method in app user config

- packages/build-next-bricks/src/buildStories.js
> fix(): set upward for babel-loader for building stories

- packages/cook/src/__fixtures__/expressions.ts
- packages/cook/src/sanitize.ts
- packages/supply/src/index.ts
> feat(): allow accessing URL

- packages/runtime/src/internal/bindListeners.spec.ts
- packages/runtime/src/internal/bindListeners.ts
- packages/types/src/manifest.ts
> feat(): new event action: parent.postMessage

- packages/runtime/src/internal/compute/getGeneralGlobals.spec.ts
- packages/runtime/src/internal/compute/getGeneralGlobals.ts
> fix(): resume THEME.getCssPropertyValue

- packages/easyops-runtime/src/websocket/MessageService.ts
> fix(): handle websocket close immediately after open

- packages/brick-dll/manifest.snapshot.json
- packages/next-docs/package.json
- packages/pipes/package.json
- packages/storyboard-function-types/package.json
- v3/brick-dll-v3/manifest.snapshot.json
- yarn.lock
> fix(): 更新brick-next-pipes refs BRICK-555

- packages/build-next-bricks/src/scanBricks.js
> fix(): set editors chunk to its folder

- packages/runtime/src/internal/Renderer.spec.ts
- packages/runtime/src/internal/Renderer.ts
- packages/runtime/src/internal/RendererContext.ts
- packages/runtime/src/internal/Runtime.spec.ts
- packages/runtime/src/internal/compute/listenOnTrackingContext.ts
- packages/runtime/src/internal/data/DataStore.ts
- packages/runtime/src/internal/interfaces.ts
And dispose ctx tracks after unmount
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): handle ctx change just after control node computed

- dll/editor-bricks-helper/manifest.snapshot.json
- etc/brick-kit.api.md
- packages/brick-dll/manifest.snapshot.json
- packages/brick-kit/src/ModalStack.spec.ts
- packages/brick-kit/src/ModalStack.ts
- packages/brick-kit/src/index.ts
> feat(): support instantiateModalStack

- .size-limit.js
- packages/babel-preset-next/index.js
- packages/brick-container/package.json
- yarn.lock
> fix(): update core-js to the latest

- packages/brick-container/src/polyfill.ts
> fix(): manually add array polyfills since old babel doesn't support them

- package.json
- yarn.lock
Reverts easyops-cn/next-core#4542
> Revert "chore(deps): Update dependency lerna to ^8.1.9 (next)"

- etc/brick-kit.api.md
- etc/brick-types.api.md
- packages/brick-kit/src/core/StoryboardFunctionRegistryFactory.spec.ts
- packages/brick-kit/src/core/StoryboardFunctionRegistryFactory.ts
- packages/brick-kit/src/internal/getGeneralGlobals.ts
- packages/brick-types/src/manifest.ts
- packages/supply/src/index.ts
> feat(): support native mode for storyboard functions

- packages/runtime/src/internal/FormRenderer/registerFormRenderer.spec.ts
- packages/runtime/src/internal/FormRenderer/registerFormRenderer.ts
Closes CUSTOMIZE-1018
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): form-renderer 支持 getFieldsValue 方法

- packages/brick-kit/src/core/Kernel.ts
> fix(): load v3 processors eagerly

- etc/brick-kit.api.md
- packages/brick-container/src/preview/listen.spec.ts
- packages/brick-container/src/preview/listen.ts
- packages/brick-kit/src/core/Router.ts
- packages/brick-kit/src/core/listen.spec.ts
- packages/brick-kit/src/core/listen.ts
- packages/brick-kit/src/developHelper.ts
Refs CD-8866
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 支持嵌入 iframe 时通讯

- packages/brick-container/deploy/package.conf.yaml
> fix(): remove dep of micro_app_service

- packages/easyops-runtime/src/checkInstalledApps.ts
> fix(): set noAbortOnRouteChange for installed apps checking

- packages/brick-container/src/index.tsx
Refs CD-9047
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): refine loading bar custom event

- .size-limit.js
> chore(): update size-limit

- packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
- packages/editor-bricks-helper/src/internal/BuilderDataManager.ts
> fix(): prefer default "" slot over "content" when drag bricks

- packages/editor-bricks-helper/src/DropZone/reverseNormalize.ts
> fix(): dataSource is a json field

- packages/brick-utils/src/builder/normalizeBuilderNode.spec.ts
- packages/brick-utils/src/builder/normalizeBuilderNode.ts
> fix(): remove raw yaml fields

- packages/sdk-scripts/src/interface.ts
- packages/sdk-scripts/src/lib/Api.ts
- packages/sdk-scripts/src/lib/FunctionBlock.ts
- packages/sdk-scripts/src/loaders/__snapshots__/loadService.spec.ts.snap
- packages/sdk-scripts/yaml/api/cd/package/search.yaml
> fix(): support custom service name

- .size-limit.js
- declarations/global.d.ts
- packages/brick-container/webpack/common.js
- packages/brick-icons/rollup.config.js
- packages/brick-icons/scripts/pre-build.js
> feat(): support image icons

- etc/brick-types.api.md
- packages/brick-kit/src/BrickAsComponent.tsx
- packages/brick-types/src/manifest.ts
> feat(): support onScrollIntoView for useBrick

- packages/webpack-config-factory/src/bricks/webpack.base.factory.js
Closes INFRA-001
请勾选以下两组选项其中之一：
或者：
>
>
> fix(): 修复设置为公共依赖后lazyBrick加载错误问题

- .pkgbuild/@easyops/PKGBUILD
- conf/config.yaml
- packages/brick-container/deploy/install_postscripts.sh
- packages/brick-container/deploy/update_postscript.sh
- packages/brick-container/tools/package-union/report_union_micro_app.py
- packages/brick-container/tools/report_installed_brick_next_package.py
- packages/brick-container/tools/report_installed_theme_template.py
- packages/brick-container/tools/utils/get_headers.py
Ref: INFRA-4667
请勾选以下两组选项其中之一：
或者：
>
>
> feat(): brick_next支持服务鉴权

- packages/brick-container/tools/utils/custom_get_token_util.py
- packages/brick-container/tools/utils/get_headers.py
Refs INFRA-5181
@stallman-cui CC
> chore(brick_next_v3): token 鉴权改造，脚本申请 token 需要带上 clientId 和 secret
