packages/typedoc-plugin-filter-inherit/package.json
packages/typedoc-plugin-filter-inherit/src/constants.ts
packages/typedoc-plugin-filter-inherit/src/index.ts
packages/typedoc-plugin-filter-inherit/src/plugin.ts
packages/typedoc-plugin-filter-inherit/tsconfig.json

Refs NEXT_BUILDER-718
请勾选以下两组选项其中之一：
或者：
>
>

feat(): typedoc plugin

---

.npmrc
.yarnrc
packages/create-next-repo/src/patches/replaceInternalUrls.spec.ts
packages/create-next-repo/src/patches/replaceInternalUrls.ts
yarn.lock

Currently the synchronization of npm mirror from taobao is unstable and not timely, we should switch to the original npm registry by default.

fix(): use original npm instead of mirror from taobao

---

etc/brick-kit.api.md
packages/brick-kit/src/core/StoryboardFunctionRegistryFactory.spec.ts
packages/brick-kit/src/core/StoryboardFunctionRegistryFactory.ts
packages/cook/src/cook.spec.ts
packages/cook/src/cook.ts

instead of beforeEvaluate
请勾选以下两组选项其中之一：
或者：
>
>

fix(cook-hooks): use beforeCall for functions

---

packages/brick-container/src/index.tsx
packages/brick-http/src/http.spec.ts
packages/brick-http/src/http.ts

refs NEXT_BUILDER-1908
请勾选以下两组选项其中之一：
或者：
>
>

feat(): support  requestCacheIgnoreList

---

etc/brick-kit.api.md
etc/brick-types.api.md
packages/brick-kit/src/core/Resolver.ts
packages/brick-kit/src/core/StoryboardContext.spec.ts
packages/brick-kit/src/core/StoryboardContext.ts
packages/brick-kit/src/internal/bindListeners.spec.ts
packages/brick-kit/src/internal/bindListeners.ts
packages/brick-types/src/manifest.ts
packages/brick-types/src/runtime.ts

fix(): ignore cache when refresh context

---

etc/brick-types.api.md
packages/brick-kit/src/core/StoryboardContext.spec.ts
packages/brick-kit/src/core/StoryboardContext.ts
packages/brick-kit/src/internal/bindListeners.spec.ts
packages/brick-kit/src/internal/bindListeners.ts
packages/brick-types/src/runtime.ts

feat(): support context/state load/refresh callback

---

packages/brick-kit/src/core/StoryboardContext.ts
packages/brick-kit/src/internal/bindListeners.ts

fix(): fix missing runtime brick in event callback

---

packages/brick-kit/src/core/CustomTemplates/expandCustomTemplate.ts

fix(): to collect contracts before state define

---

etc/brick-types.api.md
packages/brick-kit/src/core/LocationContext.ts
packages/brick-kit/src/history.ts
packages/brick-kit/src/internal/bindListeners.spec.ts
packages/brick-kit/src/internal/bindListeners.ts
packages/brick-kit/src/internal/historyExtended.spec.ts
packages/brick-kit/src/internal/historyExtended.ts
packages/brick-types/src/runtime.ts

with detail about whether the action is blocked
请勾选以下两组选项其中之一：
或者：
>
>

feat(): support history callback

---

packages/brick-container/src/index.tsx

Refs INFRA-001
请勾选以下两组选项其中之一：
或者：
>
>

fix(easyops-analytics): enable api analyzer when open feature flag

---

etc/brick-types.api.md
packages/brick-kit/src/core/LocationContext.ts
packages/brick-types/src/manifest.ts
packages/brick-utils/src/matchPath.spec.ts
packages/brick-utils/src/matchPath.ts

feat(): support router if condition

---

.size-limit.js
packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts

refs NEXT_BUILDER-1769
请勾选以下两组选项其中之一：
或者：
>
>

fix(): should merge userConfig and defaultConfig

---

.size-limit.js
etc/brick-types.api.md
packages/brick-kit/src/core/Router.ts
packages/brick-types/src/runtime.ts

feat(): support emit render info

---

packages/brick-icons/src/BrickIcon.tsx
packages/brick-kit/src/core/Router.spec.ts
packages/brick-kit/src/core/Router.ts
packages/easyops-analytics/src/ApiAnalysis.spec.ts
packages/easyops-analytics/src/ApiAnalysis.ts
packages/easyops-illustrations/src/Illustrations.spec.tsx

Refs NEXT_BUILDER-2059
请勾选以下两组选项其中之一：
或者：
>
>

feat():  收集非pageLoad的api

---

dll/editor-bricks-helper/manifest.snapshot.json
etc/brick-kit.api.md
packages/brick-dll/manifest.snapshot.json
packages/brick-kit/src/getRealValue.spec.ts
packages/brick-kit/src/getRealValue.ts
packages/brick-kit/src/index.ts

feat(): support external usage of getRealValue

---

CONTRIBUTING.md
packages/brick-container/serve/getEnv.js
packages/brick-container/serve/getProxies.js
packages/brick-container/serve/serve.js
packages/brick-container/serve/serveLocal.js
packages/brick-container/serve/utils.js

fix(): support debugging with standalone v2

---

packages/brick-kit/src/hooks/useProvider/fetch.spec.ts
packages/brick-kit/src/hooks/useProvider/fetch.ts

Refs NEXT_BUILDER-2059
请勾选以下两组选项其中之一：
或者：
>
>

fix(useProvider):  compatibility with string of cachekey

---

packages/brick-kit/src/internal/menu.ts

fix(): use self i18n when injecting dynamic menu items

---

packages/dev-dependencies/patch.js

since in our internal CI it has specified `--maxWorkers` by default
请勾选以下两组选项其中之一：
或者：
>
>

fix(test:ci): disable runInBand

---

.size-limit.js
etc/brick-kit.api.md
etc/brick-types.api.md
packages/brick-kit/src/core/StoryboardContext.spec.ts
packages/brick-kit/src/core/StoryboardContext.ts
packages/brick-kit/src/internal/bindListeners.spec.ts
packages/brick-kit/src/internal/bindListeners.ts
packages/brick-types/src/manifest.ts
packages/brick-types/src/runtime.ts

feat(): support batchUpdate context

---

etc/brick-kit.api.md
packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts
packages/brick-kit/src/core/Runtime.ts
packages/brick-kit/src/core/interfaces.ts
packages/brick-kit/src/developHelper.ts

Refs NEXT_BUILDER-3649
请勾选以下两组选项其中之一：
或者：
>
>
当前在编排时直接使用契约预览环境会报错，需要通过手动 build & push 之后再刷新才能正常的显示，因为预览的时候没有对新增的契约做任何处理，所以会找不到该契约定义。
当编排保存的时候，会得到此次修改的内容节点信息，对于该信息的所形成的 storyboard 配置进行扫描，得到新增的契约部分，如果有新增契约的话自动调用 build & push 的操作，把新增的契约信息写进该小产品中
还有关联的另一个 PR
https://github.com/easyops-cn/next-basics/pull/2387

fix(): 修复直接使用契约时，还需要手动 build & push 问题

---

packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts

fix(): load v3-widget-mate before load v3 widgets in v2 container

---

packages/brick-playground/src/index.ts

fix(playground): compress shared example

---

packages/build-next-bricks/bin/post-build-next-bricks.js
packages/build-next-bricks/bin/pre-build-next-bricks.js
packages/build-next-bricks/package.json

feat(): treat other bricks as peer dependencies

---

packages/brick-container/tools/report_installed_brick_next_package.py

fix(): fix v3 widget upload error

---

packages/webpack-config-factory/src/bricks/ScanUseProviderHookContractsPlugin.js

Closes CMDB_CONSUME-231
请勾选以下两组选项其中之一：
或者：
>
>

feat(): userProviderHook使用conditional expression时契约可以被收集

---

declarations/global.d.ts
packages/brick-container/serve/getEnv.js
packages/brick-container/serve/getIndexHtml.js
packages/brick-container/src/index.ejs
packages/brick-container/src/index.tsx
packages/brick-container/webpack/common.js
packages/brick-dll/manifest.snapshot.json
packages/brick-kit/src/ErrorBoundary.tsx
packages/brick-kit/src/core/Router.spec.ts
packages/brick-kit/src/core/Router.ts
packages/easyops-analytics/package.json
packages/easyops-analytics/src/SkywalkingAnalysis.ts
packages/easyops-analytics/src/index.ts
yarn.lock

Closes APM-996
请勾选以下两组选项其中之一：
或者：
>
>

feat(): brick-next接入rum

---

packages/runtime/src/CustomTemplates.spec.ts
packages/runtime/src/CustomTemplates.ts

fix(): tpl proxied methods should return

---

cypress/e2e/sub-routes.spec.js
packages/brick-container/serve/middlewares/standaloneBootstrapJson.js
packages/brick-container/src/BootstrapError.shadow.css
packages/brick-container/src/BootstrapError.ts
packages/brick-container/src/bootstrap.ts
packages/brick-container/src/styles/default.css
packages/loader/src/stableLoadBricks.spec.ts
packages/loader/src/stableLoadBricks.ts
packages/runtime/src/createRoot.spec.ts
packages/runtime/src/createRoot.ts
packages/runtime/src/internal/ErrorNode.spec.ts
packages/runtime/src/internal/ErrorNode.ts
packages/runtime/src/internal/Renderer.spec.ts
packages/runtime/src/internal/Renderer.ts
packages/runtime/src/internal/RendererContext.ts
packages/runtime/src/internal/Router.ts
packages/runtime/src/internal/Runtime.spec.ts
packages/runtime/src/internal/Runtime.ts
packages/runtime/src/internal/i18n.ts

fix(): refine error display

---

packages/build-config-factory/src/generateBrickContracts.js
packages/webpack-config-factory/src/bricks/ScanUseProviderHookContractsPlugin.js

fix(): extract source of contract in contract.yaml

---

.size-limit.js
packages/brick-kit/src/core/CustomTemplates/expandCustomTemplate.ts
packages/brick-kit/src/core/CustomTemplates/replaceSlotWithSlottedBricks.spec.ts
packages/brick-kit/src/core/CustomTemplates/replaceSlotWithSlottedBricks.ts
packages/brick-kit/src/core/CustomTemplates/setupTemplateProxy.ts

feat(): supports slots in template
