packages/brick-container/tools/report_installed_micro_app.py

report_installed_micro_app.py add OBJECT_STORE_SERVICE and UCPRO_DESKTOP_SERVICE env
请勾选以下两组选项其中之一：
或者：
>
>

chore(tools): script add env supported

---

packages/brick-kit/src/setProperties.spec.ts
packages/brick-kit/src/setProperties.ts

fix(): support dataset in properties

---

packages/custom-antd-styles/src/radio.less

fix(custom-antd-style): 修复radio边框缺失

---

packages/brick-utils/src/resolveContextConcurrently.spec.ts
packages/brick-utils/src/resolveContextConcurrently.ts

fix(): fix detecting circular contexts

---

packages/build-config-factory/src/generateBrickDocs.js

Refs NEXT_BUILDER-667
请勾选以下两组选项其中之一：
或者：
>
>

feat(): doc add group field and sort properties

---

packages/easyops-analytics/src/ApiAnalysis.ts

Closes POKEMON-67
请勾选以下两组选项其中之一：
或者：
>
>

fix(): set `code` default value as -1

---

packages/custom-antd-styles/src/button.less
packages/custom-antd-styles/src/var.less

Refs ARTIFACT-174
请勾选以下两组选项其中之一：
或者：
>
>

fix(): use variable to modify small button and input height

---

packages/build-config-factory/src/generateBrickDocs.js

chore(): refine doc

---

etc/brick-types.api.md
packages/brick-container/serve/getEnv.js
packages/brick-types/src/builder.ts
packages/editor-bricks-helper/src/interfaces.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.ts

feat(): contextUpdated

---

packages/editor-bricks-helper/src/internal/BuilderDataManager.ts

refs NEXT_BUILDER-770
请勾选以下两组选项其中之一：
或者：
>
>

fix(builder-date-manager): update nodes when context is updated

---

packages/build-config-factory/src/generateBrickDocs.js

Refs NEXT_BUILDER-677
请勾选以下两组选项其中之一：
或者：
>
>

fix(): fix syntax

---

packages/webpack-config-factory/src/bricks/webpack.base.factory.js

refs BRICK_STORE-1725
请勾选以下两组选项其中之一：
或者：
>
>

feat(webpack): publicPath

---

.github/workflows/lerna-version.yml

chore(ci): sync taobao npm mirror immediately after lerna version

---

packages/brick-dll/manifest.snapshot.json
packages/brick-utils/src/index.ts
packages/brick-utils/src/placeholder/index.ts
packages/brick-utils/src/scanI18NInStoryboard.spec.ts
packages/brick-utils/src/scanI18NInStoryboard.ts
packages/brick-utils/src/scanPermissionActionsInStoryboard.spec.ts

feat(): scan i18n in storyboard

---

packages/brick-dll/manifest.snapshot.json
packages/brick-utils/src/index.ts
packages/brick-utils/src/smartDisplayForEvaluableString.spec.ts
packages/brick-utils/src/smartDisplayForEvaluableString.ts

feat(): get smart display for an evaluable string

---

packages/brick-utils/src/smartDisplayForEvaluableString.spec.ts
packages/brick-utils/src/smartDisplayForEvaluableString.ts

fix(): fix smart display for evaluable string

---

dll/editor-bricks-helper/manifest.snapshot.json
packages/editor-bricks-helper/src/hooks/useRouteList.spec.tsx
packages/editor-bricks-helper/src/hooks/useRouteList.ts
packages/editor-bricks-helper/src/index.ts
packages/editor-bricks-helper/src/interfaces.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.ts

refs NEXT_BUILDER-687
请勾选以下两组选项其中之一：
或者：
>
>

feat(builder-data-manager): useRouteList

---

packages/brick-kit/src/core/Resolver.ts
packages/brick-kit/src/makeProviderRefreshable.spec.ts
packages/brick-kit/src/makeProviderRefreshable.ts

feat(): support to manually stop interval of providers

---

etc/brick-kit.api.md
package.json
packages/brick-kit/src/ErrorBoundary.tsx
packages/dev-dependencies/package.json
yarn.lock

https://github.com/easyops-cn/next-basics/runs/2056369572
https://github.com/microsoft/TypeScript/issues/42773

Revert "Merge pull request #165 from easyops-cn/renovate/typescript-4.x"

---

packages/brick-container/src/styles/editor-bricks-variables.css
packages/editor-bricks-helper/src/DropZone/DropZone.module.css

refs NEXT_BUILDER-702
请勾选以下两组选项其中之一：
或者：
>
>

feat(drop-zone): height

---

packages/editor-bricks-helper/src/DropZone/DropZone.module.css

fix(builder): fix root drop-zone style which let canvas to handle outer margin

---

packages/editor-bricks-helper/src/EditorBrickAsComponent/EditorBrickAsComponent.spec.tsx
packages/editor-bricks-helper/src/EditorBrickAsComponent/EditorBrickAsComponent.tsx

fix(builder): auto determine layout of bricks with no editors

---

.size-limit.js
etc/brick-kit.api.md
packages/brick-kit/src/UpdatingElement.ts
packages/brick-kit/src/decorators/property.spec.ts
packages/brick-kit/src/decorators/property.ts

feat(property): support to ignore decorate for properties

---

packages/build-config-factory/src/generateBrickDocs.js

chore(): support  accessor

---

etc/brick-types.api.md
packages/brick-kit/src/bindListeners.spec.ts
packages/brick-kit/src/bindListeners.ts
packages/brick-kit/src/core/LocationContext.ts
packages/brick-types/src/manifest.ts
packages/brick-types/src/runtime.ts

feat(): support context onChange

---

packages/build-config-factory/package.json
packages/build-config-factory/src/generateBrickDocs.js

chore(): doc support property inherit

---

packages/brick-utils/src/cook/CookVisitor.ts
packages/brick-utils/src/cook/cook.spec.ts
packages/brick-utils/src/cook/supply.ts

NEXT_BUILDER-723
请勾选以下两组选项其中之一：
或者：
>
>

feat(evaluations): support URLSearchParams

---

dll/editor-bricks-helper/manifest.snapshot.json
packages/editor-bricks-helper/src/EditorContainer/EditorContainer.tsx
packages/editor-bricks-helper/src/hooks/useHoverNodeUid.spec.tsx
packages/editor-bricks-helper/src/hooks/useHoverNodeUid.ts
packages/editor-bricks-helper/src/index.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.ts

refs NEXT_BUILDER-715
请勾选以下两组选项其中之一：
或者：
>
>

feat(editor-bricks-helper): useHoverNodeUid

---

packages/brick-container/src/styles/editor-bricks-variables.css

Refs NEXT_BUILDER-703
请勾选以下两组选项其中之一：
或者：
>
>

fix(): css style variable

---

packages/brick-kit/src/core/Kernel.ts
packages/brick-kit/src/core/LocationContext.spec.ts
packages/brick-kit/src/core/LocationContext.ts

fix(): fix z-index of portal bricks

---

packages/editor-bricks-helper/src/EditorContainer/EditorContainer.tsx

refs NEXT_BUILDER-724
请勾选以下两组选项其中之一：
或者：
>
>

fix(editor-container): set dependencies of hoverNodeUid

---

packages/brick-types/src/manifest.ts

docs(): refine doc

---

dll/editor-bricks-helper/manifest.snapshot.json
packages/editor-bricks-helper/src/DropZone/DropZone.tsx
packages/editor-bricks-helper/src/EditorContainer/EditorContainer.module.css
packages/editor-bricks-helper/src/EditorContainer/EditorContainer.tsx
packages/editor-bricks-helper/src/hooks/useShowRelatedNodesBasedOnEvents.spec.tsx
packages/editor-bricks-helper/src/hooks/useShowRelatedNodesBasedOnEvents.ts
packages/editor-bricks-helper/src/index.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.ts
packages/editor-bricks-helper/src/processors/getRelatedNodesBasedOnEvents.spec.ts
packages/editor-bricks-helper/src/processors/getRelatedNodesBasedOnEvents.ts

refs NEXT_BUILDER-724
请勾选以下两组选项其中之一：
或者：
>
>

feat(editor-container): get related nodes based on events

---

etc/brick-kit.api.md
packages/brick-kit/src/core/Runtime.spec.ts
packages/brick-kit/src/core/Runtime.ts
packages/brick-kit/src/core/interfaces.ts
packages/brick-kit/src/evaluate.spec.ts
packages/brick-kit/src/evaluate.ts

feat(): support to check if a micro-app is installed

---

packages/editor-bricks-helper/src/EditorContainer/EditorContainer.module.css
packages/editor-bricks-helper/src/EditorContainer/EditorContainer.tsx
packages/editor-bricks-helper/src/hooks/useHighlightNodes.spec.tsx
packages/editor-bricks-helper/src/hooks/useHighlightNodes.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.ts

refs NEXT_BUILDER-725
请勾选以下两组选项其中之一：
或者：
>
>

feat(editor-bricks-helper): useHighlightNodes

---

packages/custom-antd-styles/src/descriptions.less

Closes GZJF-225
请勾选以下两组选项其中之一：
或者：
>
>

fix(descriptions): dark theme style fixes

---

packages/editor-bricks-helper/src/EditorContainer/EditorContainer.module.css

refs NEXT_BUILDER-724
请勾选以下两组选项其中之一：
或者：
>
>

fix(editor-container): background color

---

packages/brick-container/src/styles/variables.css
packages/custom-antd-styles/src/tag.less

Closes BRICK_STORE-2057
请勾选以下两组选项其中之一：
或者：
>
>

feat(tag): tag标签黑暗模式样式

---

packages/brick-container/src/styles/variables.css
packages/custom-antd-styles/src/tag.less

Closes BRICK_STORE-2057
请勾选以下两组选项其中之一：
或者：
>
>

feat(tag): 填充色tag黑暗模式样式

---

packages/brick-container/src/styles/variables.css
packages/custom-antd-styles/src/tag.less

Closes BRICK_STORE-2057
请勾选以下两组选项其中之一：
或者：
>
>

fix(tag): tag style fix

---

etc/brick-kit.api.md
etc/brick-types.api.md
packages/brick-kit/src/core/Runtime.ts
packages/brick-types/src/manifest.ts

Refs LAUNCHPAD-56
请勾选以下两组选项其中之一：
或者：
>
>

feat(): support sitemap data

---

packages/public-scoped-sdk/index.js

chore(): add public sdk

---

packages/brick-container/src/index.tsx
packages/brick-container/src/styles/business-variables.css
packages/brick-container/src/styles/default.css

fix(business-layout): add css variables and refine sticky footer

---

packages/brick-container/src/styles/default.css
packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts
packages/brick-kit/src/core/Router.ts

NEXT_BUILDER-768
请勾选以下两组选项其中之一：
或者：
>
>

fix(business): support set menu to false in business layout

---

packages/brick-kit/src/core/Router.ts

fix(layout): support an empty string as layoutType

---

packages/brick-kit/src/core/LocationContext.spec.ts
packages/brick-kit/src/core/LocationContext.ts

fix(): match app with longer homepage before shorter ones

---

packages/sdk-scripts/src/lib/FunctionBlock.ts
packages/sdk-scripts/src/loaders/__snapshots__/loadService.spec.ts.snap
packages/sdk-scripts/src/loaders/loadService.spec.ts
packages/sdk-scripts/yaml/api/api_gateway/auth/check_login.yaml

fix(): ignore url prefix for api of api_gateway

---

packages/build-config-factory/src/post-build.js

fix(): do not use fs.rmSync which is added in node v14.14

---

packages/sdk-scripts/src/lib/FunctionBlock.ts
packages/sdk-scripts/src/loaders/__snapshots__/loadService.spec.ts.snap

feat(): print contract as comment for sdk

---

packages/dev-dependencies/patch.js
packages/dev-dependencies/patches/enableSdkRenovate.js
packages/dev-dependencies/patches/enableSdkRenovate.spec.js
packages/dev-dependencies/patches/index.js

New SDKs will contain contract info as comments for each api.
请勾选以下两组选项其中之一：
或者：
>
>

feat(): enable sdk in renovate.json

---

packages/build-config-factory/src/pre-build.js
packages/sdk-scripts/src/lib/Api.ts
packages/sdk-scripts/src/lib/Context.ts
packages/sdk-scripts/src/lib/FunctionBlock.ts
packages/sdk-scripts/src/loaders/__snapshots__/loadService.spec.ts.snap
packages/sdk-scripts/src/loaders/loadService.ts
packages/sdk-scripts/src/main.ts
packages/sdk-scripts/src/manually.ts

feat(): refactory sdk exports, make tree-shaking possible

---

packages/dev-dependencies/patch.js
packages/dev-dependencies/patches/groupSdkRenovate.js
packages/dev-dependencies/patches/groupSdkRenovate.spec.js
packages/dev-dependencies/patches/index.js

feat(renovate): group sdk packages

---

packages/sdk-scripts/src/lib/Api.ts
packages/sdk-scripts/src/loaders/__snapshots__/loadService.spec.ts.snap

fix(): add prefix for interfaces too

---

packages/dev-dependencies/patch.js
packages/dev-dependencies/patches/index.js
packages/dev-dependencies/patches/migrateOfficialRenovate.js
packages/dev-dependencies/patches/migrateOfficialRenovate.spec.js

feat(): enable sdk renovate after migrating official renovate

---

packages/webpack-config-factory/src/bricks/webpack.base.factory.js

chore(): support .svga file

---

packages/brick-kit/package.json
packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts
packages/brick-kit/src/core/checkPermissions.spec.ts
packages/brick-kit/src/core/checkPermissions.ts
packages/brick-kit/src/core/menu.spec.ts
packages/brick-kit/src/core/menu.ts
yarn.lock

fix(): use new sdk

---

packages/sdk-scripts/src/lib/Context.ts
packages/sdk-scripts/src/loaders/__snapshots__/loadService.spec.ts.snap

fix(): no need to generate contracts for sdk packages

---

packages/webpack-config-factory/src/bricks/webpack.prod.factory.js

See https://github.com/terser/terser/issues/983

fix(): workaround for a bug of terser with yield

---

packages/custom-antd-styles/src/form.less

Refs USER_ADMIN-124
请勾选以下两组选项其中之一：
或者：
>
>

fix(): lmodify bussiness input css

---

packages/custom-antd-styles/src/form.less

Refs USER_ADMIN-124
请勾选以下两组选项其中之一：
或者：
>
>

fix(): add select style

---

etc/brick-types.api.md
mock-micro-apps/home/storyboard.yaml
packages/brick-kit/src/core/LocationContext.spec.ts
packages/brick-kit/src/core/LocationContext.ts
packages/brick-types/src/manifest.ts

feat(): support conditional context of free variable

---

packages/editor-bricks-helper/src/DropZone/DropZone.module.css
packages/editor-bricks-helper/src/DropZone/DropZone.tsx
packages/editor-bricks-helper/src/DropZone/getDropPosition.ts
packages/editor-bricks-helper/src/DropZone/processDrop.spec.ts
packages/editor-bricks-helper/src/DropZone/processDrop.ts
packages/editor-bricks-helper/src/interfaces.ts

feat(): support portal canvas

---

etc/brick-types.api.md
packages/brick-kit/src/historyExtended.spec.ts
packages/brick-kit/src/historyExtended.ts
packages/brick-types/src/runtime.ts

feat(): support to keep hash in push/replace query

---

packages/brick-scripts/src/questions/askBrickName.spec.ts
packages/brick-scripts/src/questions/askBrickName.ts

which will be prefixed by `provider-` automatically
请勾选以下两组选项其中之一：
或者：
>
>

fix(): allow brick name without a hyphen for provider

---

etc/brick-types.api.md
packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts
packages/brick-kit/src/core/Router.ts
packages/brick-kit/src/core/menu.spec.ts
packages/brick-kit/src/core/menu.ts
packages/brick-kit/src/evaluate.spec.ts
packages/brick-kit/src/evaluate.ts
packages/brick-kit/src/setProperties.ts
packages/brick-types/src/manifest.ts
packages/brick-types/src/runtime.ts
packages/brick-utils/src/placeholder/compile.spec.ts
packages/brick-utils/src/placeholder/compile.ts

feat(): support to override app in shared menus

---

packages/brick-kit/src/core/menu.ts

fix(menu): restrict menu with app linked

---

dll/editor-bricks-helper/manifest.snapshot.json
packages/editor-bricks-helper/src/DropZone/DropZone.tsx
packages/editor-bricks-helper/src/hooks/useCanDrop.ts
packages/editor-bricks-helper/src/hooks/useCanvasList.spec.tsx
packages/editor-bricks-helper/src/hooks/useCanvasList.ts
packages/editor-bricks-helper/src/index.ts

feat(): support independent portal canvas

---

packages/dev-dependencies/patch.js
packages/dev-dependencies/patches/migrateHusky.js
packages/dev-dependencies/patches/migrateHusky.spec.js
packages/dev-dependencies/patches/updateLicense.js
packages/dev-dependencies/patches/updateLicense.spec.js

fix(): write root package.json at last

---

etc/brick-types.api.md
packages/brick-container/src/index.ejs
packages/brick-container/src/index.tsx
packages/brick-container/src/styles/default.css
packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts
packages/brick-types/src/manifest.ts
packages/brick-types/src/runtime.ts

INFRA-0
请勾选以下两组选项其中之一：
或者：
>
>

feat(): remove header and footer mountpoint

---

etc/brick-kit.api.md
packages/brick-kit/src/core/Runtime.ts
packages/brick-kit/src/core/interfaces.ts
packages/brick-kit/src/core/menu.ts

NEXT_BUILDER-769
请勾选以下两组选项其中之一：
或者：
>
>

feat(): support to fetch menu by menu id

---

packages/public-scoped-sdk/index.js

fix(): set api-gateway as public scoped sdk

---

packages/custom-antd-styles/src/legacy-form.less

fix(): edit antd-form-labele-defaultCss Closes BRICK_STORE-2091

---

packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts

fix(): use new business-website bricks

---

packages/custom-antd-styles/src/legacy-form.less

fix(): Fix the antd style impact button Closes BRICK_STORE-2091

---

packages/custom-antd-styles/src/legacy-form.less

fix(): Fixed 8px influence style issue Closes BRICK_STORE-2091

---

packages/brick-kit/src/core/CustomTemplates/registerCustomTemplate.ts

fix(): fix warn of native prop in tpl

---

.size-limit.js
packages/brick-container/src/index.tsx
packages/brick-container/webpack.common.js
packages/brick-container/webpack.dev.js
packages/brick-container/webpack.prod.js
packages/brick-dll/webpack.dll.js
packages/brick-icons/.gitignore
packages/brick-icons/package.json
packages/brick-icons/rollup.config.js
packages/brick-icons/scripts/pre-build.js
packages/brick-icons/src/BrickIcon.spec.tsx
packages/brick-icons/src/BrickIcon.tsx
packages/brick-icons/src/declarations.d.ts
packages/brick-icons/src/index.ts
packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts
packages/brick-utils/src/getDllAndDepsOfStoryboard.spec.ts
packages/brick-utils/src/getDllAndDepsOfStoryboard.ts
packages/rollup-config-factory/src/index.js
packages/webpack-config-factory/src/dll/webpack.dll.factory.js
packages/webpack-config-factory/src/index.js

feat(): support to async load icons and refine dll js name

---

packages/brick-icons/package.json
packages/brick-icons/src/BrickIcon.spec.tsx
packages/brick-icons/src/BrickIcon.tsx

fix(): refine icons loading

---

packages/brick-kit/src/BrickAsComponent.spec.tsx
packages/brick-kit/src/BrickAsComponent.tsx

fix(BrickAsComponent): skip invoke transformProperties when if is false

---

packages/dev-dependencies/patch.js
packages/dev-dependencies/patches/addMocksForBrickIcons.js
packages/dev-dependencies/patches/addMocksForBrickIcons.spec.js
packages/dev-dependencies/patches/index.js
packages/dev-dependencies/template/__mocks__/@next-core/brick-icons.js

fix(): add mocks for brick-icons

---

packages/create-next-repo/src/__mocks__/customConsole.ts
packages/create-next-repo/src/patches/changeMode.spec.ts
packages/create-next-repo/src/patches/changeMode.ts
packages/create-next-repo/src/patches/index.ts

fix(): change mode for husky hooks

---

packages/custom-antd-styles/src/legacy-form.less

Closes UISIX-112
请勾选以下两组选项其中之一：
或者：
>
>

fix(legacy-form): 修复label内图标不对齐问题

---

packages/custom-antd-styles/src/legacy-form.less

fix(): fix antdStyle Refs BRICK_STORE-2091

---

packages/brick-kit/src/core/Bars/BaseBar.spec.ts
packages/brick-kit/src/core/Bars/BaseBar.ts
packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts

feat(): brick:basic-bricks.menu-bar add testid Closes BRICK_STORE-2139

---

packages/babel-preset-next/index.js
packages/babel-preset-next/package.json

fix(): revert some babel plugins

---

etc/brick-types.api.md
packages/brick-types/src/story.ts
packages/build-config-factory/src/generateBrickDocs.js
packages/editor-bricks-helper/src/EditorBrickAsComponent/EditorBrickAsComponent.spec.tsx
packages/editor-bricks-helper/src/EditorBrickAsComponent/EditorBrickAsComponent.tsx
packages/editor-bricks-helper/src/EditorBrickAsComponent/getBrickDoc.spec.ts
packages/editor-bricks-helper/src/EditorBrickAsComponent/getBrickDoc.ts
packages/editor-bricks-helper/src/EditorBrickAsComponent/getEditorBrick.spec.ts
packages/editor-bricks-helper/src/EditorBrickAsComponent/getEditorBrick.ts
packages/editor-bricks-helper/src/hooks/useStoryList.spec.tsx
packages/editor-bricks-helper/src/hooks/useStoryList.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.ts

Refs NEXT_BUILDER-740
请勾选以下两组选项其中之一：
或者：
>
>

feat(): 支持在文档中声明编辑器

---

etc/brick-types.api.md
packages/brick-types/src/menu.ts

Closes EASY_HUB-170
请勾选以下两组选项其中之一：
或者：
>
>

feat(brick-types): menuIcon.color support gradient color

---

etc/brick-types.api.md
packages/brick-types/src/menu.ts

Closes EASY_HUB-170
请勾选以下两组选项其中之一：
或者：
>
>

feat(brick-types): GradientColor support direction

---

packages/editor-bricks-helper/src/DropZone/processDrop.spec.ts
packages/editor-bricks-helper/src/DropZone/processDrop.ts
packages/editor-bricks-helper/src/interfaces.ts

feat(): support to add bricks with properties

---

dll/editor-bricks-helper/manifest.snapshot.json
packages/editor-bricks-helper/src/index.ts

feat(): export useHighlightNodes

---

packages/dev-dependencies/patch.js
packages/dev-dependencies/patches/index.js
packages/dev-dependencies/patches/updateResolutions.js
packages/dev-dependencies/patches/updateResolutions.spec.js

fix(): add a resolution of @testing-library/dom

---

etc/brick-types.api.md
packages/brick-types/src/story.ts
packages/build-config-factory/src/generateBrickDocs.js
packages/editor-bricks-helper/src/EditorBrickAsComponent/EditorBrickAsComponent.tsx
packages/editor-bricks-helper/src/EditorElementFactory.tsx

Refs NEXT_BUILDER-740
请勾选以下两组选项其中之一：
或者：
>
>

feat(): editor 支持属性设置

---

packages/brick-utils/rollup.config.js
packages/rollup-config-factory/package.json
packages/rollup-config-factory/src/index.js
yarn.lock

chore(): update rollup plugins

---

packages/brick-kit/src/core/Bars/AppBar.spec.ts
packages/brick-kit/src/core/Bars/AppBar.ts
packages/brick-kit/src/core/Bars/MenuBar.spec.ts
packages/brick-kit/src/core/Bars/MenuBar.ts

fix(): fix errors of page title and menu in business layout

---

packages/brick-kit/src/evaluate.spec.ts
packages/brick-kit/src/evaluate.ts
packages/brick-kit/src/i18nText.spec.ts
packages/brick-kit/src/i18nText.ts

feat(evaluate): support I18N_TEXT(data)

---

packages/build-config-factory/src/generateBrickDocs.js

chore(): typedoc add allowInheritedDoc

---

dll/editor-bricks-helper/manifest.snapshot.json
etc/brick-kit.api.md
etc/brick-types.api.md
packages/brick-dll/manifest.snapshot.json
packages/brick-kit/src/index.ts
packages/brick-types/src/builder.ts

refs NEXT_BUILDER-839
请勾选以下两组选项其中之一：
或者：
>
>

chore(): add brick-types BuilderSnippetNode

---

etc/brick-kit.api.md
etc/brick-types.api.md
packages/brick-kit/src/i18nText.ts
packages/brick-types/src/builder.ts
packages/brick-types/src/manifest.ts
packages/brick-types/src/story.ts
packages/editor-bricks-helper/src/DropZone/processDrop.spec.ts
packages/editor-bricks-helper/src/DropZone/processDrop.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts

fix(): refine types and process drop

---

etc/brick-types.api.md
packages/brick-kit/src/i18nText.spec.ts
packages/brick-types/src/builder.ts

fix(): refine types for snippets

---

dll/editor-bricks-helper/manifest.snapshot.json
etc/brick-kit.api.md
packages/brick-dll/manifest.snapshot.json
packages/brick-kit/src/core/Bars/AppBar.ts
packages/brick-kit/src/core/Bars/BaseBar.ts
packages/brick-kit/src/core/Bars/MenuBar.ts
packages/brick-kit/src/core/Runtime.spec.ts
packages/brick-kit/src/core/Runtime.ts
packages/brick-kit/src/core/interfaces.ts
packages/brick-kit/src/index.ts
packages/brick-kit/src/useApplyPageTitle.spec.tsx
packages/brick-kit/src/useApplyPageTitle.ts

feat(): support to apply page title

---

dll/editor-bricks-helper/manifest.snapshot.json
packages/editor-bricks-helper/package.json
packages/editor-bricks-helper/src/DropZone/getSnippetNodeDetail.ts
packages/editor-bricks-helper/src/DropZone/processDrop.spec.ts
packages/editor-bricks-helper/src/DropZone/processDrop.ts
packages/editor-bricks-helper/src/DropZone/reverseNormalize.ts

fix(): refine brick conf to brick node

---

packages/brick-kit/src/bindListeners.spec.ts
packages/brick-kit/src/bindListeners.ts

fix(): handle synchronized callback error

---

packages/sdk-scripts/src/interface.ts
packages/sdk-scripts/src/lib/ObjectType.ts
packages/sdk-scripts/src/lib/TypeDefinition.ts
packages/sdk-scripts/src/lib/UnionType.ts
packages/sdk-scripts/src/loaders/__snapshots__/loadService.spec.ts.snap
packages/sdk-scripts/yaml/api/cd/package/send_message_with_appendix.yaml
packages/sdk-scripts/yaml/model/msgsender/send_message_with_appendix_request.yaml

fix(sdk-scripts): fix form data with ref fields

---

.size-limit.js
packages/editor-bricks-helper/src/DropZone/DropZone.module.css
packages/editor-bricks-helper/src/DropZone/DropZone.tsx
packages/editor-bricks-helper/src/interfaces.ts

fix(builder): support to set canvas mode

---

packages/editor-bricks-helper/src/DropZone/getSnippetNodeDetail.ts
packages/editor-bricks-helper/src/DropZone/processDrop.spec.ts
packages/editor-bricks-helper/src/DropZone/processDrop.ts
packages/editor-bricks-helper/src/interfaces.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.ts
packages/editor-bricks-helper/src/internal/getBuilderNode.spec.ts
packages/editor-bricks-helper/src/internal/getBuilderNode.ts

fix(builder): support to initialize alias of brick nodes

---

etc/brick-types.api.md
packages/brick-types/src/builder.ts

fix(): add types of layer type

---

packages/brick-container/tools/report_installed_brick_next_package.py

Refs NEXT_BUILDER-831
请勾选以下两组选项其中之一：
或者：
>
>

feat(micro_app_service): 修复环境开关的判断条件

---

packages/brick-kit/src/core/Resolver.spec.ts
packages/brick-kit/src/core/Resolver.ts

fix(): fix onReject when resolving context

---

etc/brick-kit.api.md
packages/brick-kit/src/core/CustomApis.spec.ts
packages/brick-kit/src/core/CustomApis.ts
packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts
packages/brick-kit/src/core/__mocks__/MicroAppApiOrchestrationData.ts
packages/brick-kit/src/core/interfaces.ts

Refs NEXT_BUILDER-854
请勾选以下两组选项其中之一：
或者：
>
>

fix(): support contract v2

---

packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts

Refs NEXT_BUILDER-854
请勾选以下两组选项其中之一：
或者：
>
>

fix(): refine contract

---

packages/build-config-factory/src/generateBrickDocs.js

Closes BRICK_STORE-215
请勾选以下两组选项其中之一：
或者：
>
>

chore(build-config-factory): allowInheritedDoc add GraphElement

---

packages/brick-utils/src/cook/CookVisitor.ts
packages/brick-utils/src/cook/PrecookVisitor.ts
packages/brick-utils/src/cook/__snapshots__/cook.spec.ts.snap
packages/brick-utils/src/cook/cook.spec.ts
packages/brick-utils/src/cook/precook.spec.ts
packages/brick-utils/src/cook/supply.ts

feat(cook): support tagged template

---

packages/brick-icons/src/icons/deploy/develop.svg
packages/brick-icons/src/icons/deploy/prerelease.svg
packages/brick-icons/src/icons/deploy/production.svg
packages/brick-icons/src/icons/deploy/test.svg

Refs CD-1982
请勾选以下两组选项其中之一：
或者：
>
>

feat(): add deploy icons

---

packages/build-config-factory/src/generateBrickDocs.js

Closes NEXT_BUILDER-826
请勾选以下两组选项其中之一：
或者：
>
>

feat(story): support parenthesized type

---

packages/brick-container/serve/getEnv.js
packages/brick-container/serve/getProxies.js

请勾选以下两组选项其中之一：
或者：
>
>
cc @Wuqimenga

fix(serve): support to set local snippet packages

---

packages/editor-bricks-helper/src/EditorBrickAsComponent/EditorBrickAsComponent.spec.tsx
packages/editor-bricks-helper/src/EditorBrickAsComponent/EditorBrickAsComponent.tsx

fix(): disable dragging template internal nodes

---

packages/brick-icons/src/icons/easy-view/classic-layout/grid-classic-titlebar-toolbar-content.svg

Refs#BRICK_STORE-2179
请勾选以下两组选项其中之一：
或者：
>
>

chore(brick-icons): upload some layout icons to the easyops icon repo

---

packages/brick-utils/src/builder/normalizeBuilderNode.ts

fix(builder): consider `transformFrom` as a yaml field

---

packages/brick-utils/src/builder/normalizeBuilderNode.ts

fix(builder): fix `transformFrom` in brick nodes

---

packages/brick-kit/src/BrickWrapper.tsx
packages/brick-kit/src/__snapshots__/BrickWrapper.spec.tsx.snap
packages/brick-kit/src/featuraFlags.spec.tsx

fix(): refine feature flags

---

packages/brick-kit/src/handleHttpError.spec.tsx
packages/brick-kit/src/handleHttpError.tsx

Refs: EASY_HUB-258
请勾选以下两组选项其中之一：
或者：
>
>
handleHttpError 提示不支持换行符展示, 现已修复

fix(): httpError style fix

---

packages/editor-bricks-helper/src/DropZone/reverseNormalize.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.ts

fix(builder): update only id and instanceId after node stored

---

etc/brick-types.api.md
packages/brick-kit/src/bindListeners.ts
packages/brick-types/src/manifest.ts

Refs NEXT_BUILDER-854
请勾选以下两组选项其中之一：
或者：
>
>

feat(): useProvider 支持 saveAs 的方法

---

packages/brick-kit/src/core/CustomApis.spec.ts
packages/brick-kit/src/core/CustomApis.ts
packages/brick-kit/src/core/__mocks__/MicroAppApiOrchestrationData.ts

NEXT_BUILDER-854
请勾选以下两组选项其中之一：
或者：
>
>

feat(): api contract support file download

---

packages/brick-kit/src/core/LocationContext.ts
packages/brick-kit/src/core/Router.ts
packages/brick-kit/src/core/__mocks__/LocationContext.ts
packages/easyops-analytics/src/ApiAnalysis.spec.ts
packages/easyops-analytics/src/ApiAnalysis.ts

Closes SERVICE_OBSERVE-280
请勾选以下两组选项其中之一：
或者：
>
>

feat(): add route field for analysis

---

packages/brick-kit/src/core/LocationContext.ts

fix(LocationContext): use hasOwnProperty to check if value exists

---

packages/brick-container/deploy/package.conf.yaml
packages/brick-kit/src/core/menu.spec.ts
packages/brick-kit/src/core/menu.ts

feat(menu): support injecting menu items into a menu group

---

packages/brick-utils/src/scanCustomApisInStoryboard.ts
packages/brick-utils/src/scanI18NInStoryboard.ts
packages/brick-utils/src/scanPermissionActionsInStoryboard.spec.ts
packages/brick-utils/src/scanPermissionActionsInStoryboard.ts

fix(): fix scanning permission actions

---

packages/brick-kit/src/setProperties.spec.ts
packages/brick-kit/src/setProperties.ts

fix(): evaluate lazily for events inside slots of useBrick

---

packages/brick-kit/src/core/menu.spec.ts
packages/brick-kit/src/core/menu.ts

fix(menu): allow injecting menu items in non-group menus

---

etc/brick-kit.api.md
packages/brick-kit/src/BrickAsComponent.spec.tsx
packages/brick-kit/src/BrickAsComponent.tsx
packages/brick-kit/src/internal/getNextStateOfUseBrick.ts
packages/brick-kit/src/setProperties.spec.ts
packages/brick-kit/src/setProperties.ts
packages/brick-kit/src/transformProperties.spec.ts
packages/brick-kit/src/transformProperties.ts

feat(): support transforming data in properties of useBrick

---

packages/brick-kit/src/BrickAsComponent.tsx
packages/brick-kit/src/core/LocationContext.ts
packages/brick-kit/src/internal/listenOnTrackingContext.spec.ts
packages/brick-kit/src/internal/listenOnTrackingContext.ts
packages/brick-kit/src/setProperties.spec.ts
packages/brick-kit/src/setProperties.ts
packages/brick-kit/src/transformProperties.spec.ts
packages/brick-kit/src/transformProperties.ts

feat(): support tracking context in useBrick

---

packages/brick-container/tools/report_installed_brick_next_package.py

chore(micro_app_service): 仅有nb执行脚本

---

packages/webpack-config-factory/src/bricks/webpack.base.factory.js

chore(): support lazy style

---

packages/brick-kit/src/BrickAsComponent.spec.tsx
packages/brick-kit/src/internal/getNextStateOfUseBrick.ts
packages/brick-kit/src/internal/setProperties.spec.ts
packages/brick-kit/src/internal/setProperties.ts
packages/brick-kit/src/transformProperties.spec.ts

fix(): transform useBrick.if lazyly inside useBrick.properties

---

etc/brick-kit.api.md
packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts
packages/brick-kit/src/core/LazyBrickRegistry.spec.ts
packages/brick-kit/src/core/LazyBrickRegistry.ts
packages/brick-kit/src/core/Runtime.ts
packages/brick-kit/src/core/interfaces.ts
packages/brick-utils/src/getDllAndDepsOfStoryboard.spec.ts
packages/brick-utils/src/getDllAndDepsOfStoryboard.ts
packages/webpack-config-factory/src/bricks/webpack.base.factory.js
packages/webpack-config-factory/src/bricks/webpack.prod.factory.js

feat(): support lazy load of bricks

---

.eslintrc
.size-limit.js
dll/editor-bricks-helper/manifest.snapshot.json
packages/babel-preset-next/index.js
packages/babel-preset-next/package.json
packages/brick-container/serve/getEnv.js
packages/brick-container/serve/serveLocal.js
packages/brick-container/serve/utils.js
packages/brick-dll/manifest.snapshot.json
packages/brick-dll/package.json
packages/brick-dll/webpack.dll.js
packages/brick-scripts/src/loaders/__snapshots__/loadTemplate.spec.ts.snap
packages/brick-scripts/src/loaders/loadTemplate.ts
packages/brick-scripts/template/bricks-pkg.json
packages/brick-scripts/template/bricks-pkg/scripts/pre-build.js
packages/brick-scripts/template/bricks-pkg/src/index.spec.ts
packages/build-config-factory/src/pre-build.js
packages/build-config-factory/src/size-limit.js
packages/dev-dependencies/package.json
packages/dev-dependencies/patch.js
packages/dev-dependencies/patches/index.js
packages/dev-dependencies/patches/migrateJestV2.js
packages/dev-dependencies/patches/migrateJestV2.spec.js
packages/dev-dependencies/patches/updateBrickNext.js
packages/dev-dependencies/patches/updateBrickNext.spec.js
packages/jest-config-factory/package.json
packages/jest-config-factory/src/index.js
packages/rollup-config-factory/src/index.js
yarn.lock

to remove babel helper duplications
请勾选以下两组选项其中之一：
或者：
>
>

fix(): use @babel/plugin-transform-runtime

---

packages/build-config-factory/src/pre-build.js
packages/jest-config-factory/src/index.js

fix(): support customized entry for lazy bricks

---

packages/brick-icons/src/icons/honeycomb.svg

chore(): icon color change

---

packages/brick-icons/src/icons/honeycomb.svg

chore(): add honeycomb.svg

---

packages/brick-container/src/styles/variables.css

Refs#NEXT_BUILDER-876
请勾选以下两组选项其中之一：
或者：
>
>

chore(): add a global css variable used in easy-view

---

package.json
packages/brick-container/serve/getEnv.js
packages/brick-container/serve/getProxies.js
packages/brick-container/serve/index.js
packages/brick-container/serve/utils.js

fix(serve): defaults to serve by remote container in remote mode

---

packages/brick-kit/src/internal/getNextStateOfUseBrick.ts
packages/brick-kit/src/internal/setProperties.spec.ts

fix(): make lifeCycle.useResolves.transform as lazy in useBrick

---

packages/brick-kit/src/BrickAsComponent.spec.tsx
packages/brick-kit/src/BrickAsComponent.tsx
packages/brick-kit/src/core/Runtime.ts

fix(): load bricks in dynamic useBrick

---

packages/brick-kit/src/BrickAsComponent.spec.tsx
packages/brick-kit/src/BrickAsComponent.tsx
packages/brick-kit/src/core/Runtime.ts

Reverts easyops-cn/next-core#856

Revert "fix(): load bricks in dynamic useBrick"

---

packages/brick-scripts/template/bricks-pkg.json
packages/dev-dependencies/patches/addPreBuildScriptForBricks.js
packages/dev-dependencies/patches/addPreBuildScriptForBricks.spec.js

fix(): fix pre-build script for bricks

---

packages/brick-utils/src/scanStoryboard.spec.ts
packages/brick-utils/src/scanStoryboard.ts

Refs NEXT_BUILDER-615
请勾选以下两组选项其中之一：
或者：
>
>

fix(): collect useProvider in onChange of context

---

dll/editor-bricks-helper/manifest.snapshot.json
etc/brick-kit.api.md
packages/brick-container/serve/getEnv.js
packages/brick-dll/manifest.snapshot.json
packages/brick-kit/src/BrickAsComponent.spec.tsx
packages/brick-kit/src/BrickAsComponent.tsx
packages/brick-kit/src/checkIf.spec.ts
packages/brick-kit/src/checkIf.ts
packages/brick-kit/src/internal/devtools.ts
packages/brick-kit/src/internal/setProperties.spec.ts
packages/brick-kit/src/internal/setProperties.ts
packages/brick-kit/src/transformProperties.spec.ts
packages/brick-kit/src/transformProperties.ts
packages/brick-utils/src/placeholder/compile.spec.ts
packages/brick-utils/src/placeholder/compile.ts
packages/brick-utils/src/placeholder/index.ts
packages/brick-utils/src/placeholder/interfaces.ts
packages/brick-utils/src/placeholder/lexical.spec.ts
packages/brick-utils/src/placeholder/lexical.ts
packages/brick-utils/src/placeholder/syntax.spec.ts
packages/brick-utils/src/placeholder/syntax.ts

fix(): allow transform and inject in useBrick properties at the same time

---

packages/brick-utils/src/cook/cook.spec.ts
packages/brick-utils/src/cook/supply.ts

feat(): support atob and btoa in evaluations

---

cypress/integration/mocked-home.spec.js
etc/brick-types.api.md
mock-micro-apps/home/storyboard.yaml
packages/brick-kit/src/core/Router.ts
packages/brick-kit/src/core/Runtime.ts
packages/brick-kit/src/internal/bindListeners.spec.ts
packages/brick-kit/src/internal/bindListeners.ts
packages/brick-kit/src/internal/poll.spec.ts
packages/brick-kit/src/internal/poll.ts
packages/brick-types/src/manifest.ts

feat(): support provider poll

---

etc/brick-types.api.md
packages/brick-kit/src/internal/poll.spec.ts
packages/brick-kit/src/internal/poll.ts
packages/brick-types/src/manifest.ts

fix(poll): support expectPollStopImmediately

---

dll/editor-bricks-helper/manifest.snapshot.json
etc/brick-types.api.md
packages/brick-container/deploy/package.conf.yaml
packages/brick-dll/manifest.snapshot.json
packages/brick-kit/src/core/Router.ts
packages/brick-kit/src/internal/menu.ts
packages/brick-kit/src/internal/shouldBeDefaultCollapsed.spec.ts
packages/brick-kit/src/internal/shouldBeDefaultCollapsed.ts
packages/brick-types/src/menu.ts
packages/brick-utils/src/builder/index.ts
packages/brick-utils/src/builder/normalizeMenu.spec.ts
packages/brick-utils/src/builder/normalizeMenu.ts

feat(menu): support defaultCollapsedBreakpoint

---

packages/brick-container/deploy/package.conf.yaml

fix(): update backend depedencies

---

packages/webpack-config-factory/src/bricks/webpack.dev.factory.js

fix(): fix module conflict

---

packages/webpack-config-factory/src/bricks/BrickHashedModuleIdsPlugin.js
packages/webpack-config-factory/src/bricks/webpack.base.factory.js
packages/webpack-config-factory/src/bricks/webpack.dev.factory.js

fix(): prefix module id with package name to avoid collisions

---

packages/brick-utils/src/cook/CookFunctionVisitor.ts
packages/brick-utils/src/cook/PrecookFunctionVisitor.ts
packages/brick-utils/src/cook/cookFunction.spec.ts

fix(storyboard-function): fix arrow function expression

---

etc/brick-types.api.md
packages/brick-kit/src/core/StoryboardFunctions.ts
packages/brick-types/src/manifest.ts
packages/brick-utils/src/cook/PrecookFunctionVisitor.ts
packages/brick-utils/src/cook/__snapshots__/cookFunction.spec.ts.snap
packages/brick-utils/src/cook/cookFunction.spec.ts
packages/brick-utils/src/cook/cookFunction.ts
packages/brick-utils/src/cook/interfaces.ts
packages/brick-utils/src/cook/precookFunction.spec.ts
packages/brick-utils/src/cook/precookFunction.ts
packages/brick-utils/src/cook/utils.ts

feat(): support typescript in storyboard functions

---

packages/brick-utils/src/cook/CookFunctionVisitor.ts
packages/brick-utils/src/cook/PrecookFunctionVisitor.ts
packages/brick-utils/src/cook/cookFunction.spec.ts

fix(cook): support ts as expression

---

etc/brick-types.api.md
packages/brick-types/src/menu.ts

Refs#BRICK_STORE-2278
请勾选以下两组选项其中之一：
或者：
>
>

chore(): add SrcIcon type to MenuIcon

---

packages/brick-kit/src/internal/menu.spec.ts
packages/brick-kit/src/internal/menu.ts

MONITOR-2075
请勾选以下两组选项其中之一：
或者：
>
>

fix(): allow inject multiple menus into one group

---

etc/brick-types.api.md
packages/brick-types/src/menu.ts

Refs#BRICK_STORE-2278MenuIcon
请勾选以下两组选项其中之一：
或者：
>
>

fix(MenuIcon): revert MenuIcon

---

packages/brick-container/deploy/package.conf.yaml

Refs EASY_CONF-27
请勾选以下两组选项其中之一：
或者：
>
>

chore(): modify api_gateway dependency to ^1.18.2

---

packages/brick-utils/src/cook/__snapshots__/cook.spec.ts.snap
packages/brick-utils/src/cook/cook.spec.ts
packages/brick-utils/src/cook/parse.ts
packages/brick-utils/src/cook/precookFunction.spec.ts
packages/brick-utils/src/cook/test-cases/expressions.ts
packages/brick-utils/src/cook/test-cases/negative/expressions.ts

CD-2330
请勾选以下两组选项其中之一：
或者：
>
>
cc @ann2624

fix(cook): use non-strict-mode for expression

---

packages/cook/src/lint.spec.ts
packages/cook/src/lint.ts

fix(lint): fix literals other than regex

---

packages/cook/src/lint.spec.ts
packages/cook/src/lint.ts

fix(lint): fix false negative of var declarations

---

packages/brick-container/src/i18n/index.ts

Refs NEXT_BUILDER-993
请勾选以下两组选项其中之一：
或者：
>
>
浏览器语言为非中英文时，应显示中文（英文的国际化覆盖不全面）

fix(): 修复浏览器语言为非中英文时国际化文本空白问题

---

etc/brick-kit.api.md
etc/brick-types.api.md
packages/brick-container/src/i18n/index.ts
packages/brick-kit/src/core/StoryboardFunctionRegistryFactory.spec.ts
packages/brick-kit/src/core/StoryboardFunctionRegistryFactory.ts
packages/brick-types/src/manifest.ts
packages/cook/src/ExecutionContext.ts
packages/cook/src/cook.spec.ts
packages/cook/src/cook.ts
packages/cook/src/index.ts
packages/cook/src/precook.spec.ts
packages/cook/src/precook.ts

NEXT_BUILDER-996
请勾选以下两组选项其中之一：
或者：
>
>

feat(function): support to collect coverage

---

packages/dev-dependencies/patch.js
packages/dev-dependencies/patches/enableNextLibsRenovate.js
packages/dev-dependencies/patches/enableNextLibsRenovate.spec.js
packages/dev-dependencies/patches/index.js

feat(): enabled next-libs renovate

---

packages/brick-container/src/styles/variables.css

Refs NEXT_BUILDER-1001
请勾选以下两组选项其中之一：
或者：
>
>

chore(): add global css variable used in ui-v8

---

packages/brick-utils/src/builder/normalizeBuilderNode.ts

fix(): make `analyticsData: null` disposable

---

packages/custom-antd-styles/src/table.less

Closes BRICK_STORE-2321
请勾选以下两组选项其中之一：
或者：
>
>

fix(table): fix width of nested empty table keep growing

---

packages/brick-kit/src/internal/evaluate.spec.ts
packages/brick-kit/src/internal/evaluate.ts

feat(): support getting misc settings in storyboard

---

packages/brick-kit/src/internal/bindListeners.ts

fix(): update args during polling

---

packages/brick-kit/src/internal/bindListeners.spec.ts
packages/brick-kit/src/internal/bindListeners.ts

fix(): window.open should follow base href

---

etc/brick-kit.api.md
packages/brick-kit/src/core/Runtime.ts
packages/brick-kit/src/developHelper.ts

请勾选以下两组选项其中之一：
或者：
>
>
- [] 给新特性添加了单元测试。
对外暴露新增API: checkoutContext
BrickPreview渲染时会重新创建LocationContext, 渲染使用上下文跟之前不一致; 然而在进入BrickAsComponent时, 获取到的tplContext仍旧是旧的context, 所以新增此api, 在BrickPreview渲染前做上下文切换, 等待渲染完再将上下文切换回来, 已达到正常工作的目的

feat(developHelper): add checkoutContext api

---

packages/brick-kit/src/internal/bindListeners.spec.ts
packages/brick-kit/src/internal/bindListeners.ts

Reverts easyops-cn/next-core#1106

Revert "fix(): window.open should follow base href"

---

packages/webpack-config-factory/package.json
packages/webpack-config-factory/src/bricks/ScanCustomElementsPlugin.js
packages/webpack-config-factory/src/bricks/ScanTemplatesPlugin.js
packages/webpack-config-factory/src/bricks/webpack.base.factory.js
yarn.lock

feat(): set webpack public path on the fly

---

packages/brick-container/webpack/dev.js

chore: fix devServerOptions import path

---

packages/build-config-factory/src/generateBrickContracts.js
packages/build-config-factory/src/post-build.js
packages/webpack-config-factory/src/bricks/ScanCustomElementsPlugin.js

feat(): general brick contracts for providers

---

packages/build-config-factory/src/generateBrickContracts.js

fix(): use compatible syntax for node.js

---

packages/build-config-factory/src/generateBrickContracts.js
packages/webpack-config-factory/package.json
packages/webpack-config-factory/src/bricks/webpack.base.factory.js
packages/webpack-config-factory/src/bricks/webpack.contracts.factory.js

fix(): ignore worker files when building contracts

---

packages/build-config-factory/src/generateBrickContracts.js

fix(): fix generating brick contracts

---

packages/brick-container/package.json

feat(): add dist-standalone into npm package files

---

declarations/global.d.ts
packages/brick-container/package.json
packages/brick-container/serve/serve.js
packages/brick-container/src/index.ejs
packages/brick-container/webpack.prod.js
packages/brick-container/webpack/common.js
packages/brick-container/webpack/prod.js
packages/brick-kit/src/core/standaloneBootstrap.spec.ts
packages/brick-kit/src/core/standaloneBootstrap.ts

feat(): use a single build for standalone apps

---

packages/build-config-factory/src/generateBrickContracts.js
packages/webpack-config-factory/src/bricks/webpack.base.factory.js

fix(): fix postcss-loader after upgraded postcss to v8

---

packages/brick-container/webpack/common.js

chore(): fix yarn start

---

packages/brick-container/src/styles/default.less

fix(): use composited animations for loading-bar

---

packages/brick-kit/src/core/LocationContext.spec.ts
packages/brick-kit/src/core/LocationContext.ts

Refs: NEXT_BUILDER-1119
请勾选以下两组选项其中之一：
或者：
>
>

feat(locationContext): add noCurrentApp

---

packages/brick-kit/src/core/Router.ts

Refs: NEXT_BUILDER-1119
请勾选以下两组选项其中之一：
或者：
>
>

feat(Router): set noCurrentApp default value

---

packages/brick-container/deploy/package.conf.yaml

fix(): upgrade api gateway version

---

.size-limit.js
packages/brick-container/serve/getProxies.js
packages/brick-container/serve/serveLocal.js
packages/brick-kit/package.json
packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts
packages/brick-kit/src/core/Runtime.ts
yarn.lock

bootstrap 接口替换为 v2 

---

packages/brick-container/deploy/package.conf.yaml
packages/brick-container/serve/getEnv.js
packages/brick-container/serve/getProxies.js

feat(): support legacy bootstrap flag

---

packages/brick-kit/src/core/Router.ts

Refs: NEXT_BUILDER-1134
请勾选以下两组选项其中之一：
或者：
>
>

feat(): use global noCurrentApp as default

---

packages/brick-container/deploy/package.conf.yaml
packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts

fix(): bootstrap 增加开关控制

---

packages/brick-container/serve/getProxies.js
packages/brick-container/serve/serveLocal.js
packages/brick-kit/src/core/Kernel.ts

fix(): get stroyboard v2

---

packages/brick-kit/src/core/Kernel.ts
packages/brick-kit/src/core/Resolver.ts

fix(): fix a regression of caching resolves

---

packages/webpack-config-factory/src/bricks/webpack.base.factory.js

in case of some weird cache behavious would happen
请勾选以下两组选项其中之一：
或者：
>
>

fix(): no `.worker` for worker js

---

packages/brick-container/serve/serveLocal.js
packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts

Refs  QUALITY-203
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 移除之前使用 legcay bootstrap 接口的开关

---

packages/brick-kit/src/core/Router.ts

fix(): fix page tracker

---

packages/brick-kit/src/core/Kernel.ts

fix(): add icons field

---

packages/brick-kit/src/core/Router.spec.ts
packages/brick-kit/src/core/Router.ts

请勾选以下两组选项其中之一：
或者：
>
>
在brick-kit中将请求的状态码暴露出去

feat(): expose http code

---

packages/brick-container/serve/getProxies.js

chore(): apiProxyOption missing

---

packages/build-config-factory/src/generateProviderContracts.js

Refs NEXT_BUILDER-995
请勾选以下两组选项其中之一：
或者：
>
>

fix(): add namespace

---

package.json
packages/brick-container/serve/getEnv.js

fix(): serve with no mock by default in next-core

---

packages/webpack-config-factory/src/bricks/webpack.contracts.factory.js

ignore building node modules other than libs and sdk,
which do not matter with contracts.
cc @panzekun 
请勾选以下两组选项其中之一：
或者：
>
>

fix(): refine generating contracts for bricks

---

packages/build-config-factory/src/generateProviderContracts.js
packages/sdk-scripts/src/lib/Context.ts
packages/sdk-scripts/src/loaders/__snapshots__/loadService.spec.ts.snap
packages/sdk-scripts/src/loaders/__snapshots__/loadTemplate.spec.ts.snap
packages/sdk-scripts/template/rollup.config.js

Refs BRICK_STORE-2324
请勾选以下两组选项其中之一：
或者：
>
>

fix(): rename contract.json -> contracts.json

---

packages/brick-kit/src/BrickAsComponent.tsx

fix(): pass data through tpl in useBrick

---

packages/brick-kit/src/internal/evaluate.spec.ts
packages/brick-kit/src/internal/evaluate.ts

feat(): add new constant BASE_URL in evaluations

---

packages/sdk-scripts/src/loaders/loadService.ts

Refs NEXT_BUILDER-995
请勾选以下两组选项其中之一：
或者：
>
>

fix(): remember clear model i18n

---

package.json
packages/editor-bricks-helper/src/internal/getBuilderNode.spec.ts
packages/editor-bricks-helper/src/internal/getBuilderNode.ts

feat(): display brick alias/id/dataset.testid/brick.name in order

---

packages/webpack-config-factory/src/bricks/webpack.base.factory.js

feat(): support prepending rules

---

dll/editor-bricks-helper/manifest.snapshot.json
packages/brick-dll/manifest.snapshot.json
packages/brick-kit/src/core/StoryboardFunctionRegistryFactory.spec.ts
packages/brick-kit/src/core/StoryboardFunctionRegistryFactory.ts
packages/brick-kit/src/core/WidgetFunctions.ts
packages/brick-kit/src/internal/devtools.ts
packages/brick-kit/src/internal/evaluate.spec.ts
packages/brick-kit/src/internal/evaluate.ts
packages/brick-kit/src/internal/getGeneralGlobals.ts
packages/brick-kit/src/internal/proxyFactories.ts
packages/brick-utils/src/index.ts
packages/brick-utils/src/resolveContextConcurrently.ts
packages/brick-utils/src/scanI18NInStoryboard.ts
packages/brick-utils/src/scanPermissionActionsInStoryboard.spec.ts
packages/brick-utils/src/scanPermissionActionsInStoryboard.ts
packages/brick-utils/src/scanProcessorsInStoryboard.ts
packages/brick-utils/src/visitStoryboard.spec.ts
packages/brick-utils/src/visitStoryboard.ts

feat(): refine storyboard functions and expressions

---

packages/brick-utils/src/visitStoryboard.spec.ts
packages/brick-utils/src/visitStoryboard.ts

fix(): refine visiting storyboard

---

packages/brick-kit/src/internal/evaluate.spec.ts
packages/brick-kit/src/internal/evaluate.ts

fix(): fix accessing not-existed property of QUERY

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css

Refs BRICK_STORE-2342
请勾选以下两组选项其中之一：
或者：
>
>

fix(): modify style

---

CONTRIBUTING.md

docs(): add FAQ about CI errors

---

etc/brick-types.api.md
packages/brick-kit/src/core/Router.ts
packages/brick-kit/src/internal/bindListeners.spec.ts
packages/brick-kit/src/internal/bindListeners.ts
packages/brick-kit/src/themAndMode.spec.tsx
packages/brick-kit/src/themeAndMode.ts
packages/brick-types/src/manifest.ts

Refs BRICK_STORE-1294
请勾选以下两组选项其中之一：
或者：
>
>

feat(): support switch dark-v2

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css
packages/brick-container/src/styles/variables.css

Refs NEXT_BUILDER-1222
请勾选以下两组选项其中之一：
或者：
>
>

fix(): style refactor

---

packages/brick-container/src/index.tsx

Refs: NEXT_BUILDER-1198
请勾选以下两组选项其中之一：
或者：
>
>

feat(httpInterceptors):  update mock url

---

packages/brick-container/serve/getEnv.js
packages/brick-container/serve/getProxies.js
packages/brick-kit/src/internal/evaluate.spec.ts
packages/brick-kit/src/internal/evaluate.ts
packages/brick-kit/src/themeAndMode.ts

Refs NEXT_BUILDER-1240
请勾选以下两组选项其中之一：
或者：
>
>

feat(): dark theme

---

packages/brick-container/src/styles/theme/dark.css
packages/custom-antd-styles/src/var.less

Refs BRICK_STORE-2342
请勾选以下两组选项其中之一：
或者：
>
>

fix(): css variables

---

packages/brick-kit/src/core/Router.ts

Refs OS-120
请勾选以下两组选项其中之一：
或者：
>
>

fix(Router): render call scrollTo before life cycle handler

---

dll/editor-bricks-helper/manifest.snapshot.json
etc/brick-kit.api.md
packages/brick-container/src/index.tsx
packages/brick-dll/manifest.snapshot.json
packages/brick-kit/src/core/MockRegistry.spec.ts
packages/brick-kit/src/core/MockRegistry.ts
packages/brick-kit/src/index.ts

Refs: NEXT_BUILDER-1198
请勾选以下两组选项其中之一：
或者：
>
>

feat(MockRegistry):  remove version in mock url

---

packages/brick-container/scripts/pre-build.js
packages/brick-kit/package.json
packages/brick-kit/rollup.config.js
packages/brick-kit/src/core/Kernel.ts
packages/brick-kit/src/internal/applyColorTheme.spec.ts
packages/brick-kit/src/internal/applyColorTheme.ts
packages/color-theme/src/index.spec.ts
packages/color-theme/src/index.ts
packages/rollup-config-factory/src/index.js

请勾选以下两组选项其中之一：
或者：
>
>
cc @lijmyeah

feat(): apply color theme

---

packages/brick-utils/src/scanI18NInStoryboard.ts
packages/brick-utils/src/scanPermissionActionsInStoryboard.ts
packages/brick-utils/src/visitStoryboard.spec.ts
packages/brick-utils/src/visitStoryboard.ts

fix(): refine some types

---

packages/storyboard-function-types/.gitignore
packages/storyboard-function-types/package.json
packages/storyboard-function-types/scripts/libs/general.js
packages/storyboard-function-types/scripts/libs/lodash.js
packages/storyboard-function-types/scripts/libs/moment.js
packages/storyboard-function-types/scripts/libs/pipes.js
packages/storyboard-function-types/scripts/pre-build.js
packages/storyboard-function-types/src/index.ts
packages/storyboard-function-types/src/interfaces.ts
packages/storyboard-function-types/tsconfig.json

feat(): expose types of builtins for storyboard functions

---

packages/brick-container/serve/getProxies.js
packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css
packages/brick-container/src/styles/variables.css
packages/brick-kit/src/core/Router.ts
packages/brick-kit/src/internal/evaluate.ts
packages/brick-kit/src/internal/getGeneralGlobals.spec.ts
packages/brick-kit/src/internal/getGeneralGlobals.ts
packages/custom-antd-styles/src/card.less
packages/custom-antd-styles/src/var.less

Refs NEXT_BUILDER-1249
请勾选以下两组选项其中之一：
或者：
>
>

feat(): card style

---

.size-limit.js
etc/brick-types.api.md
packages/brick-kit/src/core/FlowApi.spec.ts
packages/brick-kit/src/core/FlowApi.ts
packages/brick-types/src/manifest.ts

Refs: NEXT_BUILDER-1198
请勾选以下两组选项其中之一：
或者：
>
>

feat(FlowApi):  useMock in flow api

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css
packages/brick-container/src/styles/variables.css
packages/custom-antd-styles/src/var.less
packages/less-plugin-css-variables/src/LessReplacer.js

Refs NEXT_BUILDER-1246
请勾选以下两组选项其中之一：
或者：
>
>

feat(): general-radio style

---

packages/brick-kit/src/core/Router.ts
packages/brick-kit/src/handleHttpError.spec.tsx
packages/brick-kit/src/handleHttpError.tsx

fix(): do not redirect to login page while NO_AUTH_GUARD is enabled

---

dll/editor-bricks-helper/manifest.snapshot.json
etc/brick-kit.api.md
packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css
packages/brick-dll/manifest.snapshot.json
packages/brick-kit/src/core/Router.ts
packages/brick-kit/src/index.ts
packages/brick-kit/src/themAndMode.spec.tsx
packages/brick-kit/src/themeAndMode.ts
packages/custom-antd-styles/src/var.less

Refs NEXT_BUILDER-1244
请勾选以下两组选项其中之一：
或者：
>
>

feat():component style

---

packages/cook/src/__fixtures__/iteration-statements/for-of-loops.ts
packages/cook/src/__fixtures__/iteration-statements/index.ts
packages/cook/src/__fixtures__/negative/statements.ts
packages/cook/src/__snapshots__/cook.spec.ts.snap
packages/cook/src/cook.spec.ts
packages/cook/src/cook.ts

fix(): perform iterator close in for-of-loop

---

packages/brick-container/deploy/package.conf.yaml

fix(): do not depend on next_builder_service

---

packages/brick-utils/src/builder/normalizeMenu.ts

Refs: NEXT_BUILDER-1301
请勾选以下两组选项其中之一：
或者：
>
>
- x ] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。

feat(): menu add href field

---

packages/brick-container/src/styles/antd.less
packages/custom-antd-styles/src/popover.less
packages/custom-antd-styles/src/tooltip.less

feat(): add general styles

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css
packages/custom-antd-styles/src/radio.less

Refs NEXT_BUILDER-1244
请勾选以下两组选项其中之一：
或者：
>
>

fix(): fix style

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css
packages/custom-antd-styles/src/transfer.less

Refs NEXT_BUILDER-1251
请勾选以下两组选项其中之一：
或者：
>
>

fix(): fix styles and replace css variables

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css
packages/custom-antd-styles/src/table.less

Refs  NEXT_BUILDER-1222
请勾选以下两组选项其中之一：
或者：
>
>

fix(): style fix

---

packages/brick-container/src/styles/theme/default.css

Refs NEXT_BUILDER-1321
请勾选以下两组选项其中之一：
或者：
>
>

fix(): style refine

---

packages/brick-container/src/styles/variables.css

fix(): adpat to dark v1 theme

---

packages/brick-kit/src/internal/historyExtended.spec.ts
packages/brick-kit/src/internal/historyExtended.ts

fix(): fix history push in standalone apps

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css

feat(): support css variables of rank table

---

packages/brick-container/src/styles/theme/default.css

feat(): support css variables of chart axis

---

packages/brick-container/src/styles/antd.less
packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css
packages/brick-container/src/styles/variables.css
packages/custom-antd-styles/src/calendar.less
packages/custom-antd-styles/src/date-picker.less
packages/custom-antd-styles/src/var.less

Refs BRICK_STORE-2391
请勾选以下两组选项其中之一：
或者：
>
>

feat(): date picker style

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css

Refs BRICK_STORE-2399
请勾选以下两组选项其中之一：
或者：
>
>

feat(): cmdb-instance-modal style

---

packages/custom-antd-styles/src/transfer.less

fix(): modify  transfer styles

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css
packages/custom-antd-styles/src/var.less

fix(): refine style of avatar using css variables

---

packages/brick-container/src/styles/antd.less
packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css
packages/custom-antd-styles/src/slider.less
packages/custom-antd-styles/src/var.less

Refs BRICK_STORE-2396
请勾选以下两组选项其中之一：
或者：
>
>

feat(): slider style

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css

Refs BRICK_STORE-2396
请勾选以下两组选项其中之一：
或者：
>
>

feat(): dashboard style

---

packages/brick-container/src/styles/theme/default.css

Refs BRICK_STORE-2401
请勾选以下两组选项其中之一：
或者：
>
>

fix(): chart tooltip

---

packages/brick-container/serve/getProxies.js
packages/brick-container/serve/serveLocal.js
packages/brick-container/serve/utils.js

fix(): support connect remote in standalone app

---

packages/brick-container/serve/getProxies.js

fix(): fix remote asset root

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css
packages/custom-antd-styles/src/date-picker.less
packages/custom-antd-styles/src/radio.less
packages/custom-antd-styles/src/tag.less

Refs BRICK_STORE-2395
请勾选以下两组选项其中之一：
或者：
>
>

fix(): refine css

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css
packages/custom-antd-styles/src/tag.less

Refs NEXT_BUILDER-1244
请勾选以下两组选项其中之一：
或者：
>
>

fix(): typo

---

packages/brick-container/src/styles/theme/dark.css

Refs NEXT_BUILDER-1255
请勾选以下两组选项其中之一：
或者：
>
>

fix(): modal style

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css

Refs BRICK_STORE-2395
请勾选以下两组选项其中之一：
或者：
>
>

fix(): tag style

---

packages/brick-container/tools/report_installed_theme_template.py

Refs NEXT_BUILDER-1346
请勾选以下两组选项其中之一：
或者：
>
>

feat(theme_report): 主题模板数据上报

---

packages/brick-container/src/styles/theme/default.css

refs BRICK_STORE-2406
请勾选以下两组选项其中之一：
或者：
>
>

fix(style): cascader在light模式下缺少样式

---

packages/custom-antd-styles/src/cascader.less

refs BRICK_STORE-2406
请勾选以下两组选项其中之一：
或者：
>
>

fix(cascader): cascader的options有空数组children时显示空白下级选项

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css

fix(): set color-scheme for specific theme

---

packages/custom-antd-styles/src/cascader.less

refs BRICK_STORE-2406
请勾选以下两组选项其中之一：
或者：
>
>

fix(cascader): cascader的options有空数组children时异常显示分割线

---

packages/brick-container/src/styles/theme/dark.css

refs BRICK_STORE-2406
请勾选以下两组选项其中之一：
或者：
>
>

fix(dark): gray色板区分color和rgba color

---

.size-limit.js
packages/brick-kit/src/EasyopsEmpty/EasyopsEmpty.spec.tsx
packages/brick-kit/src/EasyopsEmpty/EmptySvg.tsx

Refs BRICK_STORE-2375
请勾选以下两组选项其中之一：
或者：
>
>

fix(): empty image

---

packages/brick-container/dev-server/index.js

fix(): fix yarn start error

---

packages/brick-container/src/styles/theme/default.css
packages/custom-antd-styles/src/card.less

Refs NEXT_BUILDER-1249
请勾选以下两组选项其中之一：
或者：
>
>

fix(): card style

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css

Refs NEXT_BUILDER-1258
请勾选以下两组选项其中之一：
或者：
>
>

fix(): add link color

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css
packages/brick-container/src/styles/variables.css
packages/custom-antd-styles/src/collapse.less
packages/custom-antd-styles/src/var.less

Refs BRICK_STORE-2474
请勾选以下两组选项其中之一：
或者：
>
>

fix():collapse style

---

packages/brick-kit/src/core/LocationContext.ts

fix(): resume getTplContext for compatibility

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css

Refs BRICK_STORE-2497
请勾选以下两组选项其中之一：
或者：
>
>

fix(): add v8 css variables

---

packages/brick-kit/src/core/StoryboardContext.ts

fix(): fix state.onChange

---

packages/brick-kit/src/internal/setProperties.spec.ts
packages/brick-kit/src/internal/setProperties.ts

fix(): fix missing tpl context when setting properties by callback

---

packages/brick-kit/src/core/CustomTemplates/CustomTemplateContext.spec.ts
packages/brick-kit/src/core/CustomTemplates/CustomTemplateContext.ts
packages/brick-kit/src/core/StoryboardContext.spec.ts
packages/brick-kit/src/core/StoryboardContext.ts

fix(): fix targetRef on working in state.onChange

---

packages/brick-kit/src/BrickAsComponent.tsx
packages/brick-kit/src/core/CustomTemplates/handleProxyOfCustomTemplate.spec.ts
packages/brick-kit/src/core/CustomTemplates/handleProxyOfCustomTemplate.ts

fix(): fix re-render of useBrick of tpl

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css

Refs BRICK_STORE-2466
请勾选以下两组选项其中之一：
或者：
>
>

fix(): menu brick style

---

packages/brick-container/src/styles/variables.css

Refs NEXT_BUILDER-419
请勾选以下两组选项其中之一：
或者：
>
>

fix(): dark style

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css

Refs BRICK_STORE-2466
请勾选以下两组选项其中之一：
或者：
>
>

fix(): sub menu style

---

packages/brick-kit/src/core/CustomTemplates/propertyMerge.spec.ts
packages/brick-kit/src/core/CustomTemplates/propertyMerge.ts

fix(): mark lazy useBrick for tpl property merge

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css

Refs BRICK_STORE-2481
请勾选以下两组选项其中之一：
或者：
>
>

fix(): log display

---

etc/brick-types.api.md
packages/brick-kit/src/core/LocationContext.ts
packages/brick-kit/src/internal/evaluate.spec.ts
packages/brick-kit/src/internal/evaluate.ts
packages/brick-types/src/runtime.ts

Close NEXT_BUILDER-1386
请勾选以下两组选项其中之一：
或者：
>
>

feat(): 新增`PATH_NAME`常量

---

packages/brick-kit/src/BrickAsComponent.spec.tsx
packages/brick-kit/src/BrickAsComponent.tsx

fix(): fix useBrick lifeCycle couldn't get TPL

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css

Refs BRICK_STORE-2527
请勾选以下两组选项其中之一：
或者：
>
>

fix(): add css variables

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css

Refs BRICK_STORE-2596
请勾选以下两组选项其中之一：
或者：
>
>

fix(): upload style

---

packages/brick-container/src/i18n/index.ts

fix(): fix i18n of moment

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css

Refs BRICK_STORE-2497
请勾选以下两组选项其中之一：
或者：
>
>

add v8 ui variables

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css

feat(): add custom css variables

---

packages/brick-dll/manifest.snapshot.json
packages/brick-kit/src/core/LocationContext.ts
packages/brick-kit/src/core/Router.ts
packages/brick-kit/src/core/Runtime.ts

Refs: NEXT_BUILDER-1424
请勾选以下两组选项其中之一：
或者：
>
>

feat(): support export container data

---

packages/brick-kit/src/EasyopsEmpty/EmptySvg.tsx

Refs BRICK_STORE-2607
请勾选以下两组选项其中之一：
或者：
>
>

fix(): empty icon

---

packages/brick-utils/src/getDllAndDepsOfStoryboard.spec.ts
packages/brick-utils/src/getDllAndDepsOfStoryboard.ts

fix(): fix get deps when brick package has no editors

---

packages/brick-scripts/src/questions/translateListToAutocomplete.ts

feat(): support yarn yo input custom editor

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css
packages/custom-antd-styles/src/select.less

Refs BRICK_STORE-2565
请勾选以下两组选项其中之一：
或者：
>
>

fix(): style modify

---

packages/editor-bricks-helper/src/DropZone/DropZone.module.css
packages/editor-bricks-helper/src/DropZone/DropZone.tsx
packages/editor-bricks-helper/src/EditorBrickAsComponent/EditorBrickAsComponent.tsx
packages/editor-bricks-helper/src/SlotContainer/SlotContainer.tsx

feat(): support dropZone add Empty ClassName

---

packages/brick-container/src/styles/theme/default.css

Refs NEXT_BUILDER-1250
请勾选以下两组选项其中之一：
或者：
>
>

fix(): anchor style

---

packages/editor-bricks-helper/src/EditorBrickAsComponent/getEditorBrick.spec.ts
packages/editor-bricks-helper/src/EditorBrickAsComponent/getEditorBrick.ts

feat(): support get widget editor brick

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css
packages/brick-container/src/styles/variables.css
packages/custom-antd-styles/src/message.less
packages/custom-antd-styles/src/tag.less
packages/custom-antd-styles/src/var.less

Refs BRICK_STORE-2620
请勾选以下两组选项其中之一：
或者：
>
>

fix(): theme style

---

etc/brick-types.api.md
packages/brick-types/src/preview.ts

fix(): add several preview message types

---

dll/editor-bricks-helper/manifest.snapshot.json
packages/brick-dll/manifest.snapshot.json
packages/brick-utils/src/debounceByAnimationFrame.spec.ts
packages/brick-utils/src/debounceByAnimationFrame.ts
packages/brick-utils/src/index.ts

feat(): new util function: debounceByAnimationFrame

---

packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.ts

Refs: NEXT_BUILDER-1459
请勾选以下两组选项其中之一：
或者：
>
>

fix():  fix snippet add bug

---

packages/brick-kit/src/hooks/useProvider/fetch.spec.ts
packages/brick-kit/src/hooks/useProvider/fetch.ts
packages/brick-kit/src/hooks/useProvider/fetchProviderArgs.ts
packages/brick-kit/src/hooks/useProvider/useProvider.spec.tsx
packages/brick-kit/src/hooks/useProvider/useProvider.ts
packages/brick-kit/src/hooks/useProvider/useProviderArgs.spec.ts
packages/brick-kit/src/hooks/useProvider/useProviderArgs.ts
packages/brick-kit/src/hooks/useProvider/useProviderTypes.ts

Closes NEXT_BUILDER-1468
请勾选以下两组选项其中之一：
或者：
>
>

feat(): React组件支持调用skd生成的provider

---

packages/brick-kit/src/core/StoryboardFunctionRegistryFactory.spec.ts
packages/brick-kit/src/core/StoryboardFunctionRegistryFactory.ts
packages/brick-kit/src/internal/evaluate.spec.ts
packages/brick-kit/src/internal/getGeneralGlobals.ts
packages/storyboard-function-types/scripts/libs/general.js

feat(): support console in storyboard functions

---

dll/editor-bricks-helper/manifest.snapshot.json
packages/brick-dll/manifest.snapshot.json
packages/brick-kit/src/core/LocationContext.spec.ts
packages/brick-kit/src/core/LocationContext.ts
packages/brick-kit/src/internal/devtools.spec.ts
packages/brick-kit/src/internal/evaluate.spec.ts
packages/brick-kit/src/internal/evaluate.ts
packages/brick-kit/src/internal/menu.spec.ts
packages/brick-kit/src/internal/menu.ts
packages/brick-utils/src/index.ts
packages/brick-utils/src/scanAppInStoryboard.spec.ts
packages/brick-utils/src/scanAppInStoryboard.ts

Refs: NEXT_BUILDER-1459
请勾选以下两组选项其中之一：
或者：
>
>

feat(): support APP.getMenus

---

packages/brick-kit/src/core/StoryboardFunctionRegistryFactory.spec.ts
packages/brick-kit/src/internal/getGeneralGlobals.ts
packages/brick-utils/src/builder/normalizeBuilderNode.spec.ts
packages/brick-utils/src/builder/normalizeBuilderNode.ts
packages/cook/src/__fixtures__/expressions.ts
packages/cook/src/__fixtures__/negative/expressions.ts
packages/cook/src/__snapshots__/cook.spec.ts.snap
packages/supply/src/index.ts

fix(): ignore `previewSettings` when building route node

---

packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.ts

feat(): move node up or down

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css
packages/custom-antd-styles/src/date-picker.less
packages/custom-antd-styles/src/var.less
packages/less-plugin-css-variables/src/LessReplacer.js

Refs BRICK_STORE-2644
请勾选以下两组选项其中之一：
或者：
>
>

fix(): refine style

---

etc/brick-types.api.md
packages/brick-types/src/preview.ts

fix(preview): add types for context menu on brick

---

packages/brick-container/src/styles/theme/dark.css

Refs NEXT_BUILDER-1246
请勾选以下两组选项其中之一：
或者：
>
>

fix(): switch style

---

packages/custom-antd-styles/src/tree/mixin.less

Refs#BRICK_STORE-2651
请勾选以下两组选项其中之一：
或者：
>
>

feat(): adapt to the dark theme

---

packages/custom-antd-styles/src/tree/mixin.less

chore(): fix styles

---

etc/brick-kit.api.md
packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts
packages/brick-kit/src/core/Runtime.ts
packages/brick-kit/src/developHelper.ts

feat(): support updating storyboard on the fly

---

packages/brick-kit/src/internal/menu.ts

Refs: NEXT_BUILDER-1459
请勾选以下两组选项其中之一：
或者：
>
>

feat(): cache fetchMenu, and APP.getMenu change

---

.size-limit.js
__jest__/setup.ts
etc/brick-types.api.md
packages/brick-kit/src/core/LocationContext.spec.ts
packages/brick-kit/src/core/LocationContext.ts
packages/brick-kit/src/core/Router.spec.ts
packages/brick-kit/src/core/Router.ts
packages/brick-kit/src/internal/evaluate.spec.ts
packages/brick-kit/src/internal/evaluate.ts
packages/brick-kit/src/internal/mediaQuery.spec.ts
packages/brick-kit/src/internal/mediaQuery.ts
packages/brick-types/src/manifest.ts

Closes BRICK_STORE-2530
请勾选以下两组选项其中之一：
或者：
>
>

feat(): add MEDIA gloabl object and onMediaChange life cycle

---

packages/brick-kit/src/core/LocationContext.spec.ts
packages/brick-kit/src/internal/evaluate.spec.ts
packages/brick-kit/src/internal/mediaQuery.spec.ts
packages/brick-kit/src/internal/mediaQuery.ts

refactor(mediaQuery): rename size to breakpoint

---

dll/editor-bricks-helper/manifest.snapshot.json
packages/editor-bricks-helper/src/hooks/useActiveNodeUid.spec.tsx
packages/editor-bricks-helper/src/hooks/useActiveNodeUid.ts
packages/editor-bricks-helper/src/index.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.ts

feat(): set active node

---

packages/webpack-config-factory/package.json
packages/webpack-config-factory/src/bricks/ScanUseProviderHookContractsPlugin.js
packages/webpack-config-factory/src/bricks/webpack.contracts.factory.js
yarn.lock

Refs NEXT_BUILDER-1470
请勾选以下两组选项其中之一：
或者：
>
>

feat(): useProviderHook契约收集

---

.size-limit.js
packages/babel-preset-next/index.js

fix(): use latest version of core-js for babel preset-env

---

packages/brick-kit/src/core/CustomTemplates/expandCustomTemplate.spec.ts
packages/brick-kit/src/core/CustomTemplates/registerCustomTemplate.ts
packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts

feat(): support re-registering custom templates

---

.size-limit.js
etc/brick-kit.api.md
etc/brick-types.api.md
packages/brick-kit/src/core/CollectContracts.spec.ts
packages/brick-kit/src/core/CollectContracts.ts
packages/brick-kit/src/core/FlowApi.spec.ts
packages/brick-kit/src/core/FlowApi.ts
packages/brick-kit/src/core/Router.ts
packages/brick-kit/src/core/interfaces.ts
packages/brick-kit/src/providers/CustomApi.spec.ts
packages/brick-kit/src/providers/CustomApi.ts
packages/brick-types/src/manifest.ts

Refs FLOW_BUILDER-314
请勾选以下两组选项其中之一：
或者：
>
>
契约增加 `ext_fields` 的字段，支持 query 参数和 body 参数，发请求的时候判断是否存在该字段，根据其组装相关参数。
相关参考文档  https://tapd.easyops.local/pages/viewpage.action?pageId=37323352

fix(): contract refactor

---

.size-limit.js
etc/brick-kit.api.md
packages/brick-container/src/index.tsx
packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts
packages/brick-kit/src/core/Router.ts
packages/brick-kit/src/core/Runtime.ts
packages/brick-kit/src/developHelper.ts

feat(): support previewing template by settings

---

packages/brick-kit/src/core/Router.ts

fix(): no need to add a placeholder for template preview

---

packages/custom-antd-styles/src/form.less

chore(): reset css for layout-business

---

packages/brick-container/src/styles/theme/dark.css

Refs BRICK_STORE-2497
请勾选以下两组选项其中之一：
或者：
>
>

fix(): navigation style

---

etc/brick-kit.api.md
etc/brick-types.api.md
packages/brick-kit/src/core/FlowApi.spec.ts
packages/brick-kit/src/core/FlowApi.ts
packages/brick-kit/src/core/interfaces.ts
packages/brick-kit/src/providers/CustomApi.ts
packages/brick-types/src/manifest.ts

Refs C_CENTER-8
请勾选以下两组选项其中之一：
或者：
>
>

fix(): support service name

---

packages/brick-kit/src/core/LocationContext.spec.ts
packages/brick-kit/src/core/LocationContext.ts

fix(): fix getMenu later

---

.gitignore
packages/brick-container/serve/getEnv.js
packages/brick-container/serve/getProxies.js
packages/brick-container/serve/serve.js

fix(): support serving by https

---

packages/brick-kit/src/hooks/useProvider/useProvider.ts

Refs NEXT_BUILDER-1470
请勾选以下两组选项其中之一：
或者：
>
>

fix(): useProvider hook 支持query查询provider

---

packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts

fix(): reload bootstrap again when loading bricks failed

---

packages/brick-container/src/styles/theme/dark.css

Refs: BRICK_STORE-2672
请勾选以下两组选项其中之一：
或者：
>
>

fix(general-button): 适配dark模式下按钮背景色

---

packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts

fix(template-preview): support setting lifeCycle and events

---

packages/brick-kit/src/core/Router.ts

fix(): put template preview route before others

---

etc/brick-types.api.md
packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts
packages/brick-kit/src/internal/bindListeners.spec.ts
packages/brick-kit/src/internal/bindListeners.ts
packages/brick-types/src/manifest.ts
packages/editor-bricks-helper/src/processors/getRelatedNodesBasedOnEvents.ts

fix(): support setting targetRef as array

---

packages/brick-kit/src/core/Router.ts

fix(): put template preview route between specific ones and others

---

packages/custom-antd-styles/src/radio.less

Refs: BRICK_STORE-2686
请勾选以下两组选项其中之一：
或者：
>
>

fix(general-radio): 修改颜色变量

---

packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts

fix(): template preview with context

---

packages/brick-container/src/styles/theme/dark.css

fix(): 修改颜色变量指向

---

packages/brick-kit/src/internal/menu.ts

fix(getMenu): fix menu lose

---

etc/brick-types.api.md
packages/brick-kit/src/core/Router.ts
packages/brick-kit/src/internal/misc.spec.ts
packages/brick-kit/src/internal/misc.ts
packages/brick-types/src/runtime.ts

fix(): fix menu in iframe

---

packages/brick-scripts/src/loaders/__snapshots__/loadTemplate.spec.ts.snap
packages/brick-scripts/src/questions/askTargetType.ts
packages/brick-scripts/template/brick/$PascalBrickName$.spec.tsx
packages/brick-scripts/template/brick/$PascalBrickName$.tsx

we should admit that:
Enzyme is NOT suitable for testing react v17+ any more.
请勾选以下两组选项其中之一：
或者：
>
>

fix(): adopt testing-library instead of enzyme

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css

feat():告警等级颜色修改等优化 Closes SERVICE_OBSERVE-1319

---

packages/editor-bricks-helper/src/internal/getAppendingNodesAndEdges.ts

fix(): override mount point for snippets

---

packages/brick-kit/src/core/StoryboardFunctionRegistryFactory.spec.ts
packages/brick-kit/src/core/StoryboardFunctionRegistryFactory.ts
packages/supply/src/index.ts

fix(): mock _.uniqueId in storyboard functions

---

etc/brick-kit.api.md
packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts
packages/brick-kit/src/core/Router.ts
packages/brick-kit/src/core/Runtime.ts
packages/brick-kit/src/developHelper.ts

feat(): support snippet preview

---

etc/brick-kit.api.md
packages/brick-kit/src/BrickWrapper.tsx

fix(): fix types of BrickWrapper

---

packages/jest-config-factory/src/index.js

fix(): fix transformModulePatterns

---

packages/brick-kit/src/BrickAsComponent.spec.tsx
packages/brick-kit/src/BrickAsComponent.tsx

fix(useBrick): fix update error

---

package.json
packages/brick-dll/manifest.snapshot.json
packages/brick-kit/src/hooks/useProvider/useProvider.spec.tsx
packages/brick-kit/src/themAndMode.spec.tsx
packages/brick-utils/src/scanAppInStoryboard.spec.ts
packages/easyops-analytics/src/userAnalytics.spec.ts
yarn.lock

test(): fix test warnings

---

packages/brick-utils/src/builder/normalizeBuilderNode.spec.ts
packages/brick-utils/src/builder/normalizeBuilderNode.ts

fix(): ignore screenshot in builder nodes

---

.size-limit.js
declarations/global.d.ts
packages/brick-container/package.json
packages/brick-container/serve/getEnv.js
packages/brick-container/serve/serve.js
packages/brick-container/src/index.ejs
packages/brick-container/src/index.tsx
packages/brick-container/webpack/common.js
yarn.lock

for sandbox demo website only
请勾选以下两组选项其中之一：
或者：
>
>

feat(): support mocking global date

---

packages/brick-kit/src/core/MockRegistry.spec.ts
packages/brick-kit/src/core/MockRegistry.ts

Refs: NEXT_BUILDER-1571
请勾选以下两组选项其中之一：
或者：
>
>

feat(mock): update mock rule

---

packages/custom-antd-styles/src/select.less

fix(general-select): 修改select样式

---

packages/custom-antd-styles/src/select.less

Reverts easyops-cn/next-core#1834

Revert "fix(general-select): 修改select样式"

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css

feat(): 补充颜色变量

---

packages/jest-config-factory/src/index.js

feat(): support extending moduleNameMappper

---

etc/brick-types.api.md
packages/brick-kit/src/core/LocationContext.spec.ts
packages/brick-kit/src/core/LocationContext.ts
packages/brick-kit/src/core/Router.ts
packages/brick-kit/src/core/__mocks__/LocationContext.ts
packages/brick-types/src/manifest.ts

refs NEXT_BUILDER-1616
请勾选以下两组选项其中之一：
或者：
>
>

feat(): support lifeCycle.onIntersectionChange

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css
packages/brick-kit/src/internal/bindListeners.ts
packages/custom-antd-styles/src/message.less

fix(): theme dark

---

packages/brick-kit/src/core/MessageDispatcher.spec.ts
packages/brick-kit/src/core/MessageDispatcher.ts
packages/brick-kit/src/internal/proxyFactories.ts
packages/brick-kit/src/websocket/WebSocketService.spec.ts
packages/brick-kit/src/websocket/WebSocketService.ts

Refs PIPELINE-1594
请勾选以下两组选项其中之一：
或者：
>
>

feat(MessageDispatcher): call error callbacks on WS error event

---

packages/brick-utils/src/scanStoryboard.ts

fix(): collect custom template state

---

packages/build-config-factory/src/generateBrickDocs.js

Refs BRICK_STORE-2820
请勾选以下两组选项其中之一：
或者：
>
>

fix(): support group i18n

---

packages/editor-bricks-helper/src/interfaces.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.ts

Refs: NEXT_BUILDER-1619
请勾选以下两组选项其中之一：
或者：
>
>

feat(BuilderDataManager): support preview addNode

---

packages/brick-container/serve/getEnv.js

fix(): update default remote server

---

packages/brick-container/serve/getProxies.js

Refs INFRA-727
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 修复 stories 本地预览

---

packages/editor-bricks-helper/src/interfaces.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.ts

Refs: NEXT_BUILDER-1619
请勾选以下两组选项其中之一：
或者：
>
>

feat(BuilderDataManager): support preview snippet apply

---

packages/editor-bricks-helper/src/interfaces.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.ts

Refs: NEXT_BUILDER-1619
请勾选以下两组选项其中之一：
或者：
>
>

feat(BuilderDataManager):workbenchNodeAdd support redirect parent

---

.size-limit.js
packages/brick-kit/src/core/LocationContext.spec.ts
packages/brick-kit/src/core/LocationContext.ts
packages/brick-kit/src/core/Router.spec.ts
packages/brick-kit/src/core/Router.ts

refs BRICK_STORE-2856
请勾选以下两组选项其中之一：
或者：
>
>

feat(): 增加开关控制6.0或8.0UI的切换

---

packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.ts

Refs: NEXT_BUILDER-1619
请勾选以下两组选项其中之一：
或者：
>
>

fix(BuilderDataManager): add node redirect parent error

---

packages/create-next-repo/src/download.spec.ts
packages/create-next-repo/src/download.ts
packages/create-next-repo/src/getOptions.spec.ts
packages/create-next-repo/src/getOptions.ts

fix(): follow redirect when downloading from github

---

packages/brick-container/src/styles/theme/dark.css

Refs BRICK_STORE-2567
请勾选以下两组选项其中之一：
或者：
>
>

fix(): modify css variables

---

packages/jest-config-factory/src/index.js

Refs NEXT_BUILDER-1470
请勾选以下两组选项其中之一：
或者：
>
>

fix(jest-config-factory): add lazy-bricks  name mapper

---

packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.ts

fix(BuilderDataManage):  sortUid incorrect after add node

---

packages/dev-dependencies/patch.js
packages/dev-dependencies/patches/index.js
packages/dev-dependencies/patches/migrateLazyBricksWithJest.js
packages/dev-dependencies/patches/migrateLazyBricksWithJest.spec.js

Refs NEXT_BUILDER-1470
请勾选以下两组选项其中之一：
或者：
>
>

fix(dev-deps): remove mock lazy bricks form index.spec.ts

---

packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts

refs MONITOR-3647
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 对于任意布局，在路由跳转的时候都应该重置浏览器标题

---

packages/brick-kit/src/core/FlowApi.spec.ts
packages/brick-kit/src/core/FlowApi.ts

fix(): remove the request to fetch contarcts

---

packages/webpack-config-factory/src/bricks/webpack.base.factory.js

chore(): support useLessReplacePlugin

---

packages/brick-container/serve/utils.js

fix(): get local bricks from both @bricks/* and @next-bricks/*

---

packages/brick-dll/package.json
packages/brick-kit/package.json
yarn.lock

Reverts easyops-cn/next-core#1995

Revert "chore(deps): Update dependency react-i18next to ^11.18.0"

---

packages/brick-dll/manifest.snapshot.json
packages/brick-dll/package.json
packages/brick-kit/package.json
yarn.lock

Reverts easyops-cn/next-core#1998

Revert "Revert "chore(deps): Update dependency react-i18next to ^11.18.0""

---

packages/build-config-factory/src/generateBrickDocs.js

Closes BRICK_STORE-2990
请勾选以下两组选项其中之一：
或者：
>
>

feat(generateBrickDocs): support function type

---

etc/brick-types.api.md
packages/brick-types/src/manifest.ts

chore(type): breadcrumbConf add useLocalMenuTitle

---

packages/brick-kit/src/internal/getGeneralGlobals.spec.ts
packages/brick-kit/src/internal/getGeneralGlobals.ts
packages/brick-kit/src/themAndMode.spec.tsx
packages/brick-kit/src/themeAndMode.ts

chore(): THEME object add method getCssPropertyValue

---

packages/brick-kit/src/internal/getGeneralGlobals.spec.ts
packages/brick-kit/src/themAndMode.spec.tsx

chore(): add test case

---

packages/build-config-factory/src/generateBrickDocs.js

Refs BRICK_STORE-2986
请勾选以下两组选项其中之一：
或者：
>
>

fix(generateBrickDocs): support wrapping intersection types in brackets

---

packages/brick-kit/src/core/CustomForms/ExpandCustomForm.spec.ts
packages/brick-kit/src/core/CustomForms/ExpandCustomForm.ts

refactor():变更field数据结构

---

packages/brick-container/src/index.tsx
packages/brick-http/src/http.spec.ts
packages/brick-http/src/http.ts

Refs: NEXT_BUILDER-1692
请勾选以下两组选项其中之一：
或者：
>
>

feat(): support request cache in preview

---

packages/brick-types/package.json

chore: manually bump version

---

etc/brick-kit.api.md
etc/brick-types.api.md
packages/brick-kit/src/core/FlowApi.ts
packages/brick-kit/src/core/interfaces.ts
packages/brick-kit/src/providers/CustomApi.spec.ts
packages/brick-kit/src/providers/CustomApi.ts
packages/brick-types/src/manifest.ts

Refs BRICK_STORE-3005
请勾选以下两组选项其中之一：
或者：
>
>

feat(): contract support upload type

---

packages/brick-http/src/http.spec.ts
packages/brick-http/src/http.ts

fix(http): get error cache

---

packages/brick-dll/manifest.snapshot.json
packages/easyops-illustrations/src/Illustrations.spec.tsx
packages/easyops-illustrations/src/Illustrations.ts

chore(): refine code

---

packages/brick-kit/src/providers/CustomApi.spec.ts
packages/brick-kit/src/providers/CustomApi.ts

fix(): some optimization

---

packages/brick-kit/src/internal/devtools.spec.ts
packages/brick-kit/src/internal/devtools.ts

fix(devtools): try to emit only in idle time

---

packages/brick-container/src/styles/theme/dark.css
packages/brick-container/src/styles/theme/default.css

chore(): 添加颜色变量

---

packages/cook/src/lint.spec.ts
packages/cook/src/lint.ts

fix(): fix linting with var in muti-line

---

packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.ts

feat(): support updateNode update edges

---

packages/brick-kit/src/core/Router.spec.ts
packages/brick-kit/src/core/Router.ts

fix(): do not report 404 when page is empty

---

packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.ts

feat(): support drag snippet not update builder data

---

packages/brick-container/serve/getProxies.js

fix(): intercept hard-code remote root redirct

---

packages/brick-container/serve/getProxies.js

fix(): simplify root redirect interception

---

packages/editor-bricks-helper/src/interfaces.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.ts

feat(): update workbenchTree Drag move

---

packages/brick-kit/src/core/LocationContext.ts
packages/brick-kit/src/core/Router.ts

Refs INSTANCE-2619
请勾选以下两组选项其中之一：
或者：
>
>

feat(brick-kit): 增加两个cmdb模板

---

packages/brick-container/src/index.tsx
packages/brick-http/src/http.spec.ts
packages/brick-http/src/http.ts

feat(http): add match-api-cache event

---

packages/brick-container/src/index.tsx

fix(): fix post message origin

---

packages/brick-container/src/index.tsx

fix(http): post message error

---

packages/brick-container/src/index.tsx

fix(http): fix sender error

---

packages/brick-kit/src/internal/devtools.spec.ts
packages/brick-kit/src/internal/devtools.ts

fix(): ignore emitting if devtools is not presented

---

packages/public-scoped-sdk/index.js

chore():add sdk:form-builder-service-sdk

---

packages/dev-dependencies/patches/migrateLazyBricksWithJest.js
packages/dev-dependencies/patches/migrateLazyBricksWithJest.spec.js

fix(): fix jest migrations when no relevant files

---

packages/editor-bricks-helper/src/interfaces.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.ts
packages/editor-bricks-helper/src/internal/getObjectIdByNode.spec.ts
packages/editor-bricks-helper/src/internal/getObjectIdByNode.ts

fix(): move error

---

packages/brick-kit/src/core/Kernel.ts
packages/brick-kit/src/internal/devtools.ts

fix(devtools): emit messages only if applicable

---

packages/webpack-config-factory/src/bricks/webpack.contracts.factory.js

fix(): refine contract building

---

packages/brick-kit/src/internal/getGeneralGlobals.ts

Refs SERVICE_OBSERVE-1676
请勾选以下两组选项其中之一：
或者：
>
>

feat(brick-kit): support location.host and location.hostname

---

packages/webpack-config-factory/src/bricks/webpack.base.factory.js
packages/webpack-config-factory/src/loaders/gltf-loader.js
packages/webpack-config-factory/src/loaders/utils.js

feat(): support loading gltf

---

etc/brick-types.api.md
packages/brick-container/src/index.tsx
packages/brick-kit/src/auth.ts
packages/brick-types/src/manifest.ts

feat(): http support crsf token

---

packages/brick-kit/src/handleHttpError.spec.tsx
packages/brick-kit/src/handleHttpError.tsx

fix(handleHttpError): 修复请求报错msg超出弹窗的问题  refs INSTANCE-2681

---

packages/brick-kit/src/handleHttpError.spec.tsx
packages/brick-kit/src/handleHttpError.tsx

Reverts easyops-cn/next-core#2132

Revert "fix(handleHttpError): 修复请求报错msg超出弹窗的问题  refs INSTANCE-2681"

---

packages/brick-kit/src/internal/getGeneralGlobals.spec.ts
packages/brick-kit/src/internal/getGeneralGlobals.ts

Refs BRICK_STORE-3040
请勾选以下两组选项其中之一：
或者：
>
>

feat(): support MISC variable

---

.size-limit.js
etc/brick-types.api.md
packages/brick-container/deploy/package.conf.yaml
packages/brick-kit/package.json
packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts
packages/brick-kit/src/internal/menu.spec.ts
packages/brick-kit/src/internal/menu.ts
packages/brick-types/src/manifest.ts
yarn.lock

fix(): fulfill i18n only when loading injected menus

---

packages/brick-container/src/styles/theme/default.css

close none
请勾选以下两组选项其中之一：
或者：
>
>

fix(): addNewColor

---

dll/editor-bricks-helper/manifest.snapshot.json
etc/brick-types.api.md
packages/brick-dll/manifest.snapshot.json
packages/brick-kit/src/core/LocationContext.ts
packages/brick-kit/src/core/Resolver.spec.ts
packages/brick-kit/src/core/Resolver.ts
packages/brick-kit/src/core/StoryboardContext.spec.ts
packages/brick-kit/src/core/StoryboardContext.ts
packages/brick-kit/src/internal/bindListeners.spec.ts
packages/brick-kit/src/internal/bindListeners.ts
packages/brick-types/src/manifest.ts
packages/brick-types/src/runtime.ts
packages/brick-utils/src/track.spec.ts
packages/brick-utils/src/track.ts

feat(): support lazy context

---

packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts

fix(): preview route render error

---

packages/easyops-analytics/src/ApiAnalysis.spec.ts
packages/easyops-analytics/src/ApiAnalysis.ts

Closes POKEMON-258 POKEMON-256
请勾选以下两组选项其中之一：
或者：
>
>

feat(easyops-analytics): support more metric

---

etc/brick-types.api.md
packages/brick-kit/src/i18n/index.ts
packages/brick-kit/src/internal/evaluate.spec.ts
packages/brick-kit/src/internal/evaluate.ts
packages/brick-kit/src/internal/getGeneralGlobals.ts
packages/brick-kit/src/internal/menu.spec.ts
packages/brick-kit/src/internal/menu.ts
packages/brick-kit/src/internal/setProperties.ts
packages/brick-types/src/manifest.ts
packages/brick-types/src/menu.ts
packages/brick-types/src/runtime.ts

feat(): support bundling menu with i18n

---

packages/easyops-analytics/src/ApiAnalysis.spec.ts
packages/easyops-analytics/src/ApiAnalysis.ts

Closes POKEMON-258 POKEMON-256
请勾选以下两组选项其中之一：
或者：
>
>

fix(easyops-analytics): support more metric

---

packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts
packages/brick-kit/src/core/Router.spec.ts
packages/brick-kit/src/core/Router.ts
packages/brick-kit/src/core/Runtime.ts

fix(): drop support for related apps

---

etc/brick-kit.api.md
packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts
packages/brick-kit/src/core/Runtime.ts
packages/brick-kit/src/core/interfaces.ts
packages/cook/src/cook.ts

fix(): remove dead code

---

etc/brick-types.api.md
packages/brick-types/src/story.ts
packages/rollup-config-factory/package.json
packages/rollup-config-factory/src/index.js

Refs BRICK_STORE-3050
请勾选以下两组选项其中之一：
或者：
>
>

feat(): stories rollup factory

---

packages/brick-container/serve/getProxies.js

fix(): fix serve without subdir

---

packages/editor-bricks-helper/src/interfaces.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.ts

feat(BuilderDataManage): support workbenchNodeAdd get sortData

---

dll/editor-bricks-helper/manifest.snapshot.json
etc/brick-types.api.md
packages/brick-dll/manifest.snapshot.json
packages/brick-kit/src/core/CollectContracts.spec.ts
packages/brick-kit/src/core/CollectContracts.ts
packages/brick-kit/src/core/CustomTemplates/expandCustomTemplate.ts
packages/brick-kit/src/core/Router.ts
packages/brick-types/src/manifest.ts
packages/brick-utils/src/index.ts
packages/brick-utils/src/scanStoryboard.ts

Refs BRICK_STORE-3091
请勾选以下两组选项其中之一：
或者：
>
>

feat(): support to use contract in widgets

---

dll/editor-bricks-helper/manifest.snapshot.json
packages/brick-dll/manifest.snapshot.json
packages/brick-utils/src/index.ts
packages/brick-utils/src/makeThrottledAggregation.spec.ts
packages/brick-utils/src/makeThrottledAggregation.ts

feat(): support makeThrottledAggregation

---

packages/brick-kit/src/internal/bindListeners.spec.ts
packages/brick-kit/src/internal/bindListeners.ts

feat(): allow target/targetRef to be set as evaluable string

---

packages/brick-kit/src/core/Router.ts
packages/easyops-analytics/src/ApiAnalysis.spec.ts
packages/easyops-analytics/src/ApiAnalysis.ts

Refs INFRA-001
请勾选以下两组选项其中之一：
或者：
>
>

feat(easyops-analytics): add metic

---

packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts
packages/brick-kit/src/internal/menu.ts

Refs: NEXT_BUILDER-2027
请勾选以下两组选项其中之一：
或者：
>
>

feat(): standalone app not need to request i18n

---

packages/brick-kit/src/internal/bindListeners.spec.ts
packages/brick-kit/src/internal/bindListeners.ts

fix(): target/ targetRef 能够获取事件信息

---

etc/brick-types.api.md
packages/brick-kit/src/core/Kernel.ts
packages/brick-types/src/manifest.ts

feat(): bootstrap add standaloneMode field

---

packages/brick-kit/src/core/Router.ts

feat(): support micro-app jump to standalone-app

---

packages/brick-utils/src/builder/normalizeBuilderNode.ts

fix(): fix router.if was null and return false

---

packages/brick-kit/src/core/LocationContext.ts
packages/brick-kit/src/core/Router.ts

fix(): standalone back and show pageNotFound

---

packages/brick-kit/src/core/Router.ts

fix(): fix standalone jump problem

---

dll/editor-bricks-helper/manifest.snapshot.json
etc/brick-kit.api.md
packages/brick-container/src/index.tsx
packages/brick-dll/manifest.snapshot.json
packages/brick-http/src/errors.ts
packages/brick-http/src/http.spec.ts
packages/brick-http/src/http.ts
packages/brick-kit/src/abortController.spec.ts
packages/brick-kit/src/abortController.ts
packages/brick-kit/src/core/Router.spec.ts
packages/brick-kit/src/core/Router.ts
packages/brick-kit/src/handleHttpError.spec.tsx
packages/brick-kit/src/handleHttpError.tsx
packages/brick-kit/src/index.ts
packages/brick-kit/src/internal/isHttpAbortError.spec.ts
packages/brick-kit/src/internal/isHttpAbortError.ts

Closes NEXT_BUILDER-2059
请勾选以下两组选项其中之一：
或者：
>
>

feat():  support cancel pending requests on route changed

---

etc/brick-types.api.md
packages/brick-types/src/manifest.ts
packages/brick-utils/src/scanStoryboard.spec.ts
packages/brick-utils/src/scanStoryboard.ts

Closes NEXT_BUILDER-2059
请勾选以下两组选项其中之一：
或者：
>
>

feat():  collect useBackend api contract

---

packages/brick-container/serve/getProxies.js

fix(): remove secure cookie flags with non-https

---

packages/build-config-factory/src/size-limit.js

fix(size-limit): support size-limit of chunks and workers

---

packages/brick-kit/src/core/FlowApi.spec.ts
packages/brick-kit/src/core/FlowApi.ts
packages/brick-kit/src/core/Resolver.spec.ts
packages/brick-kit/src/core/Resolver.ts
packages/brick-kit/src/internal/bindListeners.ts
packages/brick-kit/src/providers/CustomApi.spec.ts
packages/brick-kit/src/providers/CustomApi.ts

fix(FlowApi): fix download api without data must pass data argument

---

nx.json
packages/brick-kit/src/internal/historyExtended.ts

fix(): fix history.push with relative paths

---

packages/editor-bricks-helper/src/internal/getBuilderNode.spec.ts
packages/editor-bricks-helper/src/internal/getBuilderNode.ts

fix(): ignore alias which equals to brick name

---

packages/brick-kit/src/core/CustomForms/ExpandCustomForm.spec.ts
packages/brick-kit/src/core/CustomForms/ExpandCustomForm.ts
packages/brick-kit/src/core/CustomForms/__snapshots__/ExpandCustomForm.spec.ts.snap
packages/brick-utils/src/scanStoryboard.ts

Ella/form b UI lder 124

---

packages/brick-kit/src/core/Router.ts

Ref: NEXT_BUILDER-2064
请勾选以下两组选项其中之一：
或者：
>
>

feat(): update appBarTip style

---

packages/webpack-config-factory/src/bricks/webpack.base.factory.js

feat(): support public root with version

---

packages/jest-config-factory/src/index.js

fix(): transform libs entry points

---

packages/brick-utils/src/placeholder/__snapshots__/syntax.spec.ts.snap
packages/brick-utils/src/placeholder/compile.spec.ts
packages/brick-utils/src/placeholder/lexical.spec.ts
packages/brick-utils/src/placeholder/lexical.ts
packages/brick-utils/src/placeholder/syntax.spec.ts

fix(): refine inject error handling

---

packages/brick-icons/src/icons/colored-monitor/load-balancing.svg
packages/brick-icons/src/icons/colored-monitor/www.svg

feat(): add icon

---

packages/brick-kit/src/hooks/useProvider/fetch.spec.ts
packages/brick-kit/src/hooks/useProvider/fetch.ts
packages/brick-kit/src/hooks/useProvider/useProvider.ts
packages/brick-kit/src/hooks/useProvider/useProviderArgsDefaults.ts
packages/brick-kit/src/hooks/useProvider/useProviderTypes.ts

Refs NEXT_BUILDER-2059
请勾选以下两组选项其中之一：
或者：
>
>

feat():  refine useProvider hook

---

packages/brick-container/src/XMLHttpRequest.ts
packages/brick-container/src/index.tsx

fix(): batch set csrftoken with XMLHttpRequest

---

packages/dev-dependencies/patch.js
packages/dev-dependencies/patches/index.js
packages/dev-dependencies/patches/onlyAutoMergePatchVersions.js
packages/dev-dependencies/patches/onlyAutoMergePatchVersions.spec.js

fix(): only auto-merge patch versions

---

packages/brick-kit/src/core/Router.ts

fix(): allow to disable prefetch scripts

---

packages/brick-kit/src/core/Runtime.ts
packages/brick-kit/src/core/matchStoryboard.ts

fix(): handle test env for brick packages

---

package.json
packages/dev-dependencies/package.json
yarn.lock

fix(): downgrade typescript to 4.7.x

---

packages/editor-bricks-helper/src/internal/BuilderDataManager.spec.ts
packages/editor-bricks-helper/src/internal/BuilderDataManager.ts

fix(): update node with unreachable

---

etc/brick-types.api.md
packages/brick-types/src/story.ts

feat(): add new brick types

---

packages/brick-container/tools/report_installed_brick_next_package.py

refs BRICK_STORE-3172
请勾选以下两组选项其中之一：
或者：
>
>

feat(): 上报脚本增加从story解析snippet并上报的逻辑

---

etc/brick-types.api.md
packages/brick-types/src/story.ts

feat(): update interface SnippetConf

---

declarations/global.d.ts
etc/brick-kit.api.md
packages/brick-kit/src/core/StoryboardFunctionRegistryFactory.ts
packages/brick-kit/src/core/WidgetFunctions.ts
packages/brick-kit/src/internal/getGeneralGlobals.ts
packages/brick-kit/src/internal/images.spec.ts
packages/brick-kit/src/internal/images.ts

feat(): support widget images in standalone apps

---

etc/brick-types.api.md
packages/brick-types/src/story.ts

fix(): update type snippetConf

---

etc/brick-types.api.md
packages/brick-types/package.json

chore(): update docs etc

---

packages/brick-kit/src/core/CustomForms/ExpandCustomForm.ts

feat():新增表单预览设置，Refs:FORM_BUILDER-151

---

etc/brick-kit.api.md
packages/brick-kit/src/EasyopsEmpty/EasyopsEmpty.tsx

close BRICK_STORE-3134
请勾选以下两组选项其中之一：
或者：
>
>

fix():  add new properties for easyopsEmpty

---

etc/brick-types.api.md
packages/brick-types/src/story.ts

fix(): fix snippetConf.thumbnail type

---

packages/easyops-analytics/src/ApiAnalysis.ts

Refs NEXT_BUILDER-2059
请勾选以下两组选项其中之一：
或者：
>
>

fix(useProvider): fix status filed as null problem

---

packages/brick-container/src/styles/theme/default.css

chore(style): change pageTitle fontSize to 22

---

packages/brick-kit/src/core/CustomTemplates/expandCustomTemplate.ts

fix(): allow duplicated tpl state names

---

packages/brick-container/serve/getProxies.js
packages/brick-container/serve/utils.js

fix(): merge settings in standalone mode

---

etc/brick-types.api.md
packages/brick-kit/src/internal/menu.spec.ts
packages/brick-kit/src/internal/menu.ts
packages/brick-types/src/menu.ts

refs NEXT_BUILDER-2193
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 修复standalone模式下, APP.homepage 异常的问题

---

.github/workflows/ci.yml
README.md

chore(): refine ci

---

packages/brick-utils/src/scanInstalledAppsInStoryboard.spec.ts
packages/brick-utils/src/scanInstalledAppsInStoryboard.ts

fix(): InstalledApp should check menus

---

packages/brick-kit/src/core/LocationContext.ts

fix(): allow circular templates while detect stack overflow

---

packages/brick-kit/src/hooks/useProvider/useProviderTypes.ts

fix(brick-kit): useProviderType中的RequestInit类型移除HttpOptions中重复存在的cache定义

---

CONTRIBUTING.md
package.json
packages/brick-http/jest.config.js
packages/brick-icons/jest.config.js
packages/brick-kit/jest.config.js
packages/brick-utils/jest.config.js
packages/color-theme/jest.config.js
packages/cook/jest.config.js
packages/create-next-repo/jest.config.js
packages/dev-dependencies/jest.config.js
packages/easyops-analytics/jest.config.js
packages/easyops-illustrations/jest.config.js
packages/editor-bricks-helper/jest.config.js
packages/jest-config-factory/bin/next-jest.js
packages/jest-config-factory/package.json
packages/jest-config-factory/src/findFileUpward.js
packages/jest-config-factory/src/index.js
packages/jest-config-factory/src/next-jest.js
packages/less-plugin-css-variables/jest.config.js
packages/pipes/jest.config.js
packages/repo-config/jest.config.js
packages/sdk-scripts/jest.config.js
packages/storyboard/jest.config.js
packages/supply/jest.config.js

chore(): refine test scripts

---

packages/brick-kit/src/internal/evaluate.spec.ts
packages/brick-kit/src/internal/evaluate.ts

fix(): throw when processors not found

---

etc/brick-types.api.md
packages/brick-kit/src/internal/evaluate.spec.ts
packages/brick-kit/src/internal/evaluate.ts
packages/brick-kit/src/internal/setProperties.spec.ts
packages/brick-kit/src/internal/setProperties.ts
packages/brick-types/src/runtime.ts

fix(): fix ctx evaluations after history.push

---

etc/brick-types.api.md
packages/brick-kit/src/BrickAsComponent.spec.tsx
packages/brick-kit/src/BrickAsComponent.tsx
packages/brick-types/src/manifest.ts
packages/storyboard/src/interfaces.ts
packages/storyboard/src/parseStoryboard.ts

ife_cycle
请勾选以下两组选项其中之一：
或者：
>
>

feat(BrickAsComponent): Add onMount and onUnmount life cycle.

---

packages/brick-kit/src/internal/evaluate.ts
packages/brick-kit/src/internal/setProperties.ts
packages/brick-kit/src/transformProperties.spec.ts
packages/brick-kit/src/transformProperties.ts

fix(): fix tracking context in useBrick

---

packages/brick-kit/src/internal/evaluate.ts
packages/brick-kit/src/transformProperties.spec.ts
packages/brick-kit/src/transformProperties.ts

fix(): memoize data when tracking context in useBrick

---

cypress.config.ts
cypress/e2e/404.spec.js
cypress/e2e/login.spec.js

chore(): simplify e2e

---

packages/dev-dependencies/patch.js
packages/dev-dependencies/patches/enableLernaWithNx.js
packages/dev-dependencies/patches/enableLernaWithNx.spec.js
packages/dev-dependencies/patches/index.js

feat(): enable lerna with nx

---

packages/dev-dependencies/patches/enableLernaWithNx.js
packages/dev-dependencies/patches/enableLernaWithNx.spec.js

fix(): checking dir exists

---

packages/dev-dependencies/patches/enableLernaWithNx.js
packages/dev-dependencies/patches/enableLernaWithNx.spec.js

chore(): format json

---

packages/dev-dependencies/patch.js
packages/dev-dependencies/patches/enableLernaWithNx.js
packages/dev-dependencies/patches/enableLernaWithNx.spec.js

fix(): add missing git ignore of .cache

---

packages/brick-kit/src/core/Kernel.ts

fix(): fix favicon error

---

packages/brick-kit/src/core/Kernel.ts

refs NEXT_BUILDER-2193
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 修复standalone模式下, 额外查询的菜单信息缺少overrideApp的问题

---

packages/brick-container/serve/getEnv.js
packages/brick-container/serve/getProxies.js

fix(): enable cookie-same-site-none by default

---

packages/brick-utils/src/getDllAndDepsOfStoryboard.spec.ts
packages/brick-utils/src/getDllAndDepsOfStoryboard.ts

fix(): refine error message

---

packages/next-docs/package.json
packages/pipes/package.json
packages/storyboard-function-types/package.json
yarn.lock

chore(deps): Update dependency @easyops-cn/brick-next-pipes to ^0.4.0

---

packages/brick-kit/src/providers/CustomApi.ts

fix(): 修复当 request 是 model 类型时，被当作是无参数的情况

---

packages/brick-icons/src/icons/more.svg

chore(icons): add more icon

---

packages/brick-http/src/http.ts

fix(): clear cache if the request is failed

---

CONTRIBUTING.md
packages/brick-container/serve/getEnv.js
packages/brick-container/serve/getIndexHtml.js
packages/brick-container/serve/getProxies.js
packages/brick-container/serve/serve.js
packages/brick-container/serve/serveLocal.js
packages/brick-container/serve/utils.js
packages/brick-kit/src/core/Kernel.ts

fix(): auto detect remote standalone apps

---

packages/brick-container/serve/getEnv.js
packages/brick-container/serve/getProxies.js
packages/brick-container/serve/serve.js
packages/brick-container/serve/serveLocal.js

fix(): fix serve with remote standalone apps

---

packages/brick-kit/src/core/Kernel.ts
packages/brick-kit/src/core/Runtime.ts

Refs BRICK_STORE-3189
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 小产品可以配置 featureFlags 和 misc

---

packages/brick-kit/src/core/Kernel.ts
packages/brick-kit/src/core/Router.ts
packages/brick-kit/src/core/Runtime.ts

Refs BRICK_STORE-3189
请勾选以下两组选项其中之一：
或者：
>
>

fix(): 支持在user_config配置feature_flags和mic配置

---

packages/brick-kit/src/core/Router.spec.ts
packages/brick-kit/src/core/Router.ts
packages/brick-utils/src/getDllAndDepsOfStoryboard.spec.ts
packages/brick-utils/src/getDllAndDepsOfStoryboard.ts
packages/brick-utils/src/index.ts
packages/brick-utils/src/scanBricksInStoryboard.ts
packages/brick-utils/src/scanStoryboard.spec.ts
packages/brick-utils/src/scanStoryboard.ts

fix(): ignore processors in unused tpl

---

packages/brick-container/jest.config.js
packages/brick-container/package.json
packages/brick-container/src/httpCacheAdapter.spec.ts
packages/brick-container/src/httpCacheAdapter.ts
packages/brick-container/src/index.tsx
packages/brick-dll/manifest.snapshot.json
packages/brick-http/src/http.ts
packages/brick-kit/src/core/HttpCache.ts
packages/brick-kit/src/core/Router.spec.ts
packages/brick-kit/src/core/Router.ts

Refs NEXT_BUILDER-2268
请勾选以下两组选项其中之一：
或者：
>
>

feat(): cache http request by cacheAdapter

---

declarations/global.d.ts
packages/brick-kit/src/core/Kernel.spec.ts
packages/brick-kit/src/core/Kernel.ts
packages/brick-kit/src/core/standaloneBootstrap.spec.ts
packages/brick-kit/src/core/standaloneBootstrap.ts
packages/brick-kit/src/internal/getStandaloneInstalledApps.ts

fix(): make parallel requests for runtime api

---

packages/custom-antd-styles/src/table.less

close DESIGNER_ROUTINE-608
请勾选以下两组选项其中之一：
或者：
>
>

feat(): 修改表格自带的过滤样式

---

packages/build-config-factory/src/generateBrickDocs.js

feat(): brick-docs add enums field

---

packages/brick-kit/src/core/CustomForms/ExpandCustomForm.ts

fix(): 修复预览状态下，除表单校验外，其他表单事件无法生效问题

---

packages/brick-kit/src/core/standaloneBootstrap.ts

fix(): fix standalone bootstrap failed to inject menus

---

packages/brick-icons/src/icons/monitor/metricbeat.svg

chore(): 添加icon
